### ISSUE TITLE
H6001 is not currently supported

### ISSUE THREAD

**Issue by HomebridgeX** [bwp91/homebridge-govee#102]
Hello, I get the following message with my Govee Smart LED lamp A19 E27. Many thanks for the help:

[Govee] [Office] is not currently supported, do create a Github issue with the following info:
{"device":"69:7A:03:D8:4B:66:8B:4A","deviceName":"Office","model":"H6001","httpInfo":{"device":"69:7A:03:D8:4B:66:8B:4A","sku":"H6001","spec":"","versionHard":"1.00.05","versionSoft":"2.01.05","deviceName":"Office","deviceExt":{"deviceSettings":"{\"bleName\":\"Minger_H6001_A446\",\"ic\":0,\"sku\":\"H6001\",\"device\":\"697a03d84b668b4a\",\"deviceName\":\"Office\",\"versionHard\":\"1.00.05\",\"versionSoft\":\"2.01.05\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false

**Comment by bwp91** [comment]
Hi @HomebridgeX 

Which platform are you running Homebridge on? Ability to control this device via Homebridge will require bluetooth capability.

This normally works well for example if Homebridge is on a raspberry pi and (fairly) close to the device, but on the other hand does not work at all if Homebridge is installed on a mac.

**Comment by HomebridgeX** [comment]
Hello @bwp91 

my Homebridge runs on a Raspberry Pi. 

Other bleutooth devices from Govee can already be controlled without any problems. Only this one lamp brings the error from above. The error comes immediately when starting the Homebridge.

**Comment by bwp91** [comment]
Yes, it's not really an error, I have designed it this way for models that I have not added to the 'official' supported list.

Could you update to the beta version of the plugin, 4.4.2-beta.3, where I have added the H6001 to the bluetooth-only list.

Once installed and restarted, this device should then appear in Homebridge/HomeKit and control will be attempted via bluetooth.

Let me know!

**Comment by HomebridgeX** [comment]
All right, I'll test it and get back to you.

**Comment by HomebridgeX** [comment]
The error after starting the Homebridge is gone:

[Office] initializing with options {"adaptiveLightingShift": 0, "bluetooth": "enabled", "brightnessStep": 1, "logging": "standard"}.
[Office] initialized with id [69: 7A: 03: D8: 4B: 66: 8B: 4A].

But controlling the lamp fails:

[Office] could not be updated as BLE took too long at BluetoothLED.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:157:15).

The Raspberry is less than a meter away from the lamp with no obstacles.

**Comment by bwp91** [comment]
Do you get this `could not be updated as BLE took too long` message _every_ time you attempt to control the device? Or mostly? Only sometimes?

**Comment by HomebridgeX** [comment]
I get the message every time I try to control the device.

**Comment by bwp91** [comment]
I have just released v4.4.2-beta.5 which gives the plugin a slightly more amount of time to connect and send a command to bluetooth-only devices.

There are many potential reasons why the `could not be updated as BLE took too long` message might appear.

* The RPi can't find/discover the govee device at all
* The RPi can't find/discover the govee device in the amount of time the plugin lets
* The device is already connected via bluetooth to the govee app
* The device has the 'device safety' turned on via the govee app - i'm not exactly sure how this works but I would imagine it stops the device from connecting to other bluetooth devices except phone?

The bluetooth implementation isn't perfect - it's great when it works, but sometimes it _just_ doesn't.

It's extremely difficult to debug this when it works for some people and not for others.

One other thing I can suggest is making sure you've followed the steps for bluetooth control at:

https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control#homebridge-rpi-image

**Comment by HomebridgeX** [comment]
Good evening, 

thank you for the effort. Unfortunately, it doesn't work with the new version either.

I looked at the topic of device safety and noticed something interesting: This lamp does not have the function. On my LED stripe, that works, the function is available in the app and deactivated.

All in all, it won't be a problem for me if we end the case here and mark the lamp as incompatible. 

I am very happy that my LED stripe is working, that is the most important. 

Thank you very much!

**Comment by bwp91** [comment]
If you turn on plugin debug logging (not homebridge debug) via the plugins settings, and try to control this H6001, can you get me the logs that appear?

**Comment by HomebridgeX** [comment]
[14/08/2021, 11:48:12] [Govee] [noble] scanning started.
[14/08/2021, 11:48:15] [Govee] [noble] scanning started.
[14/08/2021, 11:48:18] [Govee] [noble] scanning started.
[14/08/2021, 11:48:20] [Govee] [Office] could not be updated as  at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-govee/node_modules/p-queue/dist/index.js:8:22).
[14/08/2021, 11:48:20] [Govee] [noble] scanning started.
[14/08/2021, 11:48:21] [Govee] [noble] scanning started.
[14/08/2021, 11:48:23] [Govee] [noble] scanning started.
[14/08/2021, 11:48:24] [Govee] [Office] reverting to API as BLE took too long.
[14/08/2021, 11:48:26] [Govee] [noble] scanning started.
[14/08/2021, 11:48:28] [Govee] [Office] could not be updated as  at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-govee/node_modules/p-queue/dist/index.js:8:22).
[14/08/2021, 11:48:29] [Govee] [noble] scanning started.
[14/08/2021, 11:48:32] [Govee] [Office] reverting to API as BLE took too long.

**Comment by bwp91** [comment]
Will try one more thing, can you update to 4.4.2-beta.7 and then try to control the H6001 again. and get me the logs.
It _should_ list the bluetooth addresses that the scanner finds. Be interesting to see if the H6001 is there at all.
Thanks

**Comment by HomebridgeX** [comment]
I see a lot of MAC addresses in the log, but the 69:7A:03:D8:4B:66:8B:4A is not there.

**Comment by bwp91** [comment]
Was `03:D8:4B:66:8B:4A` there?

**Comment by HomebridgeX** [comment]
No

**Comment by HomebridgeX** [comment]
I can see the MAC address of my LED strip that is working.

**Comment by bwp91** [comment]
Do any of the addresses in the list end with `a4:46`?

**Comment by HomebridgeX** [comment]
Yes, I see this address.

**Comment by bwp91** [comment]
What is the address?

**Comment by HomebridgeX** [comment]
a4:c1:38:e6:a4:46

**Comment by bwp91** [comment]
Try updating to 4.4.2-beta.8, I have added an option in the 'Light Devices' section called 'Custom Bluetooth Address' you can try putting `a4:c1:38:e6:a4:46` as the value then restart the plugin and trying to control the bulb. The plugin will attempt to connect to the address you entered.

**Comment by HomebridgeX** [comment]
[15/08/2021, 13:56:47] [Govee] [noble] scanning started.
[15/08/2021, 13:56:50] [Govee] found a4:c1:38:e6:a4:46
[15/08/2021, 13:56:50] [Govee] [noble] scanning stopped.
[15/08/2021, 13:56:50] [Govee] [Office] has been reported [discoverable] via BLE.
[15/08/2021, 13:56:50] [Govee] [Office] has been reported [connected] via BLE.
[15/08/2021, 13:56:50] [Govee] [Office] has been reported [disconnected] via BLE.
[15/08/2021, 13:56:53] [Govee] [noble] scanning started.
[15/08/2021, 13:56:53] [Govee] found a4:c1:38:e6:a4:46
[15/08/2021, 13:56:53] [Govee] [noble] scanning stopped.
[15/08/2021, 13:56:53] [Govee] [Office] has been reported [discoverable] via BLE.
[15/08/2021, 13:56:53] [Govee] [Office] has been reported [connected] via BLE.
[15/08/2021, 13:56:53] [Govee] [Office] has been reported [disconnected] via BLE.
[15/08/2021, 13:56:55] [Govee] [Office] could not be updated as timeout of 8 seconds exceeded.
[15/08/2021, 13:56:55] [Govee] [noble] scanning started.
[15/08/2021, 13:56:55] [Govee] found a4:c1:38:e6:a4:46
[15/08/2021, 13:56:55] [Govee] [noble] scanning stopped.
[15/08/2021, 13:56:55] [Govee] [Office] has been reported [discoverable] via BLE.
[15/08/2021, 13:56:55] [Govee] [Office] has been reported [connected] via BLE.
[15/08/2021, 13:56:55] [Govee] [Office] has been reported [disconnected] via BLE.
[15/08/2021, 13:56:56] [Govee] [noble] scanning started.
[15/08/2021, 13:56:56] [Govee] found a4:c1:38:e6:a4:46
[15/08/2021, 13:56:56] [Govee] [noble] scanning stopped.
[15/08/2021, 13:56:56] [Govee] [Office] has been reported [discoverable] via BLE.
[15/08/2021, 13:56:56] [Govee] [Office] has been reported [connected] via BLE.
[15/08/2021, 13:56:56] [Govee] [Office has been reported [disconnected] via BLE.
[15/08/2021, 13:56:58] [Govee] [noble] scanning started.
[15/08/2021, 13:56:58] [Govee] found a4:c1:38:e6:a4:46
[15/08/2021, 13:56:58] [Govee] [noble] scanning stopped.
[15/08/2021, 13:56:58] [Govee] [Office] has been reported [discoverable] via BLE.
[15/08/2021, 13:56:58] [Govee] [Office] has been reported [connected] via BLE.
[15/08/2021, 13:56:58] [Govee] [Office] has been reported [disconnected] via BLE.
[15/08/2021, 13:57:01] [Govee] [noble] scanning started.
[15/08/2021, 13:57:01] [Govee] found a4:c1:38:e6:a4:46
[15/08/2021, 13:57:01] [Govee] [noble] scanning stopped.
[15/08/2021, 13:57:01] [Govee] [Office] has been reported [discoverable] via BLE.
[15/08/2021, 13:57:01] [Govee] [Office] has been reported [connected] via BLE.
[15/08/2021, 13:57:01] [Govee] [Office] has been reported [disconnected] via BLE.
[15/08/2021, 13:57:03] [Govee] [Office] could not be updated as timeout of 8 seconds exceeded.

**Comment by bwp91** [comment]
So looks like the plugin is able to find and connect to the device - is it reponding to commands?

**Comment by HomebridgeX** [comment]
Unfortunately not.

**Comment by bwp91** [comment]
This is a shame. Feels like we were *nearly* there!
Most likely this model uses different bluetooth commands than the other models. So far it has been successful with all models but there was always a chance that a small number of models would behave differently.

**Comment by HomebridgeX** [comment]
I found this on an Amazon review: 

For the hobbyists among us: - Commands go via Bluetooth low energy, easy to understand how this works (especially if you use the Bluetooth HCI logger in Android) - There is only one characteristic (00: 01: 02: 03: 04: 05: 06: 07: 08: 09: 0A: 0B: 0C: 0D: 2B: 11) to send commands that can be tested with nRF Connect super - If you also want to tinker, there are projects on GitLab that you can use for this.

**Comment by bwp91** [comment]
This is exactly the characteristic that is used in the code, you can see this on this line:

https://github.com/bwp91/homebridge-govee/blob/119daf8d76be7b621ac5c7b62ef49ada681461fe/lib/connection/ble.js#L110

It might be the actual commands that are sent to this characteristic are different for this model. For example for all models so far, to turn ON `0x01 0x1` is sent and to turn off `0x01 0x0` is sent. Maybe for this H6001, the commands are different...

**Comment by bwp91** [comment]
Hi @HomebridgeX 

I have finally purchased a H6001 device and set it up today. I am able to change on/off, brightness and colour successfully from HomeKit.

You want to give it another try with yours?

**Comment by HomebridgeX** [comment]
Thanks for the answer, I'll try it out later and get back to you.

**Comment by HomebridgeX** [comment]
It works, thank you very much!

**Comment by bwp91** [comment]
Nothing has really changed which is weird! But great it’s working!
