### ISSUE TITLE
H6179 Device is not currently supported

### ISSUE THREAD

**Issue by dibsies** [bwp91/homebridge-govee#105]
* **Please explain your feature request in one or two sentences.**

Log statement mentions submitting a GitHub request to add support for H6179.

* **Is your feature request related to a problem? Please describe.**

```
[Govee] is not currently supported, do create a Github issue with the following info:
{"device":"D1:E1:A4:C1:38:A4:E5:88","deviceName":"Master Bedroom","model":"H6179","httpInfo":{"device":"D1:E1:A4:C1:38:A4:E5:88","sku":"H6179","spec":"","versionHard":"1.00.01","versionSoft":"1.00.08","deviceName":"Master Bedroom","deviceExt":{"deviceSettings":"{\"bleName\":\"ihoment_H6179_E588\",\"pactType\":1,\"pactCode\":1,\"ic\":0,\"sku\":\"H6179\",\"device\":\"D1:E1:A4:C1:38:A4:E5:88\",\"deviceName\":\"Master Bedroom\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.00.08\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"http://s3.amazonaws.com/govee-public/sku-img/3f041315d5d107b58ad9dba300f45c0c-add_list_type_device_6179.png\",\"headOnImg\":\"http://s3.amazonaws.com/govee-public/sku-img/4eed25c2240e4c46f216d99f3ca83b9a-new_light_title_6182_on.png\",\"headOffImg\":\"http://s3.amazonaws.com/govee-public/sku-img/5f6d71e8e0d2d9d8c4a83f099cea25e5-new_light_title_6104_off.png\",\"ext\":\"\",\"ic\":0}"},"pactType":1,"pactCode":1,"goodsType":12},"isAPIDevice":false}
```

* **Any particular Govee devices that this relates to?**

H6179

**Comment by bwp91** [comment]
Welcome!

I have just released a test version of the plugin, if you update to this version then the H6179 will appear in Homebridge. See
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version
for details of installing this beta version.

Since this device can only be controlled via bluetooth, you _may_ need to install some extra packages or do extra steps to get the bluetooth working on your homebridge 'machine'.

Which platform are you running Homebridge on? Raspberry pi?

Unfortunately the bluetooth does not work at all on more recent versions of macOS.

**Comment by dibsies** [comment]
Yup, Raspberry Pi. I will give this a shot and report back. Thank you!

**Comment by dibsies** [comment]
It looks like I was able to get them added with the beta. Unfortunately, whenever I try to do something with the devices in homekit I get the following:

```
[18/08/2021, 14:11:42] [Govee] [Living Room] could not be updated as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1056:17.
[18/08/2021, 14:11:42] [Govee] [Living Room] could not be updated as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1056:17.
[18/08/2021, 14:12:19] [Govee] [Master Bedroom] could not be updated as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1056:17.
[18/08/2021, 14:12:19] [Govee] [Master Bedroom] could not be updated as not available or enabled at /usr/local/lib/node_modules/homebridge-govee/lib/index.js:1056:17.
```

**Comment by dibsies** [comment]
Bummer, after restarting homebridge I now get the following:

`[18/08/2021, 14:20:49] [Govee] Disabling BLE client as ENODEV, No such device at GoveePlatform.pluginSetup (/usr/local/lib/node_modules/homebridge-govee/lib/index.js:350:18).
[18/08/2021, 14:20:49] [Govee] ***** Disabling plugin. *****
[18/08/2021, 14:20:49] [Govee] ***** No devices found to initialise. *****`

**Comment by bwp91** [comment]
which raspberry pi do you have? do you know if it has bluetooth capability?

**Comment by dibsies** [comment]
Pi 3 Model B+ - equipped with Bluetooth 4.2/BLE

**Comment by bwp91** [comment]
if you haven’t already, do try to run the commands linked at this address via ssh:

https://github.com/bwp91/homebridge-govee/wiki/Bluetooth-Control#homebridge-rpi-image

**Comment by dibsies** [comment]
I had actually already tried that. One odd observation is that in Homebridge on the plugin settings > MY DEVICES, I see the following:

```
Govee Model
H6179

API Supported
No

AWS Supported
No

Bluetooth Supported 
Yes

Bluetooth Enabled 
No
```

Strange, as I have BLE control ticked in the settings :/

**Comment by dibsies** [comment]
I should note that one of those Bluetooth commands returns an error: 

`sudo setcap cap_net_raw+eip $(eval readlink -f which node)`
`unable to set CAP_SETFCAP effective capability: Operation not permitted`

**Comment by dibsies** [comment]
My apologies -- I _thought_ I had a 3 B+, it appears I have a 2 B v1.2. 

How embarrassing. This must have been in the closet longer than I thought. Thank you for your help.

**Comment by bwp91** [comment]
Ah gutting!
You can use the config to hide this device from homekit to remove it.
Or obviously upgrade the pi… or maybe a bluetooth dongle?
I haven’t known the plugin to either work or not using an older pi and a dongle but I’d assume that it would!

**Comment by dibsies** [comment]
Just wanted to add that I bought an $8 Bluetooth 4.0 dongle from Amazon - installed it today and all of my Govee lights are now working flawlessly! Too cool. Thank you so much for your help. Should I continue using the beta or was support for H6179 added to stable?

**Comment by dibsies** [comment]
It probably would have helped if I read the change log 🙃. The last question I have is I noticed on the H6179 devices the brightness state only seems to work upon the first activation of the light. 

E.g., 
off —> on with brightness to 100% ✅
adjust brightness from 100% to 40% ❌
Turn light off, turn back on at 40% ✅

Is this expected behavior? No biggie just wondering if I did something wrong somewhere.

**Comment by bwp91** [comment]
Are there any warnings/errors in the homebridge log when you try to change the brightness? Can you turn plugin debug mode on and try to change the brightness and post the logs here?

**Comment by dibsies** [comment]
Not seeing any errors in the log... from what I can see the logs seem to indicate that it's working fine.

```
[27/08/2021, 07:01:12] [Govee] [noble] scanning started.
[27/08/2021, 07:01:12] [Govee] [noble] scanning stopped.
[27/08/2021, 07:01:12] [Govee] [Master Bedroom] has been reported [discoverable] via BLE.
[27/08/2021, 07:01:13] [Govee] [Master Bedroom] has been reported [connected] via BLE.
[27/08/2021, 07:01:13] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 07:01:14] [Govee] [Master Bedroom] current state [off].
[27/08/2021, 07:01:17] [Govee] [Master Bedroom] [BLE] sending update {1: 1}.
[27/08/2021, 07:01:17] [Govee] [noble] scanning started.
[27/08/2021, 07:01:17] [Govee] [Master Bedroom] current state [on].
[27/08/2021, 07:01:23] [Govee] [Master Bedroom] [BLE] sending update {4: 181}.
[27/08/2021, 07:01:23] [Govee] [noble] scanning started.
[27/08/2021, 07:01:23] [Govee] [Master Bedroom] current brightness [71%].
[27/08/2021, 07:01:24] [Govee] [Master Bedroom] [BLE] sending update {4: 127}.
[27/08/2021, 07:01:24] [Govee] [noble] scanning started.
[27/08/2021, 07:01:24] [Govee] [Master Bedroom] current brightness [50%].
[27/08/2021, 07:01:24] [Govee] [Master Bedroom] [BLE] sending update {4: 117}.
[27/08/2021, 07:01:25] [Govee] [noble] scanning started.
[27/08/2021, 07:01:25] [Govee] [Master Bedroom] current brightness [46%].
[27/08/2021, 07:01:25] [Govee] [Master Bedroom] [BLE] sending update {4: 114}.
[27/08/2021, 07:01:25] [Govee] [noble] scanning started.
[27/08/2021, 07:01:26] [Govee] [Master Bedroom] current brightness [45%].
[27/08/2021, 07:01:30] [Govee] [Master Bedroom] [BLE] sending update {4: 84}.
[27/08/2021, 07:01:30] [Govee] [noble] scanning started.
[27/08/2021, 07:01:30] [Govee] [Master Bedroom] current brightness [33%].
[27/08/2021, 07:01:31] [Govee] [Master Bedroom] [BLE] sending update {4: 68}.
[27/08/2021, 07:01:31] [Govee] [noble] scanning started.
[27/08/2021, 07:01:31] [Govee] [Master Bedroom] current brightness [27%].
[27/08/2021, 07:01:32] [Govee] [Master Bedroom] [BLE] sending update {4: 61}.
[27/08/2021, 07:01:32] [Govee] [noble] scanning started.
[27/08/2021, 07:01:32] [Govee] [Master Bedroom] current brightness [24%].
[27/08/2021, 07:01:43] [Govee] [Master Bedroom] has been reported [disconnected] via BLE.
[27/08/2021, 07:01:48] [Govee] [noble] scanning started.
[27/08/2021, 07:01:48] [Govee] [noble] scanning stopped.
[27/08/2021, 07:01:48] [Govee] [Master Bedroom] has been reported [discoverable] via BLE.
[27/08/2021, 07:01:48] [Govee] [Master Bedroom] has been reported [connected] via BLE.
[27/08/2021, 07:01:49] [Govee] [Master Bedroom] [BLE] sending update {4: 119}.
[27/08/2021, 07:01:49] [Govee] [Master Bedroom] current brightness [47%].
[27/08/2021, 07:01:50] [Govee] [Master Bedroom] [BLE] sending update {4: 137}.
[27/08/2021, 07:01:50] [Govee] [noble] scanning started.
[27/08/2021, 07:01:50] [Govee] [Master Bedroom] current brightness [54%].
[27/08/2021, 07:01:51] [Govee] [Master Bedroom] [BLE] sending update {4: 153}.
[27/08/2021, 07:01:51] [Govee] [noble] scanning started.
[27/08/2021, 07:01:51] [Govee] [Master Bedroom] current brightness [60%].
[27/08/2021, 07:01:52] [Govee] [Master Bedroom] [BLE] sending update {4: 163}.
[27/08/2021, 07:01:52] [Govee] [noble] scanning started.
[27/08/2021, 07:01:52] [Govee] [Master Bedroom] current brightness [64%].
[27/08/2021, 07:01:53] [Govee] [Master Bedroom] [BLE] sending update {4: 178}.
[27/08/2021, 07:01:53] [Govee] [noble] scanning started.
[27/08/2021, 07:01:53] [Govee] [Master Bedroom] current brightness [70%].
[27/08/2021, 07:01:53] [Govee] [Master Bedroom] [BLE] sending update {4: 147}.
[27/08/2021, 07:01:54] [Govee] [noble] scanning started.
[27/08/2021, 07:01:54] [Govee] [Master Bedroom] current brightness [58%].
[27/08/2021, 07:01:54] [Govee] [Master Bedroom] [BLE] sending update {4: 119}.
[27/08/2021, 07:01:54] [Govee] [noble] scanning started.
[27/08/2021, 07:01:55] [Govee] [Master Bedroom] current brightness [47%].
[27/08/2021, 07:01:55] [Govee] [Master Bedroom] [BLE] sending update {4: 91}.
[27/08/2021, 07:01:55] [Govee] [noble] scanning started.
[27/08/2021, 07:01:56] [Govee] [Master Bedroom] current brightness [36%].
[27/08/2021, 07:01:56] [Govee] [Master Bedroom] [BLE] sending update {4: 153}.
[27/08/2021, 07:01:56] [Govee] [noble] scanning started.
[27/08/2021, 07:01:57] [Govee] [Master Bedroom] current brightness [60%].
[27/08/2021, 07:01:57] [Govee] [Master Bedroom] [BLE] sending update {4: 181}.
[27/08/2021, 07:01:57] [Govee] [noble] scanning started.
[27/08/2021, 07:01:58] [Govee] [Master Bedroom] current brightness [71%].
[27/08/2021, 07:01:58] [Govee] [Master Bedroom] [BLE] sending update {4: 130}.
[27/08/2021, 07:01:58] [Govee] [noble] scanning started.
[27/08/2021, 07:01:59] [Govee] [Master Bedroom] current brightness [51%].
[27/08/2021, 07:01:59] [Govee] [Master Bedroom] [BLE] sending update {4: 127}.
[27/08/2021, 07:01:59] [Govee] [noble] scanning started.
[27/08/2021, 07:02:00] [Govee] [Master Bedroom] current brightness [50%].
[27/08/2021, 07:02:00] [Govee] [Master Bedroom] [BLE] sending update {4: 175}.
[27/08/2021, 07:02:00] [Govee] [noble] scanning started.
[27/08/2021, 07:02:00] [Govee] [Master Bedroom] current brightness [69%].
[27/08/2021, 07:02:01] [Govee] [Master Bedroom] [BLE] sending update {4: 181}.
[27/08/2021, 07:02:01] [Govee] [noble] scanning started.
[27/08/2021, 07:02:01] [Govee] [Master Bedroom] current brightness [71%].
[27/08/2021, 07:02:02] [Govee] [Master Bedroom] [BLE] sending update {4: 214}.
[27/08/2021, 07:02:02] [Govee] [noble] scanning started.
[27/08/2021, 07:02:02] [Govee] [Master Bedroom] current brightness [84%].
[27/08/2021, 07:02:03] [Govee] [Master Bedroom] [BLE] sending update {4: 234}.
[27/08/2021, 07:02:03] [Govee] [noble] scanning started.
[27/08/2021, 07:02:03] [Govee] [Master Bedroom] current brightness [92%].
[27/08/2021, 07:02:04] [Govee] [Master Bedroom] [BLE] sending update {4: 255}.
[27/08/2021, 07:02:04] [Govee] [noble] scanning started.
[27/08/2021, 07:02:04] [Govee] [Master Bedroom] current brightness [100%].
[27/08/2021, 07:02:05] [Govee] [Master Bedroom] [BLE] sending update {4: 229}.
[27/08/2021, 07:02:05] [Govee] [noble] scanning started.
[27/08/2021, 07:02:05] [Govee] [Master Bedroom] current brightness [90%].
[27/08/2021, 07:02:06] [Govee] [Master Bedroom] [BLE] sending update {4: 214}.
[27/08/2021, 07:02:06] [Govee] [noble] scanning started.
[27/08/2021, 07:02:06] [Govee] [Master Bedroom] current brightness [84%].
[27/08/2021, 07:02:07] [Govee] [Master Bedroom] [BLE] sending update {4: 170}.
[27/08/2021, 07:02:07] [Govee] [noble] scanning started.
[27/08/2021, 07:02:07] [Govee] [Master Bedroom] current brightness [67%].
[27/08/2021, 07:02:08] [Govee] [Master Bedroom] [BLE] sending update {4: 163}.
[27/08/2021, 07:02:08] [Govee] [noble] scanning started.
[27/08/2021, 07:02:08] [Govee] [Master Bedroom] current brightness [64%].
[27/08/2021, 07:02:09] [Govee] [Master Bedroom] [BLE] sending update {4: 61}.
[27/08/2021, 07:02:09] [Govee] [noble] scanning started.
[27/08/2021, 07:02:09] [Govee] [Master Bedroom] current brightness [24%].
[27/08/2021, 07:02:10] [Govee] [Master Bedroom] [BLE] sending update {4: 30}.
[27/08/2021, 07:02:10] [Govee] [noble] scanning started.
[27/08/2021, 07:02:10] [Govee] [Master Bedroom] current brightness [12%].
[27/08/2021, 07:02:11] [Govee] [Master Bedroom] [BLE] sending update {5: [2,221,0,255]}.
[27/08/2021, 07:02:11] [Govee] [noble] scanning started.
[27/08/2021, 07:02:11] [Govee] [Master Bedroom] current colour [rgb 221 0 255].
[27/08/2021, 07:02:13] [Govee] [Master Bedroom] [BLE] sending update {4: 155}.
[27/08/2021, 07:02:13] [Govee] [noble] scanning started.
[27/08/2021, 07:02:14] [Govee] [Master Bedroom] current brightness [61%].
[27/08/2021, 07:02:14] [Govee] [Master Bedroom] [BLE] sending update {4: 255}.
[27/08/2021, 07:02:14] [Govee] [noble] scanning started.
[27/08/2021, 07:02:15] [Govee] [Master Bedroom] current brightness [100%].
[27/08/2021, 07:02:20] [Govee] [Master Bedroom] [BLE] sending update {4: 0}.
[27/08/2021, 07:02:20] [Govee] [noble] scanning started.
[27/08/2021, 07:02:20] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 07:02:20] [Govee] [noble] scanning started.
[27/08/2021, 07:02:21] [Govee] [Master Bedroom] current state [off].
[27/08/2021, 07:02:33] [Govee] [Master Bedroom] has been reported [disconnected] via BLE.
```

It lets me change the color just fine, but as for brightness I have to go back to zero, then to whatever brightness to get it to respond to that command.

**Comment by bwp91** [comment]
Can you update to 4.7.1-beta.0 to see if this has made any difference?

I've made a bit of a horrible workaround for the H6179 only, where it sends a command to turn the device off when and before sending a command to change the brightness...

**Comment by dibsies** [comment]
The latest beta doesn't seem to do the trick. Now, when I adjust the brightness, the light turns off but doesn't come back on. Also, from off to a random brightness level doesn't seem to work anymore, as the light no longer reliably turns back on. In theory, that seems like a great workaround, though!

Here's the debug logs if helpful:

[27/08/2021, 08:02:52] [Govee] [noble] scanning started.
[27/08/2021, 08:02:52] [Govee] [noble] scanning stopped.
[27/08/2021, 08:02:52] [Govee] [Master Bedroom] has been reported [discoverable] via BLE.
[27/08/2021, 08:02:52] [Govee] [Master Bedroom] has been reported [connected] via BLE.
[27/08/2021, 08:02:53] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:02:53] [Govee] [Master Bedroom] current state [off].
[27/08/2021, 08:02:58] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:02:58] [Govee] [noble] scanning started.
[27/08/2021, 08:02:58] [Govee] [Master Bedroom] [BLE] sending update {1: 1}.
[27/08/2021, 08:02:58] [Govee] [noble] scanning started.
[27/08/2021, 08:02:59] [Govee] [Master Bedroom] [BLE] sending update {4: 147}.
[27/08/2021, 08:02:59] [Govee] [Master Bedroom] current state [on].
[27/08/2021, 08:02:59] [Govee] [noble] scanning started.
[27/08/2021, 08:02:59] [Govee] [Master Bedroom] current brightness [58%].
[27/08/2021, 08:03:00] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:03:00] [Govee] [noble] scanning started.
[27/08/2021, 08:03:00] [Govee] [Master Bedroom] [BLE] sending update {4: 209}.
[27/08/2021, 08:03:00] [Govee] [noble] scanning started.
[27/08/2021, 08:03:01] [Govee] [Master Bedroom] current brightness [82%].
[27/08/2021, 08:03:01] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:03:01] [Govee] [noble] scanning started.
[27/08/2021, 08:03:02] [Govee] [Master Bedroom] [BLE] sending update {4: 255}.
[27/08/2021, 08:03:02] [Govee] [noble] scanning started.
[27/08/2021, 08:03:02] [Govee] [Master Bedroom] current brightness [100%].
[27/08/2021, 08:03:06] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:03:06] [Govee] [noble] scanning started.
[27/08/2021, 08:03:06] [Govee] [Master Bedroom] current state [off].
[27/08/2021, 08:03:10] [Govee] [Master Bedroom] [BLE] sending update {1: 1}.
[27/08/2021, 08:03:10] [Govee] [noble] scanning started.
[27/08/2021, 08:03:10] [Govee] [Master Bedroom] current state [on].
[27/08/2021, 08:03:14] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:03:14] [Govee] [noble] scanning started.
[27/08/2021, 08:03:15] [Govee] [Master Bedroom] [BLE] sending update {4: 158}.
[27/08/2021, 08:03:15] [Govee] [noble] scanning started.
[27/08/2021, 08:03:15] [Govee] [Master Bedroom] current brightness [62%].
[27/08/2021, 08:03:16] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:03:16] [Govee] [noble] scanning started.
[27/08/2021, 08:03:16] [Govee] [Master Bedroom] [BLE] sending update {4: 102}.
[27/08/2021, 08:03:16] [Govee] [noble] scanning started.
[27/08/2021, 08:03:17] [Govee] [Master Bedroom] current brightness [40%].
[27/08/2021, 08:03:17] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:03:17] [Govee] [noble] scanning started.
[27/08/2021, 08:03:18] [Govee] [Master Bedroom] [BLE] sending update {4: 99}.
[27/08/2021, 08:03:18] [Govee] [noble] scanning started.
[27/08/2021, 08:03:18] [Govee] [Master Bedroom] current brightness [39%].
[27/08/2021, 08:03:19] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:03:19] [Govee] [noble] scanning started.
[27/08/2021, 08:03:19] [Govee] [Master Bedroom] [BLE] sending update {4: 104}.
[27/08/2021, 08:03:19] [Govee] [noble] scanning started.
[27/08/2021, 08:03:20] [Govee] [Master Bedroom] current brightness [41%].
[27/08/2021, 08:03:22] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:03:22] [Govee] [noble] scanning started.
[27/08/2021, 08:03:23] [Govee] [Master Bedroom] [BLE] sending update {4: 196}.
[27/08/2021, 08:03:23] [Govee] [noble] scanning started.
[27/08/2021, 08:03:23] [Govee] [Master Bedroom] current brightness [77%].
[27/08/2021, 08:03:24] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:03:24] [Govee] [noble] scanning started.
[27/08/2021, 08:03:24] [Govee] [Master Bedroom] [BLE] sending update {4: 204}.
[27/08/2021, 08:03:24] [Govee] [noble] scanning started.
[27/08/2021, 08:03:25] [Govee] [Master Bedroom] current brightness [80%].
[27/08/2021, 08:03:28] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:03:28] [Govee] [noble] scanning started.
[27/08/2021, 08:03:28] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:03:28] [Govee] [noble] scanning started.
[27/08/2021, 08:03:29] [Govee] [Master Bedroom] [BLE] sending update {4: 0}.
[27/08/2021, 08:03:29] [Govee] [Master Bedroom] current state [off].
[27/08/2021, 08:03:29] [Govee] [noble] scanning started.
[27/08/2021, 08:03:30] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:03:30] [Govee] [noble] scanning started.
[27/08/2021, 08:03:30] [Govee] [Master Bedroom] [BLE] sending update {1: 1}.
[27/08/2021, 08:03:30] [Govee] [noble] scanning started.
[27/08/2021, 08:03:31] [Govee] [Master Bedroom] [BLE] sending update {4: 127}.
[27/08/2021, 08:03:31] [Govee] [Master Bedroom] current state [on].
[27/08/2021, 08:03:31] [Govee] [noble] scanning started.
[27/08/2021, 08:03:31] [Govee] [Master Bedroom] current brightness [50%].
[27/08/2021, 08:03:32] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 08:03:32] [Govee] [noble] scanning started.
[27/08/2021, 08:03:32] [Govee] [Master Bedroom] [BLE] sending update {4: 178}.
[27/08/2021, 08:03:32] [Govee] [noble] scanning started.
[27/08/2021, 08:03:33] [Govee] [Master Bedroom] current brightness [70%].
[27/08/2021, 08:03:43] [Govee] [Master Bedroom] has been reported [disconnected] via BLE.

**Comment by bwp91** [comment]
Do you have/use the Eve HomeKit app?

**Comment by dibsies** [comment]
Yes, I recently installed Eve to create scenes for custom area cleanup using a Deebot vacuum.

**Comment by bwp91** [comment]
Oh that sounds like my deebot plugin!

Can you revert back to the stable version of this plugin, and use the Eve app to change the brightness of the govee H6179 to 0% and then a certain % to see if this works?

**Comment by dibsies** [comment]
Indeed it is. You, my friend, are an absolute artist!

Reverted to stable, tested in Eve. Eve does not seem to reliably control the light. This goes for the off/on and moving of the brightness slider. Sometimes moving the slider jumps back to where it was after a few seconds with no change in light status. Sometimes the light is on when the setting shows off in the app. Weird. Maybe it's something to do with the Bluetooth dongle. I definitely don't mind having to go to 0% and back to whatever brightness. I just think it's ridiculously cool to even have these lights (and Deebot!) accessible in homekit. 

Obligatory logs:

[27/08/2021, 09:21:59] [Govee] [Master Bedroom] [BLE] sending update {1: 0}.
[27/08/2021, 09:21:59] [Govee] [noble] scanning started.
[27/08/2021, 09:21:59] [Govee] [Master Bedroom] current state [off].
[27/08/2021, 09:22:02] [Govee] [Master Bedroom] [BLE] sending update {1: 1}.
[27/08/2021, 09:22:02] [Govee] [noble] scanning started.
[27/08/2021, 09:22:02] [Deebot] [bd2e7f5d-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx] sent error [NoError: Robot is operational].
[27/08/2021, 09:22:02] [Govee] [Master Bedroom] current state [on].
[27/08/2021, 09:22:03] [Govee] [Master Bedroom] [BLE] sending update {4: 71}.
[27/08/2021, 09:22:03] [Govee] [noble] scanning started.
[27/08/2021, 09:22:03] [Govee] [Master Bedroom] current brightness [28%].
[27/08/2021, 09:22:04] [Govee] [Master Bedroom] [BLE] sending update {4: 48}.
[27/08/2021, 09:22:04] [Govee] [noble] scanning started.
[27/08/2021, 09:22:05] [Govee] [Master Bedroom] current brightness [19%].
[27/08/2021, 09:22:05] [Govee] [Master Bedroom] [BLE] sending update {4: 255}.
[27/08/2021, 09:22:05] [Govee] [noble] scanning started.
[27/08/2021, 09:22:06] [Govee] [Master Bedroom] current brightness [100%].
[27/08/2021, 09:22:08] [Govee] [Master Bedroom] [BLE] sending update {4: 255}.
[27/08/2021, 09:22:08] [Govee] [noble] scanning started.
[27/08/2021, 09:22:08] [Govee] [Master Bedroom] current brightness [100%].
[27/08/2021, 09:22:09] [Govee] [Master Bedroom] [BLE] sending update {4: 43}.
[27/08/2021, 09:22:09] [Govee] [noble] scanning started.
[27/08/2021, 09:22:09] [Govee] [Master Bedroom] current brightness [17%].
[27/08/2021, 09:22:10] [Govee] [Master Bedroom] [BLE] sending update {4: 0}.
[27/08/2021, 09:22:10] [Govee] [noble] scanning started.
[27/08/2021, 09:22:12] [Govee] [Master Bedroom] current state [off].
[27/08/2021, 09:22:14] [Govee] [Master Bedroom] [BLE] sending update {1: 1}.
[27/08/2021, 09:22:14] [Govee] [noble] scanning started.
[27/08/2021, 09:22:15] [Govee] [Master Bedroom] current state [on].
[27/08/2021, 09:22:15] [Govee] [Master Bedroom] [BLE] sending update {4: 53}.
[27/08/2021, 09:22:16] [Govee] [noble] scanning started.
[27/08/2021, 09:22:16] [Govee] [Master Bedroom] current brightness [21%].
[27/08/2021, 09:22:17] [Govee] [Master Bedroom] [BLE] sending update {4: 43}.
[27/08/2021, 09:22:17] [Govee] [noble] scanning started.
[27/08/2021, 09:22:17] [Deebot] [bd2e7f5d-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx]  sent error [Request Timeout].
[27/08/2021, 09:22:17] [Govee] [Master Bedroom] current brightness [17%].
[27/08/2021, 09:22:18] [Govee] [Master Bedroom] [BLE] sending update {4: 165}.
[27/08/2021, 09:22:18] [Govee] [noble] scanning started.
[27/08/2021, 09:22:18] [Govee] [Master Bedroom] current brightness [65%].
[27/08/2021, 09:22:21] [Govee] [Master Bedroom] [BLE] sending update {4: 165}.
[27/08/2021, 09:22:21] [Govee] [noble] scanning started.
[27/08/2021, 09:22:22] [Govee] [Master Bedroom] current brightness [65%].
[27/08/2021, 09:22:22] [Govee] [Master Bedroom] [BLE] sending update {4: 79}.
[27/08/2021, 09:22:22] [Govee] [noble] scanning started.
[27/08/2021, 09:22:23] [Govee] [Master Bedroom] current brightness [31%].
[27/08/2021, 09:22:33] [Govee] [Master Bedroom] has been reported [disconnected] via BLE.
[27/08/2021, 09:23:59] [myQ] myQ API: Successfully connected to the myQ API.
[27/08/2021, 09:24:03] [Deebot] [bd2e7f5d-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx] sent error [NoError: Robot is operational].

**Comment by bwp91** [comment]
The thing is, I don't know whether it's something particular with this Govee model, or something particular to do with your system/bluetooth dongle.

I notice there is another homebridge plugin for your exact model:
https://github.com/REBELinBLUE/homebridge-govee-h6179

I looked at the code and it uses the same commands to the device.

I don't really know what else to suggest...!

**Comment by dibsies** [comment]
No worries, I appreciate all of your help, and your work in general! 👍
