### ISSUE TITLE
H613D not changing colour via BLE

### ISSUE THREAD

**Issue by jitsadar7** [bwp91/homebridge-govee#172]
### What issue do you have? Please be as thorough and explicit as possible.

Had a warning message about Disabling HTTP client as Your account is abnormal, please contact customer service.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
* I think Homebridge CLI

* Which version of Homebridge/HOOBS do you have?
*Homebridge v1.3.9

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

* Running on homebridge with windows 10 
* NPM 8.1.2
*Node v16.13.1 
 

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

v4.22.0

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H613D

### Please paste any relevant logs below.

```
2021-12-31, 9:32:34 p.m.] [Govee] Disabling HTTP client as Your account is abnormal, please contact customer service. at connectionHTTP.login (C:\Users\Jitsadar\AppData\Roaming\npm\node_modules\homebridge-govee\lib\connection\http.js:58:15).
[2021-12-31, 9:32:34 p.m.] [Govee] Disabling BLE client as Cannot find module '@abandonware/bluetooth-hci-socket'
Require stack:
- C:\Users\Jitsadar\AppData\Roaming\npm\node_modules\homebridge-govee\lib\index.js
- C:\Users\Jitsadar\AppData\Roaming\npm\node_modules\homebridge\lib\plugin.js
- C:\Users\Jitsadar\AppData\Roaming\npm\node_modules\homebridge\lib\pluginManager.js
- C:\Users\Jitsadar\AppData\Roaming\npm\node_modules\homebridge\lib\server.js
- C:\Users\Jitsadar\AppData\Roaming\npm\node_modules\homebridge\lib\cli.js
- C:\Users\Jitsadar\AppData\Roaming\npm\node_modules\homebridge\bin\homebridgeRequire stack:.
```

**Comment by bwp91** [comment]
Hi @jitsadar7 

This message is a response from the Govee server, it’s one that I have never seen before,

```
Your account is abnormal, please contact customer service
```

You will need to contact customer service of Govee.

Potential other option is to create a new Govee account, add your existing devices and use this account with this plugin

**Comment by jitsadar7** [comment]
Hello, seems like i restart way too much making govee account restricted, i got a email by saying,
The system detects that your account is logged in too many times in a row. To ensure the account safety, it will be restricted from being logging in again for 24 hours, so im just gonna wait 24 hours.

**Comment by jitsadar7** [comment]
Update : i have it working now, i cant change colors, is this supposed to be like that?

**Comment by bwp91** [comment]
Are you able to turn on and off? and change brightness?

**Comment by jitsadar7** [comment]
I can turn on and off and change brightness but not change colors

**Comment by bwp91** [comment]
Are you able to change to a colour temperature from the home app?

**Comment by jitsadar7** [comment]
Nope.

**Comment by bwp91** [comment]
Can you show me the plugin startup logs from a restart?

Also which model do you own?

Do you have your govee API key in the plugin settings?

**Comment by jitsadar7** [comment]
H613D is the model of the light, This is my logs after restarting
`[2022-01-03, 3:03:27 p.m.] [Govee] Login successful.
[2022-01-03, 3:03:28 p.m.] [Govee] Bluetooth hardware and packages found successfully.
[2022-01-03, 3:03:28 p.m.] [Govee] [H613D_D89C] initialising with options {"adaptiveLightingShift":5,"bluetooth":"enabled","brightnessStep":1,"logging":"standard"}.
[2022-01-03, 3:03:28 p.m.] [Govee] [H613D_D89C] initialised with id [dont know if i need to show or not ].
[2022-01-03, 3:03:28 p.m.] [Govee] [noble] stateChange: poweredOff.
[2022-01-03, 3:03:28 p.m.] [Govee] [noble] stateChange: poweredOn.`
And i have a govee API in the plugin settings, I didn't know there is a update so im gonna update the plugin
I will let you know if it works

**Comment by jitsadar7** [comment]
The update failed, this is what is saying 
`npm ERR! code EBUSY
npm ERR! syscall rename
npm ERR! path C:\Users\Jitsadar\AppData\Roaming\npm\node_modules\homebridge-govee\lib\c
onnection
npm ERR! dest C:\Users\Jitsadar\AppData\Roaming\npm\node_modules\.homebridge-govee-6VJP
in2u\lib\connection
npm ERR! errno -4082
npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\Jitsadar\AppData\Roaming\npm\
node_modules\homebridge-govee\lib\connection' -> 'C:\Users\Jitsadar\AppData\Roaming\npm
\node_modules\.homebridge-govee-6VJPin2u\lib\connection'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\WINDOWS\system32\config\systemprofile\AppData\Local\npm-cache\_logs\202
2-01-03T20_10_58_474Z-debug.log

Command failed. Please review log for details.
`
What am i doing wrong?

**Comment by jitsadar7** [comment]
The update failed, This what i receive 
```npm ERR! code EBUSY
npm ERR! syscall rename
npm ERR! path C:\Users\Jitsadar\AppData\Roaming\npm\node_modules\homebridge-govee\lib\c
onnection
npm ERR! dest C:\Users\Jitsadar\AppData\Roaming\npm\node_modules\.homebridge-govee-6VJP
in2u\lib\connection
npm ERR! errno -4082
npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\Jitsadar\AppData\Roaming\npm\
node_modules\homebridge-govee\lib\connection' -> 'C:\Users\Jitsadar\AppData\Roaming\npm
\node_modules\.homebridge-govee-6VJPin2u\lib\connection'

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\WINDOWS\system32\config\systemprofile\AppData\Local\npm-cache\_logs\202
2-01-03T20_10_58_474Z-debug.log

Command failed. Please review log for details.
```
is this normal?

**Comment by jitsadar7** [comment]
Can i screenshare in discord so its easy?

**Comment by jitsadar7** [comment]
I also forgot to tell you  that my led strips are bluetooth, i think it can pretty do something with changing something

**Comment by bwp91** [comment]
> The update failed, This what i receive

Did you manage to fix this? This is an error with the installer of the plugin (`npm`) rather than the plugin itself.

This could be due to a number of reasons, it may be worth stopping Homebridge then trying to update the plugin via the terminal on windows. Or looking here for some other possible solutions:
https://stackoverflow.com/questions/55212864/error-ebusy-resource-busy-or-locked-rmdir

**Comment by jitsadar7** [comment]
i had manage to fix this yesterday by uninstalling node.js and all, and then install it back now i dont have any error, but I can only turn on and off and change brightness

**Comment by bwp91** [comment]
Can you turn on debug logging from the plugin settings, restart, try to change the colour of the device from the Home app, and show me the logs that appear?
Also make sure the device isn't connected to your phone when you try to control it.

**Comment by jitsadar7** [comment]
I double checked my phone that the bluetooth isnt on, then i got a error message that it was missing the package @abandonware/bluetooth-hci-socket, so i installed in this location `C:\Users\Jitsadar\AppData\Roaming\npm\node_modules\homebridge-govee\lib\connection`
and then when i tried changing the colour and colour temperature
doesnt work and somehow it kept disconnecting so thats new so this is my logs

```
[2022-01-08, 12:03:43 p.m.] [Govee] Login successful.
[2022-01-08, 12:03:44 p.m.] [Govee] Bluetooth hardware and packages found successfully.
[2022-01-08, 12:03:44 p.m.] [Govee] [H613D_D89C] initialising with options {"adaptiveLightingShift":0,"bluetooth":"enabled","brightnessStep":1,"logging":"debug"}.
[2022-01-08, 12:03:44 p.m.] [Govee] [H613D_D89C] initialised with id [not showing it].
[2022-01-08, 12:03:44 p.m.] [Govee] [noble] stateChange: poweredOff.
[2022-01-08, 12:03:44 p.m.] [Govee] [noble] stateChange: poweredOn.
[2022-01-08, 12:03:46 p.m.] [Govee] ✓ Setup complete. Want to see this plugin in your own language? Let me know!
[2022-01-08, 12:03:50 p.m.] [Govee] [noble] scanning started.
[2022-01-08, 12:03:51 p.m.] [Govee] [noble] found device [not showing it] [GBK_H613D_D89C].
[2022-01-08, 12:03:51 p.m.] [Govee] [noble] scanning stopped.
[2022-01-08, 12:03:51 p.m.] [Govee] [H613D_D89C] has been reported [discoverable] via BLE.
[2022-01-08, 12:03:51 p.m.] [Govee] [H613D_D89C] has been reported [connected] via BLE.
[2022-01-08, 12:03:51 p.m.] [Govee] [H613D_D89C] [BLE] sending update {1: 1}.
[2022-01-08, 12:03:51 p.m.] [Govee] [H613D_D89C] current state [on].
[2022-01-08, 12:03:55 p.m.] [Govee] [noble] scanning started.
[2022-01-08, 12:03:55 p.m.] [Govee] [H613D_D89C] [BLE] sending update {5: [2,184,255,84]}.
[2022-01-08, 12:03:55 p.m.] [Govee] [H613D_D89C] current colour [rgb 184 255 84].
[2022-01-08, 12:03:56 p.m.] [Govee] [noble] scanning started.
[2022-01-08, 12:03:56 p.m.] [Govee] [H613D_D89C] [BLE] sending update {5: [2,161,255,38]}.
[2022-01-08, 12:03:56 p.m.] [Govee] [H613D_D89C] current colour [rgb 161 255 38].
[2022-01-08, 12:03:57 p.m.] [Govee] [noble] scanning started.
[2022-01-08, 12:03:57 p.m.] [Govee] [H613D_D89C] [BLE] sending update {5: [2,255,189,111]}.
[2022-01-08, 12:03:57 p.m.] [Govee] [H613D_D89C] current colour [3100K / 319M].
[2022-01-08, 12:04:02 p.m.] [Govee] [H613D_D89C] could not be updated as Cannot read properties of undefined (reading '0') at deviceLightColour.internalCTUpdate (C:\Users\Jitsadar\AppData\Roaming\npm\node_modules\homebridge-govee\lib\device\light-colour-bt.js:382:24).
[2022-01-08, 12:04:04 p.m.] [Govee] [noble] scanning started.
[2022-01-08, 12:04:04 p.m.] [Govee] [H613D_D89C] [BLE] sending update {5: [2,255,245,240]}.
[2022-01-08, 12:04:04 p.m.] [Govee] [H613D_D89C] current colour [6100K / 163M].
[2022-01-08, 12:04:04 p.m.] [Govee] [noble] scanning started.
[2022-01-08, 12:04:04 p.m.] [Govee] [H613D_D89C] [BLE] sending update {5: [2,252,247,255]}.
[2022-01-08, 12:04:04 p.m.] [Govee] [H613D_D89C] current colour [6700K / 149M].
[2022-01-08, 12:04:05 p.m.] [Govee] [noble] scanning started.
[2022-01-08, 12:04:05 p.m.] [Govee] [H613D_D89C] [BLE] sending update {5: [2,245,243,255]}.
[2022-01-08, 12:04:05 p.m.] [Govee] [H613D_D89C] current colour [7000K / 143M].
[2022-01-08, 12:04:17 p.m.] [Govee] [H613D_D89C] has been reported [disconnected] via BLE.
````

**Comment by jitsadar7** [comment]
but brightness and turning on and off works

**Comment by bwp91** [comment]
It _may_ be that the device needs a different set of commands compared to most models for colour.

I can help you if you want, it's quite a long winded process and needs an iPhone and a Mac.

If you're happy to give it a go it's probably easier to talk on Discord!

https://discord.gg/cMGhNtZ3tW

**Comment by jitsadar7** [comment]
sorry i dont have mac, only windows 10 and a iphone but i would need help
on it

**Comment by jitsadar7** [comment]
and im on discord server butter#1431, u can message me if ur available

**Comment by CadLiara** [comment]
I am having this same issue, albeit with numerous devices that are wifi and not bluetooth. I have already tried reflashing the memory card and starting my HOOBS install from scratch and updating HOOBS followed by a clean plugin install. Same issue. Same errors in logs as this post.

**Comment by wja731** [comment]
Hello, I'm having this same error. I have an H6127. I can turn the strip on/off but I cannot change the color. When trying to change color it gives this error in the logs: Cloud] could not be updated as Cannot read properties of undefined (reading 'includes') at GoveePlatform.sendDeviceUpdate (/usr/local/lib/node_modules/homebridge-govee/lib/index.js:1105:49).
