### ISSUE TITLE
Govee H6116 RGBIC Light Strip (Bluetooth Device)

### ISSUE THREAD

**Issue by Piotronic** [bwp91/homebridge-govee#220]
I am starting my Smart home project, but unfortunately I have 3 Govee RGBIC light strips H6116 build into my walls, currenty the product is not been supported in the plugin.

* **Please explain your feature request in a one or two sentences.** I would like to atleast see my Govee H6116 RGBIC Light Strip (Bluetooth Device) in Homekit to switch on/off, integrate into automations / Szenes with colours

* **Is your feature request related to a problem? Please describe.** Product H6116 currently not in "supported Devices" list

* **Any particular Govee devices that this relates to?** H6116

* **Anything else?**
Very much appriciated in advance!

**Comment by Piotronic** [comment]
![grafik](https://user-images.githubusercontent.com/98609963/155947238-30a4015d-1e5b-4909-88b0-f7c76e8f35eb.png)

**Comment by Piotronic** [comment]
this is my JSON  Config:

    "lightDevices": [
        {
            "deviceId": "A8:F1:A4:C1:38:D5:23:02",
            "enableBT": true,
            "customAddress": "ihoment_H6116_2302",
            "adaptiveLightingShift": -1,
            "overrideLogging": "debug"

**Comment by bwp91** [comment]
Hi @Piotronic 

Please update to the beta version of the plugin, 4.29.1-beta.0, this device should then be added to homebridge.

In your config, the `customAddress` option for the light needs to look like a mac address ie in some form of `a5:1c:38:ab:cd:a1`

**Comment by Piotronic** [comment]
@bwp91 
Hello, I updated to the Beta and found the correct bluetooth adr. and updated JSON:

            "deviceId": "A8:F1:A4:C1:38:D5:23:02",
            "enableBT": true,
            "customAddress": "a4:c1:38:d5:23:02",
            "adaptiveLightingShift": -1,
            "overrideLogging": "debug"
            
            
            
Switch apears in Homekit as "Off" wenn i try to switch on, I get "no response"

![grafik](https://user-images.githubusercontent.com/98609963/156034476-2f7eb745-9a34-469a-9b3e-3470e61e2f1a.png)

![grafik](https://user-images.githubusercontent.com/98609963/156034288-4eb79fac-a724-44fd-93d8-1dcc05e76c1c.png)


![grafik](https://user-images.githubusercontent.com/98609963/156034370-5f4a6567-307e-4aec-9e81-f3855b90c51f.png)

**Comment by Piotronic** [comment]
homebridge-govee v4.29.1-beta.2 

[11/03/2022, 14:22:00] [Govee] Bluetooth hardware and packages found successfully.
[11/03/2022, 14:22:00] [Govee] [H6116] initialising with options {"adaptiveLightingShift":-1,"bluetooth":"enabled","brightnessStep":1,"logging":"debug"}.
[11/03/2022, 14:22:00] [Govee] [H6116] initialised with id [A8:F1:A4:C1:38:D5:23:02] [H6116].
[11/03/2022, 14:22:00] [Govee] [noble] stateChange: poweredOn.

[11/03/2022, 14:23:22] [Govee] [H6116] not sending AWS update as not available or enabled.
[11/03/2022, 14:23:22] [Govee] [noble] scanning started.
[11/03/2022, 14:23:22] [Govee] [H6116] not sending AWS update as not available or enabled.
[11/03/2022, 14:23:22] [Govee] [noble] found device [33:6e:f6:b3:72:ff] [undefined].
[11/03/2022, 14:23:22] [Govee] [noble] scanning started.
[11/03/2022, 14:23:23] [Govee] [noble] found device [c7:31:30:30:6a:7f] [Govee_H6052_6A7F].
[11/03/2022, 14:23:23] [Govee] [noble] found device [a4:c1:38:d5:23:02] [ihoment_H6116_2302].
[11/03/2022, 14:23:23] [Govee] [noble] scanning stopped.
[11/03/2022, 14:23:23] [Govee] [H6116] has been reported [discoverable] via BLE.
noble: unknown peripheral a4c138d52302 connected!
[11/03/2022, 14:23:23] [Govee] [noble] scanning started.
[11/03/2022, 14:23:23] [Govee] [H6116] has been reported [connected] via BLE.
noble: unknown peripheral a4c138d52302 disconnected!
[11/03/2022, 14:23:23] [Govee] [H6116] has been reported [disconnected] via BLE.
[11/03/2022, 14:23:25] [Govee] [noble] scanning started.
[11/03/2022, 14:23:25] [Govee] [noble] found device [c7:31:30:30:6a:7f] [Govee_H6052_6A7F].
[11/03/2022, 14:23:25] [Govee] [noble] found device [a4:c1:38:d5:23:02] [ihoment_H6116_2302].
[11/03/2022, 14:23:25] [Govee] [noble] scanning stopped.
[11/03/2022, 14:23:25] [Govee] [H6116] has been reported [discoverable] via BLE.
noble: unknown peripheral a4c138d52302 connected!
[11/03/2022, 14:23:26] [Govee] [noble] scanning started.
[11/03/2022, 14:23:26] [Govee] [H6116] has been reported [connected] via BLE.
[11/03/2022, 14:23:27] [Govee] [H6116] has been reported [disconnected] via BLE.
noble: unknown peripheral a4c138d52302 disconnected!
[11/03/2022, 14:23:27] [Govee] [noble] scanning started.
[11/03/2022, 14:23:27] [Govee] [noble] found device [c7:31:30:30:6a:7f] [Govee_H6052_6A7F].

[11/03/2022, 14:23:28] [Govee] [noble] scanning started.
[11/03/2022, 14:23:28] [Govee] [noble] found device [70:72:45:ae:dd:bd] [undefined].
[11/03/2022, 14:23:28] [Govee] [noble] found device [a4:c1:38:d5:23:02] [ihoment_H6116_2302].
[11/03/2022, 14:23:28] [Govee] [noble] scanning stopped.
[11/03/2022, 14:23:28] [Govee] [H6116] has been reported [discoverable] via BLE.
noble: unknown peripheral a4c138d52302 connected!
[11/03/2022, 14:23:28] [Govee] [noble] scanning started.
[11/03/2022, 14:23:28] [Govee] [H6116] has been reported [connected] via BLE.
[11/03/2022, 14:23:28] [Govee] [H6116] has been reported [disconnected] via BLE.
noble: unknown peripheral a4c138d52302 disconnected!
[11/03/2022, 14:23:30] [Govee] [H6116] could not be updated as BLE took too long at BluetoothLED.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:171:15).
[11/03/2022, 14:23:30] [Govee] [H6116] could not be updated as BLE took too long at BluetoothLED.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:171:15).

**Comment by Piotronic** [comment]
I am still having the issue. Its not possible to control H6116

**Comment by bwp91** [comment]
Hi @Piotronic 

Which platform are you running Homebridge on? Raspberry pi?

**Comment by Piotronic** [comment]
> 

Yes, Raspberry Pi 4 Model B

**Comment by bwp91** [comment]
Can you make sure all the pi software is up to date using `sudo apt update` then `sudo apt full-upgrade`?

**Comment by Piotronic** [comment]
> Can you make sure all the pi software is up to date using `sudo apt update` then `sudo apt full-upgrade`?

Done, but still not working:
[16/04/2022, 21:15:03] [Govee] [H6116] could not be updated as BLE took too long at BluetoothLED.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:171:15).
[16/04/2022, 21:15:03] [Govee] [H6116] could not be updated as BLE took too long at BluetoothLED.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:171:15).
[16/04/2022, 21:15:06] [Govee] [noble] found device [a4:c1:38:d5:23:02] [ihoment_H6116_2302].
[16/04/2022, 21:15:06] [Govee] [noble] scanning stopped.
[16/04/2022, 21:15:06] [Govee] [H6116] has been reported [discoverable] via BLE.
[16/04/2022, 21:15:06] [Govee] [noble] Peripheral already connected at Peripheral.connect (/usr/local/lib/node_modules/homebridge-govee/node_modules/@abandonware/noble/lib/peripheral.js:47:26).
[16/04/2022, 21:15:06] [Govee] [H6116] has been reported [disconnected] via BLE.
noble: unknown peripheral a4c138d52302 disconnected!

**Comment by Skyminer999** [comment]
> > Can you make sure all the pi software is up to date using `sudo apt update` then `sudo apt full-upgrade`?
> 
> Done, but still not working: [16/04/2022, 21:15:03] [Govee] [H6116] could not be updated as BLE took too long at BluetoothLED.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:171:15). [16/04/2022, 21:15:03] [Govee] [H6116] could not be updated as BLE took too long at BluetoothLED.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:171:15). [16/04/2022, 21:15:06] [Govee] [noble] found device [a4:c1:38:d5:23:02] [ihoment_H6116_2302]. [16/04/2022, 21:15:06] [Govee] [noble] scanning stopped. [16/04/2022, 21:15:06] [Govee] [H6116] has been reported [discoverable] via BLE. [16/04/2022, 21:15:06] [Govee] [noble] Peripheral already connected at Peripheral.connect (/usr/local/lib/node_modules/homebridge-govee/node_modules/@abandonware/noble/lib/peripheral.js:47:26). [16/04/2022, 21:15:06] [Govee] [H6116] has been reported [disconnected] via BLE. noble: unknown peripheral a4c138d52302 disconnected!

Yes i have the exact same problem. I have everything up to date too

**Comment by bwp91** [comment]
Anyone having bluetooth issues can you try the newest beta 4.30.4-beta.2?

**Comment by Piotronic** [comment]
Many thanks for your effort, but unfortunately still not responding:

[24/04/2022, 16:57:43] [Govee] [noble] scanning started.
[24/04/2022, 16:57:43] [Govee] [noble] found device [a4:c1:38:d5:23:02] [ihoment_H6116_2302].
[24/04/2022, 16:57:43] [Govee] [noble] scanning stopped.
[24/04/2022, 16:57:43] [Govee] [H6116] has been reported [discoverable] via BLE.
[24/04/2022, 16:57:43] [Govee] [H6116] has been reported [connected] via BLE.
noble: unknown peripheral a4c138d52302 disconnected!
[24/04/2022, 16:57:43] [Govee] [H6116] has been reported [disconnected] via BLE.
[24/04/2022, 16:57:45] [Govee] [H6116] could not be updated as BLE took too long at BluetoothLED.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:171:15).
[24/04/2022, 16:57:45] [Govee] [H6116] could not be updated as BLE took too long at BluetoothLED.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:171:15).
[24/04/2022, 16:57:49] [Govee] [H6116] not sending AWS update as not available or enabled.
[24/04/2022, 16:57:49] [Govee] [noble] scanning started.
[24/04/2022, 16:57:49] [Govee] [noble] found device [d5:0c:92:4f:da:e4] [undefined].
[24/04/2022, 16:57:49] [Govee] [H6116] not sending AWS update as not available or enabled.


[24/04/2022, 16:57:54] [Govee] [noble] found device [a4:c1:38:d5:23:02] [ihoment_H6116_2302].
[24/04/2022, 16:57:54] [Govee] [noble] scanning stopped.
[24/04/2022, 16:57:54] [Govee] [H6116] has been reported [discoverable] via BLE.
[24/04/2022, 16:57:54] [Govee] [noble] scanning started.

[24/04/2022, 16:57:55] [Govee] [noble] found device [a4:c1:38:d5:23:02] [ihoment_H6116_2302].
[24/04/2022, 16:57:55] [Govee] [noble] scanning stopped.
[24/04/2022, 16:57:55] [Govee] [H6116] has been reported [discoverable] via BLE.
[24/04/2022, 16:57:56] [Govee] [H6116] could not be updated as BLE took too long at BluetoothLED.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:171:15).

**Comment by Piotronic** [comment]
[10/05/2022, 22:27:03] [Govee] [H6116] not sending AWS update as not available or enabled.
[10/05/2022, 22:27:03] [Govee] [H6116] starting update with params [{"cmd":4,"data":255}].
[10/05/2022, 22:27:03] [Govee] [H6116] starting timer.
[10/05/2022, 22:27:03] [Govee] [H6116] starting scan.
[10/05/2022, 22:27:03] [Govee] [noble] scanning started.
[10/05/2022, 22:27:03] [Govee] [H6116] scanning started.
[10/05/2022, 22:27:03] [Govee] [H6116] starting loop.
[10/05/2022, 22:27:03] [Govee] [noble] found device [9c:8c:6e:4a:7b:a5] [undefined].
[10/05/2022, 22:27:03] [Govee] [H6116] not sending AWS update as not available or enabled.
[10/05/2022, 22:27:03] [Govee] [H6116] starting update with params [{"cmd":1,"data":1}].
[10/05/2022, 22:27:03] [Govee] [H6116] starting timer.
[10/05/2022, 22:27:03] [Govee] [H6116] starting scan.
[10/05/2022, 22:27:03] [Govee] [noble] scanning started.
[10/05/2022, 22:27:03] [Govee] [H6116] scanning started.
[10/05/2022, 22:27:03] [Govee] [H6116] starting loop.

[10/05/2022, 22:27:03] [Govee] [noble] found device [a4:c1:38:d5:23:02] [ihoment_H6116_2302].
[10/05/2022, 22:27:03] [Govee] [noble] scanning stopped.
[10/05/2022, 22:27:03] [Govee] [H6116] has been reported [discoverable] via BLE.
[10/05/2022, 22:27:03] [Govee] [H6116] attempting to connect.
noble: unknown peripheral a4c138d52302 connected!
[10/05/2022, 22:27:03] [Govee] [noble] scanning started.
[10/05/2022, 22:27:03] [Govee] [H6116] has been reported [connected] via BLE.
[10/05/2022, 22:27:03] [Govee] [H6116] finding device characteristics.
[10/05/2022, 22:27:03] [Govee] [H6116] has been reported [disconnected] via BLE [undefined].
noble: unknown peripheral a4c138d52302 disconnected!
[10/05/2022, 22:27:07] [Govee] [H6116] could not be updated as BLE took too long at BluetoothLED.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:188:15).
[10/05/2022, 22:27:07] [Govee] [H6116] could not be updated as BLE took too long at BluetoothLED.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/connection/ble.js:188:15).

**Comment by Piotronic** [comment]
v5.0.1

![grafik](https://user-images.githubusercontent.com/98609963/170856880-e6fd1385-0a55-4df9-83bd-a795a6d8df1e.png)

**Comment by bwp91** [comment]
Can you make sure your raspberry pi software and firmware is up to date with

`sudo apt update`

from the homebridge terminal?

**Comment by Piotronic** [comment]
Hello, eveything was up 2 date

![grafik](https://user-images.githubusercontent.com/98609963/170859755-99be944f-11c0-48b6-8852-6c0ffae7cc8f.png)

**Comment by bwp91** [comment]
Can you update to and try 5.1.0-beta.1?

**Comment by Piotronic** [comment]
updated to 5.1.0-beta.1

![grafik](https://user-images.githubusercontent.com/98609963/170877237-e4198710-7ce6-4568-954b-c867f24c3f64.png)

**Comment by bwp91** [comment]
Do you use any other plugins that use bluetooth?

**Comment by Piotronic** [comment]
[homebridge-switchbot-bluetooth](https://github.com/galzo/homebridge-switchbot-bluetooth)
and
[homebridge-soundtouch-platform](https://github.com/bbriatte/homebridge-soundtouch-platform)

I think these to use bluetooth and are working

**Comment by thecodegoddess** [comment]
I am seeing a similar issue.

__Homebridge Log__

```
[10/06/2022, 16:37:49] [Govee] [Glide Hexa] [AWS] connected event.
[10/06/2022, 16:37:49] [Govee] [Glide Hexa] skipping sync as device status not retrievable.
[10/06/2022, 16:37:50] [Govee] ✓ Setup complete. Join the plugin's Discord community! https://discord.gg/cMGhNtZ3tW
[10/06/2022, 16:37:58] [Govee] [Glide Hexa] has been reported [offline] via API, so update may or may not be successful.
[10/06/2022, 16:37:58] [Govee] [Glide Hexa] [AWS] sending update {"msg":{"cmd":"turn","cmdVersion":0,"data":{"val":1},"transaction":"v_1654904278964000","type":1}}.
[10/06/2022, 16:37:59] [Govee] [Glide Hexa] [AWS] message event [{"msg":{"cmd":"turn","cmdVersion":0,"data":{"val":1},"transaction":"v_1654904278964000","type":1}}].
[10/06/2022, 16:37:59] [Govee] [Glide Hexa] [AWS] receiving update [{"cmd":"turn","cmdVersion":0,"data":{"val":1},"transaction":"v_1654904278964000","type":1,"source":"AWS"}].
[10/06/2022, 16:37:59] [Govee] [Glide Hexa] current state [on].
[10/06/2022, 16:37:59] [Govee] [Glide Hexa] starting update with params [{"cmd":1,"data":1}].
[10/06/2022, 16:37:59] [Govee] [Glide Hexa] starting timer.
[10/06/2022, 16:37:59] [Govee] [Glide Hexa] starting scan.
[10/06/2022, 16:37:59] [Govee] [noble] scanning started.
[10/06/2022, 16:37:59] [Govee] [Glide Hexa] scanning started.
[10/06/2022, 16:37:59] [Govee] [Glide Hexa] starting loop.
[10/06/2022, 16:37:59] [Govee] [noble] found device [34:83:9e:f1:91:12] [undefined].
[10/06/2022, 16:37:59] [Govee] [noble] found device [f6:d4:56:0e:5a:3f] [undefined].
[10/06/2022, 16:37:59] [Govee] [noble] found device [e1:d1:75:d0:0b:90] [undefined].
[10/06/2022, 16:37:59] [Govee] [noble] found device [5b:24:d6:c1:d5:7c] [undefined].
[10/06/2022, 16:37:59] [Govee] [noble] found device [3d:33:63:d5:26:01] [undefined].
[10/06/2022, 16:37:59] [Govee] [noble] found device [c8:39:32:33:5f:67] [Govee_H6061_5F67].
[10/06/2022, 16:37:59] [Govee] [Glide Hexa] has been reported [discoverable] via BLE.
[10/06/2022, 16:37:59] [Govee] [Glide Hexa] attempting to connect.
[10/06/2022, 16:38:00] [Govee] [noble] scanning stopped.
[10/06/2022, 16:38:00] [Govee] [noble] scanning started.
[10/06/2022, 16:38:00] [Govee] [Glide Hexa] has been reported [connected] via BLE.
[10/06/2022, 16:38:00] [Govee] [Glide Hexa] finding device characteristics.
[10/06/2022, 16:38:03] [Govee] [Glide Hexa] could not find device [c8:39:32:33:5f:67].
[10/06/2022, 16:38:03] [Govee] [Glide Hexa] reverting to API as BLE took too long.
[10/06/2022, 16:38:03] [Govee] [Glide Hexa] [API] sending update {"name":"turn","value":"on"}.
[10/06/2022, 16:38:03] [Govee] [Glide Hexa] has been reported [disconnected] via BLE [undefined].
[10/06/2022, 16:38:03] [Govee] Skipping sync as client is busy sending updates.
[10/06/2022, 16:38:03] [Govee] [Glide Hexa] [AWS] message event [{"msg":{"transaction":"o_1654904283843","type":1,"cmd":"turn","data":{"val":1}}}].
[10/06/2022, 16:38:03] [Govee] [Glide Hexa] [AWS] receiving update [{"transaction":"o_1654904283843","type":1,"cmd":"turn","data":{"val":1},"source":"AWS"}].
[10/06/2022, 16:38:19] [Govee] [Glide Hexa] skipping sync as device status not retrievable.
[10/06/2022, 16:38:34] [Govee] [Glide Hexa] skipping sync as device status not retrievable.
[10/06/2022, 16:38:49] [Govee] [Glide Hexa] skipping sync as device status not retrievable.
```

__My Config__
```
{
  "name": "Govee",
  "username": "MY_USSERNAME",
  "password": "MY_PASSWORD",
  "apiKey": "MY_API_KEY",
  "debug": true,
  "disablePlugin": false,
  "refreshTime": 15,
  "controlInterval": 500,
  "lightDevices": [
      {
          "label": "Office Panels",
          "deviceId": "67:C8:C8:39:32:33:5F:67",
          "ignoreDevice": false,
          "disableAWS": false,
          "enableBT": true,
          "customAddress": "C8:39:32:33:5F:67",
          "brightnessStep": 10,
          "adaptiveLightingShift": 15,
          "overrideLogging": "default"
      }
  ],
  "platform": "Govee"
}
```

**Comment by anxjo** [comment]
Hello everyone, 
sorry for my terrible english. Following your advice I was able to make my H6181 LED strips work after a long time. They had the same problems listed in these posts. If you use two plugins that take advantage of bluetooth they conflict. I tried to merge the two plugins (Homebridge Govee and Homebridge plugin Govee) by clicking on bridge settings and then I deleted (Homebridge plugin Govee). The lights started working again. Objects that used the plugin I deleted also continue to work

**Comment by bwp91** [comment]
Hi @anxjo 

If you can install the beta version of the plugin, this will use bluetooth to scan for your temperature sensors just like the homebridge-plugin-govee did. I am merging the functionality of that plugin into this one. So you will no longer need to have both.

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.
