### ISSUE TITLE
Product not currently supported

### ISSUE THREAD

**Issue by thkvy** [bwp91/homebridge-govee#237]
### What issue do you have? Please be as thorough and explicit as possible.
I configured a Govee light strip (H6107) using the Govee Home app.
I then installed the homebridge-govee plugin and after restarting the service I have the following error in the logs :
[LED Strip] is not currently supported, do create a Github issue with the following info:
{"device":"40:48:0C:F2:92:47:2E:DE","deviceName":"LED Strip","model":"H6107","httpInfo":{"groupId":0,"device":"40:48:0C:F2:92:47:2E:DE","sku":"H6107","spec":"","versionHard":"1.00.01","versionSoft":"1.01.20","deviceName":"LED Strip","deviceExt":{"deviceSettings":"{\"bleName\":\"ihoment_H6107_D127\",\"ic\":0,\"sku\":\"H6107\",\"device\":\"40480cf292472ede\",\"deviceName\":\"LED Strip\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.01.20\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false}

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
I am using Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
I have Homebridge v1.4.0 (HAP v0.10.0)

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
I am running it on Microsoft Windows 10 Professionnel with Node.js version 16.14.2 and NPM version 8.5.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
I have the version v4.30.3 of the plugin and I didn't upgrade it as I just install it.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Govee RGB LED light strip H6107

### Please paste any relevant logs below.

```
[16/04/2022, 12:40:12] Homebridge v1.4.0 (HAP v0.10.0) (Homebridge 0B28) is running on port 51159.
[16/04/2022, 12:40:12] [Govee] Login successful.
[16/04/2022, 12:40:13] [Govee] Bluetooth hardware and packages found successfully.
[16/04/2022, 12:40:13] [Govee] [LED Strip] is not currently supported, do create a Github issue with the following info:
{"device":"40:48:0C:F2:92:47:2E:DE","deviceName":"LED Strip","model":"H6107","httpInfo":{"groupId":0,"device":"40:48:0C:F2:92:47:2E:DE","sku":"H6107","spec":"","versionHard":"1.00.01","versionSoft":"1.01.20","deviceName":"LED Strip","deviceExt":{"deviceSettings":"{\"bleName\":\"ihoment_H6107_D127\",\"ic\":0,\"sku\":\"H6107\",\"device\":\"40480cf292472ede\",\"deviceName\":\"LED Strip\",\"versionHard\":\"1.00.01\",\"versionSoft\":\"1.01.20\"}","lastDeviceData":"{\"online\":false}","extResources":"{\"skuUrl\":\"\",\"headOnImg\":\"\",\"headOffImg\":\"\",\"ext\":\"\",\"ic\":0}"},"goodsType":0},"isAPIDevice":false}
[16/04/2022, 12:40:13] [Govee] [noble] stateChange: poweredOff.
[16/04/2022, 12:40:15] [Govee] ✓ Setup complete. Thanks for using this plugin, I hope you find it helpful!
```

**Comment by bwp91** [comment]
Hi @tkvy4 

Can you update to the beta version of the plugin? This device should then show as supported!

**Comment by thkvy** [comment]
Hello @bwp91,

Thanks ! Updating to the beta version fixed the issue.
My device is now supported and I can see it added to Apple Home app.

However, I am facing another issue.
Please find the logs below :
```
[16/04/2022, 17:06:11] [Govee] Login successful.
[16/04/2022, 17:06:12] [Govee] Bluetooth hardware and packages found successfully.
[16/04/2022, 17:06:12] [Govee] [LED Strip] initialising with options {"adaptiveLightingShift":0,"bluetooth":"enabled","brightnessStep":1,"logging":"debug"}.
[16/04/2022, 17:06:12] [Govee] [LED Strip] initialised with id [40:48:0C:F2:92:47:2E:DE] [H6107].
[16/04/2022, 17:06:12] [Govee] [noble] stateChange: poweredOff.
[16/04/2022, 17:06:14] [Govee] ✓ Setup complete. Don't forget to ☆ this plugin on GitHub if you're finding it useful!
[16/04/2022, 17:11:02] [Govee] [LED Strip] not sending AWS update as not available or enabled.
[16/04/2022, 17:11:02] [Govee] [LED Strip] could not be updated as BLE adapter not in correct state [poweredOff] at BluetoothLED.updateDevice (C:\Users\Kevin\AppData\Roaming\npm\node_modules\homebridge-govee\lib\connection\ble.js:140:13).
[16/04/2022, 17:11:02] [Govee] [LED Strip] not sending AWS update as not available or enabled.
[16/04/2022, 17:11:02] [Govee] [LED Strip] could not be updated as BLE adapter not in correct state [poweredOff] at BluetoothLED.updateDevice (C:\Users\Kevin\AppData\Roaming\npm\node_modules\homebridge-govee\lib\connection\ble.js:140:13).
```

I understand that the state needs to be poweredOn but how do I change it ?

Thanks !

**Comment by bwp91** [comment]
The plugin using bluetooth hasn’t really been tested with windows (i don’t have access to one).

But there are instructions here for getting the bluetooth to work on windows, i’m not sure how simple/complicated it is:

https://github.com/abandonware/noble#windows
