### ISSUE TITLE
Cannot control H6104 with current version (1.1.0), worked in previous version

### ISSUE THREAD

**Issue by apexad** [bwp91/homebridge-govee#3]
**What issue do you have? Please be as thorough and explicit as possible.**

I have an H6104.  As the title says, the plugin report error like 400 or 'it is offline' with 1.0.3 but still turned on the light strip.  1.1.0 does nothing

**Details of your setup.**
Do you use Homebridge or HOOBS?

Homebridge 

Which version of Homebridge/HOOBS do you have?

version 1.2.3/NodeJS 12.18.4

Which version of this plugin (homebridge-ewelink) do you have?

1.1.0 currently installed, but as I said it is broken, 1.0.3 worked and I will revert to that as soon as I post this issue.

**Please paste any relevant logs below. It helps if you can turn `debug` and `debugReqRes` in the package settings for more thorough logging.**
> If you are posting an error then it is helpful for me to also see the previous few lines as this can show the cause of the error.

On homebridge boot up:
```bash
[9/28/2020, 19:56:44] [Govee] [Living Room TV Ambient] could not be initialised.
[9/28/2020, 19:56:44] [Govee] Request failed with status code 400
```
When I try to control it:

```bash
[9/28/2020, 19:57:15] [Govee] [getDevices()] HTTP Response:
{
  "devices": [
    {
      "device": "<REMOVED>",
      "model": "H6104",
      "deviceName": "Living Room TV Ambient",
      "controllable": true,
      "retrievable": false,
      "supportCmds": [
        "turn",
        "brightness",
        "color",
        "colorTem"
      ]
    }
  ]
}
[9/28/2020, 19:57:15] [Govee] [Living Room TV Ambient] could not be initialised.
[9/28/2020, 19:57:15] [Govee] Request failed with status code 400
```

**Edit:** Here is another log I see:

```bash
[9/28/2020, 19:57:50] [Govee] [Living Room TV Ambient] could not be updated and its status will be reverted soon. Error: 
Error: it is currently offline
    at goveeHTTP.updateDevice (/usr/local/lib/node_modules/homebridge-govee/lib/goveeHTTP.js:72:13)
    at Govee.internalOnOffUpdate (/usr/local/lib/node_modules/homebridge-govee/lib/govee.js:207:29)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-govee/lib/govee.js:146:46)
    at Characteristic.emit (events.js:315:20)
    at Characteristic.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:60:38)
    at Characteristic._this.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Characteristic.js:369:23)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:967:36
    at Array.forEach (<anonymous>:null:null)
    at Bridge.Accessory._this._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/Accessory.js:835:18)
    at HAPServer.emit (events.js:315:20)
    at HAPServer.EventEmitter.emit (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/EventEmitter.js:60:38)
    at HAPServer._this._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:731:23)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/dist/lib/HAPServer.js:240:39)
    at IncomingMessage.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Please note, I have an apiKey setup and in the plugin config.  I have the device setup in the Govee Home app, but no other home automation (except homebridge)

**Comment by apexad** [comment]
Fixed with 1.1.1
