### ISSUE TITLE
Water leak sensors not found/updated App works fine though

### ISSUE THREAD

**Issue by oilcan-productions** [bwp91/homebridge-govee#307]
### What issue do you have? Please be as thorough and explicit as possible.
I just added the H5040 gateway and water leak sensors to my Govee devices.
The sensors state is not loaded with the following message in the logs:
```[9/19/2022, 10:44:04 AM] [Govee] [Laundry] "{\"online\":true,\"gwonline\":true,\"lastTime\":1662138300000,\"read\":true}".
[9/19/2022, 10:44:04 AM] [Govee] [Waterheater] "{\"online\":true,\"gwonline\":true,\"lastTime\":1662138120000,\"read\":true}".
[9/19/2022, 10:44:04 AM] [Govee] [Dishwasher] "{\"online\":true,\"gwonline\":true,\"lastTime\":1662137580000,\"read\":true}".
[9/19/2022, 10:44:05 AM] [Govee] [Waterheater] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
[9/19/2022, 10:44:05 AM] [Govee] [Laundry] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
[9/19/2022, 10:44:05 AM] [Govee] [Dishwasher] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
[9/19/2022, 10:44:19 AM] [Govee] [Laundry] "{\"online\":true,\"gwonline\":true,\"lastTime\":1662138300000,\"read\":true}".
[9/19/2022, 10:44:19 AM] [Govee] [Waterheater] "{\"online\":true,\"gwonline\":true,\"lastTime\":1662138120000,\"read\":true}".
[9/19/2022, 10:44:19 AM] [Govee] [Dishwasher] "{\"online\":true,\"gwonline\":true,\"lastTime\":1662137580000,\"read\":true}".
[9/19/2022, 10:44:20 AM] [Govee] [Dishwasher] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
[9/19/2022, 10:44:20 AM] [Govee] [Laundry] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
[9/19/2022, 10:44:20 AM] [Govee] [Waterheater] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).```
```
When I check the sensor in the Govee app it is showing up as expected though.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
1) Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
1.5.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi 400

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
I tried the latest stable and the 6.0 beta 3 with the same result

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
The gateway is a Govee H5040 the sensors are H5054 
GW FW version is 1.05.06 
GW HW Version: 1.00.04

### Please paste any relevant logs below.

Plugin Config:
```
        {
            "name": "Govee",
            "username": "mike@k*******.***",
            "password": "*********************",
            "apiKey": "276*****-****-****-****-**********ee",
            "debug": true,
            "platform": "Govee"
        },
```
log
```
[9/19/2022, 10:42:57 AM] ---
[9/19/2022, 10:42:58 AM] Loaded plugin: homebridge-govee@6.0.0-beta.3
[9/19/2022, 10:42:58 AM] Registering platform 'homebridge-govee.Govee'
[9/19/2022, 10:42:58 AM] ---
[9/19/2022, 10:43:00 AM] [Govee] Initializing Govee platform...
[9/19/2022, 10:43:00 AM] [Govee] Initialising plugin v6.0.0-beta.3 | System linux | Node v16.17.0 | HB v1.5.0 | HAPNodeJS v0.10.2.
[9/19/2022, 10:43:03 AM] [Govee] LAN client enabled.
[9/19/2022, 10:43:03 AM] [Govee] Login successful.
[9/19/2022, 10:43:04 AM] [Govee] HTTP/AWS clients enabled as Govee username and password provided.
[9/19/2022, 10:43:04 AM] [Govee] API client enabled as Govee API key provided.
[9/19/2022, 10:43:04 AM] [Govee] Disabling BLE client as no enabled devices configured.
[9/19/2022, 10:43:04 AM] [Govee] [Laundry] initialising with options {"logging":"debug"}.
[9/19/2022, 10:43:04 AM] [Govee] [Laundry] initialised with id [BEFF4DFA632B00C207] [H5054].
[9/19/2022, 10:43:04 AM] [Govee] [Waterheater] initialising with options {"logging":"debug"}.
[9/19/2022, 10:43:04 AM] [Govee] [Waterheater] initialised with id [BEFF4DFA632B00CA0F] [H5054].
[9/19/2022, 10:43:04 AM] [Govee] [Dishwasher] initialising with options {"logging":"debug"}.
[9/19/2022, 10:43:04 AM] [Govee] [Dishwasher] initialised with id [BEFF4DFA632B00C7CD] [H5054].
[9/19/2022, 10:44:04 AM] [Govee] [Laundry] "{\"online\":true,\"gwonline\":true,\"lastTime\":1662138300000,\"read\":true}".
[9/19/2022, 10:44:04 AM] [Govee] [Waterheater] "{\"online\":true,\"gwonline\":true,\"lastTime\":1662138120000,\"read\":true}".
[9/19/2022, 10:44:04 AM] [Govee] [Dishwasher] "{\"online\":true,\"gwonline\":true,\"lastTime\":1662137580000,\"read\":true}".
[9/19/2022, 10:44:05 AM] [Govee] [Waterheater] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
[9/19/2022, 10:44:05 AM] [Govee] [Laundry] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
[9/19/2022, 10:44:05 AM] [Govee] [Dishwasher] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
[9/19/2022, 10:44:19 AM] [Govee] [Laundry] "{\"online\":true,\"gwonline\":true,\"lastTime\":1662138300000,\"read\":true}".
[9/19/2022, 10:44:19 AM] [Govee] [Waterheater] "{\"online\":true,\"gwonline\":true,\"lastTime\":1662138120000,\"read\":true}".
[9/19/2022, 10:44:19 AM] [Govee] [Dishwasher] "{\"online\":true,\"gwonline\":true,\"lastTime\":1662137580000,\"read\":true}".
[9/19/2022, 10:44:20 AM] [Govee] [Dishwasher] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
[9/19/2022, 10:44:20 AM] [Govee] [Laundry] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
[9/19/2022, 10:44:20 AM] [Govee] [Waterheater] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
```

**Comment by nevetssf** [comment]
Same issue here. Maybe something's up with the Govee server?

Running Hoobs 4.2.8, Govee 6.0.0-beta 3

```
{
    "platform": "Govee",
    "name": "Govee",
    "username": "******@*****.******",
    "password": "*******",
    "thermoDevices": [
        {
            "deviceId": "***********",
            "ignoreDevice": true
        }
    ],
    "apiKey": "****************"
}
```

```
9/19/2022, 12:09:58 PMGovee BridgeGoveeWARNING[Boulder Sprinkler] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/hoobs/goveebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
9/19/2022, 12:09:58 PMGovee BridgeGoveeWARNING[Boulder East Wall] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/hoobs/goveebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
9/19/2022, 12:09:58 PMGovee BridgeGoveeWARNING[Boulder Sump Pump] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/hoobs/goveebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
9/19/2022, 12:09:58 PMGovee BridgeGoveeWARNING[Boulder Trap Door] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/hoobs/goveebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
9/19/2022, 12:10:13 PMGovee BridgeGoveeWARNING[Boulder East Wall] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/hoobs/goveebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
9/19/2022, 12:10:13 PMGovee BridgeGoveeWARNING[Boulder Sprinkler] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/hoobs/goveebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
9/19/2022, 12:10:13 PMGovee BridgeGoveeWARNING[Boulder Trap Door] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/hoobs/goveebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
9/19/2022, 12:10:13 PMGovee BridgeGoveeWARNING[Boulder Sump Pump] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/hoobs/goveebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
```

**Comment by tpellegrini** [comment]
Seeing a similar issue here. This is a new install of this plugin. I have 4 devices. All four are listed under "My Devices" but one of them has a slightly different dataset below, which seems to correspond to this issue:

>>
[21/09/2022, 12:26:09] [Govee] [H5054-SumpPump] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).
<<

The device corresponding to the alert is showing as having no "Cloud Status" attribute which all the working devices show: 

![image](https://user-images.githubusercontent.com/26607300/191841339-f3b50349-ec75-49c3-9ae8-eb516c70ca78.png)

I'm not sure how or where this status is determined as this device was tested and showed an alert in the Govee app on my phone.

Environment:
- Raspberry Pi 4
- Homebridge 1.5.0
- homebridge-govee v5.2.0

The gateway is a Govee H5040 the sensors are H5054.

**Comment by clunkclunk** [comment]
I am also seeing the same issue.

Rpi4, Homebridge v1.5.0, homebridge-govee v5.2.0, Govee H5040_DD31 gateway, sensors are H5054.

**Comment by RickyEnduro** [comment]
Same issue for me. At least I'm not the only one. 9/30/2022, 2:39:33 PMGovee BridgeGoveeWARNING[Water Softener (Aqua)] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/hoobs/goveebridge/node_modules/homebridge-govee/lib/connection/http.js:144:13).

**Comment by bwp91** [comment]
Hi all,

if there is someone who would be happy to give me access to a govee account with the water sensors added, and also have some time to spend splashing some water on it a couple of times, then I can definitely look into this. 

It’s on my long list of things!

Let me know and perhaps we could message on discord

thanks!

**Comment by oilcan-productions** [comment]
@bwp91 Hi Ben, sure DM me on discord.

**Comment by oilcan-productions** [comment]
This is now resolved in the latest Beta. Thanks @bwp91  for the quick resolution.

**Comment by dlollman** [comment]
This is no longer working again in latest beta.

**Comment by nevetssf** [comment]
Still unresolved for me as well, running Govee Bridge 6.0.5 beta 11.

10/9/2022, 9:07:52 AMGovee BridgeGoveeWARNING[Boulder Sump Pump] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/hoobs/goveebridge/node_modules/homebridge-govee/lib/connection/http.js:147:13).

**Comment by bwp91** [comment]
@dlollman @nevetssf 

any chance I could log into one of your govee accounts from my homebridge?

if so, we can dm on discord at https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
closing this, i believe this is fixed in beta
