### ISSUE TITLE
Accessories not responding

### ISSUE THREAD

**Issue by rjkelly1894** [bwp91/homebridge-govee#308]
### What issue do you have? Please be as thorough and explicit as possible.
All Devices from my Gogvee Library are not responding.  They all work in the Homebridge UI web interface, but none work in the home app.  I have set up all but each has same error message.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebrdige UI on Windows 10 Pro Server

* Which version of Homebridge/HOOBS do you have?
v1.5.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Windows 10

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
v5.2.0 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```9/21/2022, 5:58:59 PM] Homebridge v1.5.0 (HAP v0.10.4) (Homebridge EC21) is running on port 51452.
[9/21/2022, 5:58:59 PM] [Govee] HTTP/AWS clients enabled as Govee username and password provided.
[9/21/2022, 5:58:59 PM] [Govee] API client enabled as Govee API key provided.
[9/21/2022, 5:58:59 PM] [Govee] Disabling BLE client as Cannot find package '@abandonware/bluetooth-hci-socket' imported from C:\Users\rj_ke\AppData\Roaming\npm\node_modules\homebridge-govee\lib\platform.js at new NodeError (node:internal/errors:387:5).
[9/21/2022, 5:58:59 PM] [Govee] [RJs Desk Lightstrip] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lightstrip] if you notice any flickering when changing the brightness/colour, let me know on Discord/Github with model number [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lightstrip] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lightstrip] initialised with id [BF:50:D4:AD:FC:0C:D9:CA] [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [Joe’s Office Lamp] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [Joe’s Office Lamp] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [Joe’s Office Lamp] initialised with id [21:B0:9C:04:A0:A6:79:AF] [H6008].
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lamp] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lamp] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lamp] initialised with id [04:2A:9C:04:A0:A4:61:2F] [H6008].
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lamp 2] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lamp 2] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lamp 2] initialised with id [C8:C5:9C:04:A0:A6:79:E3] [H6008].
[9/21/2022, 5:59:00 PM] [Govee] [Office TV] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [Office TV] if you notice any flickering when changing the brightness/colour, let me know on Discord/Github with model number [H6054].
[9/21/2022, 5:59:00 PM] [Govee] [Office TV] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [Office TV] initialised with id [B5:E4:C5:31:30:30:3C:3E] [H6054].
[9/21/2022, 5:59:00 PM] [Govee] [Bathroom cabinet light] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [Bathroom cabinet light] if you notice any flickering when changing the brightness/colour, let me know on Discord/Github with model number [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [Bathroom cabinet light] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [Bathroom cabinet light] initialised with id [46:8B:D4:AD:FC:31:15:48] [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [TV Cabinet Lights] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [TV Cabinet Lights] if you notice any flickering when changing the brightness/colour, let me know on Discord/Github with model number [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [TV Cabinet Lights] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [TV Cabinet Lights] initialised with id [60:1C:D4:AD:FC:00:E6:AA] [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [Right cab light strip] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [Right cab light strip] if you notice any flickering when changing the brightness/colour, let me know on Discord/Github with model number [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [Right cab light strip] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [Right cab light strip] initialised with id [B3:46:D4:AD:FC:01:6E:E1] [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [Left Cab light Strip] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [Left Cab light Strip] if you notice any flickering when changing the brightness/colour, let me know on Discord/Github with model number [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [Left Cab light Strip] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [Left Cab light Strip] initialised with id [62:B9:D4:AD:FC:01:6F:93] [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [Bar Light Strip] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [Bar Light Strip] if you notice any flickering when changing the brightness/colour, let me know on Discord/Github with model number [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [Bar Light Strip] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [Bar Light Strip] initialised with id [3F:A5:D4:AD:FC:00:E9:21] [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [Dresser light strip] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [Dresser light strip] if you notice any flickering when changing the brightness/colour, let me know on Discord/Github with model number [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [Dresser light strip] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [Dresser light strip] initialised with id [8B:19:D4:AD:FC:33:0A:9B] [H619A].
[9/21/2022, 5:59:00 PM] [Govee] [Bedroom TV Lightstrip] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [Bedroom TV Lightstrip] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [Bedroom TV Lightstrip] initialised with id [62:4C:D7:39:32:37:28:24] [H6199].
[9/21/2022, 5:59:00 PM] [Govee] [Left Couch RJ Office] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [Left Couch RJ Office] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [Left Couch RJ Office] initialised with id [0E:ED:9C:04:A0:A4:68:7D] [H6008].
[9/21/2022, 5:59:00 PM] [Govee] [Right Couch RJ Office] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [Right Couch RJ Office] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [Right Couch RJ Office] initialised with id [F7:BE:9C:04:A0:95:1B:25] [H6008].
[9/21/2022, 5:59:00 PM] [Govee] [TV Lights] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [TV Lights] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [TV Lights] initialised with id [7F:AE:CE:33:34:36:1C:77] [H6199].
[9/21/2022, 5:59:00 PM] [Govee] [Balcony Lights] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [Balcony Lights] if you notice any flickering when changing the brightness/colour, let me know on Discord/Github with model number [H7020].
[9/21/2022, 5:59:00 PM] [Govee] [Balcony Lights] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [Balcony Lights] initialised with id [77:B9:CC:30:39:39:49:56] [H7020].
[9/21/2022, 5:59:00 PM] [Govee] [Joe’s Lamp] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [Joe’s Lamp] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [Joe’s Lamp] initialised with id [4D:12:9C:04:A0:49:C3:9B] [H6008].
[9/21/2022, 5:59:00 PM] [Govee] [RJ’s Lamp] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [RJ’s Lamp] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [RJ’s Lamp] initialised with id [6B:09:9C:04:A0:94:00:BF] [H6008].
[9/21/2022, 5:59:00 PM] [Govee] [LR3] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [LR3] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [LR3] initialised with id [A4:C4:9C:04:A0:A6:71:5B] [H6008].
[9/21/2022, 5:59:00 PM] [Govee] [LR4] has been added to Homebridge.
[9/21/2022, 5:59:00 PM] [Govee] [LR4] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","bluetooth":"disabled","brightnessStep":1,"logging":"standard"}.
[9/21/2022, 5:59:00 PM] [Govee] [LR4] initialised with id [9D:10:9C:04:A0:A6:6C:73] [H6008].
[9/21/2022, 5:59:00 PM] [Govee] Increasing API polling to 200s due to amount of API devices.
[9/21/2022, 5:59:00 PM] [Govee] [Bathroom cabinet light] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [Bathroom cabinet light] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [Bathroom cabinet light] current colour [rgb 255 222 173].
[9/21/2022, 5:59:00 PM] [Govee] [Right cab light strip] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [Right cab light strip] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [Right cab light strip] current colour [rgb 255 179 105].
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lamp 2] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lamp 2] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lamp 2] current colour [3000K / 333M].
[9/21/2022, 5:59:00 PM] [Govee] [LR3] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [LR3] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [LR3] current colour [5000K / 200M].
[9/21/2022, 5:59:00 PM] [Govee] [RJ’s Lamp] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [RJ’s Lamp] current brightness [6%].
[9/21/2022, 5:59:00 PM] [Govee] [RJ’s Lamp] current colour [3000K / 333M].
[9/21/2022, 5:59:00 PM] [Govee] [Balcony Lights] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [Balcony Lights] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [Balcony Lights] current colour [rgb 255 222 173].
[9/21/2022, 5:59:00 PM] [Govee] [Bedroom TV Lightstrip] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [Bedroom TV Lightstrip] current brightness [24%].
[9/21/2022, 5:59:00 PM] [Govee] [Bedroom TV Lightstrip] current colour [rgb 255 179 105].
[9/21/2022, 5:59:00 PM] [Govee] [Right Couch RJ Office] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [Right Couch RJ Office] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [Right Couch RJ Office] current colour [3000K / 333M].
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lightstrip] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lightstrip] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lightstrip] current colour [7143K / 140M].
[9/21/2022, 5:59:00 PM] [Govee] [LR4] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [LR4] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [LR4] current colour [5000K / 200M].
[9/21/2022, 5:59:00 PM] [Govee] [TV Cabinet Lights] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [TV Cabinet Lights] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [TV Cabinet Lights] current colour [rgb 255 222 173].
[9/21/2022, 5:59:00 PM] [Govee] [Left Cab light Strip] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [Left Cab light Strip] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [Left Cab light Strip] current colour [rgb 255 179 105].
[9/21/2022, 5:59:00 PM] [Govee] [Left Couch RJ Office] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [Left Couch RJ Office] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [Left Couch RJ Office] current colour [3000K / 333M].
[9/21/2022, 5:59:00 PM] [Govee] [Bar Light Strip] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [Bar Light Strip] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [Bar Light Strip] current colour [rgb 255 179 105].
[9/21/2022, 5:59:00 PM] [Govee] [Joe’s Lamp] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [Joe’s Lamp] current brightness [24%].
[9/21/2022, 5:59:00 PM] [Govee] [Joe’s Lamp] current colour [3000K / 333M].
[9/21/2022, 5:59:00 PM] [Govee] [Joe’s Office Lamp] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [Joe’s Office Lamp] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [Office TV] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [Office TV] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [Office TV] current colour [3302K / 303M].
[9/21/2022, 5:59:00 PM] [Govee] [Dresser light strip] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [Dresser light strip] current brightness [24%].
[9/21/2022, 5:59:00 PM] [Govee] [Dresser light strip] current colour [rgb 255 179 105].
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lamp] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lamp] current brightness [100%].
[9/21/2022, 5:59:00 PM] [Govee] [RJs Desk Lamp] current colour [3000K / 333M].
[9/21/2022, 5:59:00 PM] [Govee] [TV Lights] has been reported [online].
[9/21/2022, 5:59:00 PM] [Govee] [TV Lights] current brightness [35%].
[9/21/2022, 5:59:00 PM] [Govee] [TV Lights] current colour [rgb 255 222 173].
[9/21/2022, 5:59:02 PM] [Govee] ✓ Setup complete. Thanks for using this plugin, I hope you find it helpful!

```

**Comment by bwp91** [comment]
Closing this as a bit overwhelmed with issues.
Please update to the beta version of the plugin, and if you are still having issues, do reopen this ticket!
Thanks and apologies if closing prematurely.

**Comment by CodeTriager** [comment]
I'm having the same issue. In the Web UI it works like a charme, but in the home app it says that the devices are not responding. Has anyone an idea what to do? I already updated to the latest beta but theres no difference. 
`[28/10/2022, 10:33:20] [Govee] [LAN] server started listening on 0.0.0.0:4002.
[28/10/2022, 10:33:20] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge 4117) is running on port 51393.
[28/10/2022, 10:33:20] [Govee] [LAN] found device [{"msg":{"cmd":"scan","data":{"ip":"192.168.0.45","device":"xxx","sku":"H6072","bleVersionHard":"3.02.00","bleVersionSoft":"2.03.03","wifiVersionHard":"1.00.10","wifiVersionSoft":"1.02.11"}}}] [{"address":"192.168.0.45","family":"IPv4","port":50295,"size":210}].
[28/10/2022, 10:33:20] [Govee] [LAN] found device [{"msg":{"cmd":"scan","data":{"ip":"192.168.0.92","device":"xxx,"sku":"H61A2","bleVersionHard":"2.01.02","bleVersionSoft":"2.06.06","wifiVersionHard":"1.02.00","wifiVersionSoft":"2.04.06"}}}] [{"address":"192.168.0.92","family":"IPv4","port":63267,"size":210}].
[28/10/2022, 10:33:22] [Govee] [LAN] client enabled and found 2 device(s).
[28/10/2022, 10:33:22] [Govee] [HTTP] could not use existing access token as Cannot read properties of undefined (reading 'split') at default.pluginSetup (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:365:40).
[28/10/2022, 10:33:23] [Govee] [HTTP] disabling client as This email hasn't been registered yet. at default.login (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:58:15).
[28/10/2022, 10:33:23] [Govee] [AWS] disabling client as requires HTTP client.
[28/10/2022, 10:33:24] [Govee] [API] client enabled and found 2 device(s).
[28/10/2022, 10:33:24] [Govee] [BLE] client enabled.
[28/10/2022, 10:33:24] [Govee] [Stehlampe] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"unsupported","brightnessStep":1,"colourSafeMode":false,"lan":"enabled"}.
[28/10/2022, 10:33:24] [Govee] [Stehlampe] initialised with id [xxx] [H6072].
[28/10/2022, 10:33:24] [Govee] [LED Bogen] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"unsupported","brightnessStep":1,"colourSafeMode":false,"lan":"enabled"}.
[28/10/2022, 10:33:24] [Govee] [LED Bogen] initialised with id [xxx] [H61A2].
[28/10/2022, 10:33:24] [Govee] [BLE] stateChange: poweredOn.
[28/10/2022, 10:33:24] [Govee] [Stehlampe] [API] receiving update {"online":true,"powerState":"off","brightness":1,"colorTemInKelvin":2000,"colorTem":2000,"source":"API"}.
[28/10/2022, 10:33:24] [Govee] [Stehlampe] has been reported [online].
[28/10/2022, 10:33:24] [Govee] [Stehlampe] current colour [2000K / 500M].
[28/10/2022, 10:33:24] [Govee] [LED Bogen] [API] receiving update {"online":true,"powerState":"off","brightness":100,"colorTemInKelvin":53255,"colorTem":53255,"source":"API"}.
[28/10/2022, 10:33:24] [Govee] [LED Bogen] has been reported [online].
[28/10/2022, 10:33:25] [homebridge-govee] This plugin generated a warning from the characteristic 'Color Temperature': characteristic was supplied illegal value: number 19 exceeded minimum of 140. See https://homebridge.io/w/JtMGR for more info.
[28/10/2022, 10:33:25] [Govee] [LED Bogen] current colour [53255K / 19M].
[28/10/2022, 10:33:26] [Govee] ✓ Setup complete. Interested in sponsoring this plugin? https://github.com/sponsors/bwp91`
