### ISSUE TITLE
Leak Sensor does not update after water alarm

### ISSUE THREAD

**Issue by p51mustang** [bwp91/homebridge-govee#324]
I just installed the Homebridge-Govee plug in for Homebridge and am able to see all of the Govee H5054 leak sensors.

When I attempt to test them (water to alarm), I notice a leak alert within the Govee app, but not through HomeKit.  Then, when inspecting the HomeBridge log, I see the following:

[10/10/2022, 18:35:44] [Govee] [Bathroom] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:147:13).

Where Bathroom is the temporary name given to this sensor.

Here is the detailed log:

[10/10/2022, 18:40:44] [Govee] [H5054_843E] [HTTP] receiving update [{"source":"HTTP","battery":100,"leakDetected":false,"online":true}].
[10/10/2022, 18:40:44] [Govee] [Bathroom] raw data: {"online":true,"gwonline":true,"lastTime":1665440160000,"read":false,"battery":100,"openPush":true,"header":"2","gatewayVersionHard":"1.00.04","gatewayVersionSoft":"1.05.06","sku":"H5054","device":"CAC9A35F1128008491","deviceName":"Bathroom","versionHard":"1.0.0","versionSoft":"1.0.0"}.
[10/10/2022, 18:40:44] [Govee] [H5054_83F5] raw data: {"online":true,"gwonline":true,"lastTime":0,"read":false,"battery":100,"openPush":true,"header":"3","gatewayVersionHard":"1.00.04","gatewayVersionSoft":"1.05.06","sku":"H5054","device":"CAC9A35F11280083F5","deviceName":"H5054_83F5","versionHard":"1.0.0","versionSoft":"1.0.0"}.
[10/10/2022, 18:40:44] [Govee] [H5054_83F5] [HTTP] receiving update [{"source":"HTTP","battery":100,"leakDetected":false,"online":true}].
[10/10/2022, 18:40:44] [Govee] [Thermometer] [HTTP] receiving update [{"source":"HTTP","battery":100,"temperature":2050,"humidity":4350,"online":true}].
[10/10/2022, 18:40:45] [Govee] [Bathroom] could not be refreshed as no data received from Govee server whilst obtaining devices at default.getLeakDeviceWarning (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:147:13).

**Comment by bwp91** [comment]
Hi @p51mustang 

Please update to the beta version of the plugin you should find the leak sensors work in this version.

When you update and test the sensors, please wait up to 30 seconds for the homekit notification to come through. Then it will deactivate when you open the govee app and click “Got it” on the sensor messages page.

**Comment by p51mustang** [comment]
Thank you.  I've installed and will test today.
    On Tuesday, October 11, 2022, 02:08:10 AM EDT, Ben ***@***.***> wrote:  
 
 


Hi @p51mustang

Please update to the beta version of the plugin you should find the leak sensors work in this version.

When you update and test the sensors, please wait up to 30 seconds for the homekit notification to come through. Then it will deactivate when you open the govee app and click “Got it” on the sensor messages page.
