### ISSUE TITLE
Unable to add light strip 

### ISSUE THREAD

**Issue by surfahboy21** [bwp91/homebridge-govee#330]
### What issue do you have? Please be as thorough and explicit as possible.
Trying to get the Homebridge-govee plugin to recognize my new H6171 light strip. However, it keeps throwing an error that the "bluetooth-hci-socket" package is missing. Tried to install it manually via the "npm install @abandonware/bluetooth-hci-socket" command in the Homebridge UI terminal. But that didn't resolve anything.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
1.5.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Synology NAS / Node.js version 16.17.1

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
Version 6.0.4

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6171

### Please paste any relevant logs below.

```
[10/15/2022, 6:43:01 PM] [Govee] HTTP/AWS clients enabled as Govee username and password provided.
[10/15/2022, 6:43:01 PM] [Govee] Disabling API client as API key not provided.
[10/15/2022, 6:43:01 PM] [Govee] Disabling BLE client as Cannot find package '@abandonware/bluetooth-hci-socket' imported from /volume1/homebridge/node_modules/homebridge-govee/lib/platform.js at new NodeError (node:internal/errors:387:5).
[10/15/2022, 6:43:01 PM] [Govee] [Outdoor Strip Lights] [92:33:CD:37:34:32:36:02] will not be added to Homebridge unless configured and bluetooth enabled in config.
```

**Comment by bwp91** [comment]
Can you paste the output from running 
npm install @abandonware/bluetooth-hci-socket
in the homebridge terminal?

**Comment by surfahboy21** [comment]
Sure thing. Here you go...

```
npm ERR! code 1
npm ERR! path /volume1/homebridge/node_modules/@abandonware/bluetooth-hci-socket
npm ERR! command failed
npm ERR! command sh /tmp/install-2cda634d.sh
npm ERR! Failed to execute '/volume1/@appstore/homebridge/app/bin/node /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/volume1/homebridge/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node --module_name=bluetooth_hci_socket --module_path=/volume1/homebridge/node_modules/@abandonware/bluetooth-hci-socket/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-8/bluetooth_hci_socket-0.5.3-8-node-v93-linux-x64.tar.gz 
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: not found: make
npm ERR! gyp ERR! stack     at getNotFoundError (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:10:17)
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:57:18
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at step (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:54:21)
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:71:22
npm ERR! gyp ERR! stack     at new Promise (<anonymous>)
npm ERR! gyp ERR! stack     at subStep (/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:69:33)
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/which/which.js:80:22
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/index.js:42:5
npm ERR! gyp ERR! stack     at /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
npm ERR! gyp ERR! System Linux 4.4.180+
npm ERR! gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build" "--fallback-to-build" "--module=/volume1/homebridge/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node" "--module_name=bluetooth_hci_socket" "--module_path=/volume1/homebridge/node_modules/@abandonware/bluetooth-hci-socket/lib/binding" "--napi_version=8" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v93"
npm ERR! gyp ERR! cwd /volume1/homebridge/node_modules/@abandonware/bluetooth-hci-socket
npm ERR! gyp ERR! node -v v16.17.1
npm ERR! gyp ERR! node-gyp -v v9.0.0
npm ERR! gyp ERR! not ok 
npm ERR! node-pre-gyp ERR! build error 
npm ERR! node-pre-gyp ERR! stack Error: Failed to execute '/volume1/@appstore/homebridge/app/bin/node /volume1/@appstore/homebridge/app/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js build --fallback-to-build --module=/volume1/homebridge/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node --module_name=bluetooth_hci_socket --module_path=/volume1/homebridge/node_modules/@abandonware/bluetooth-hci-socket/lib/binding --napi_version=8 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v93' (1)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/volume1/homebridge/node_modules/@abandonware/bluetooth-hci-socket/node_modules/@mapbox/node-pre-gyp/lib/util/compile.js:89:23)
npm ERR! node-pre-gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! node-pre-gyp ERR! stack     at maybeClose (node:internal/child_process:1093:16)
npm ERR! node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! node-pre-gyp ERR! System Linux 4.4.180+
npm ERR! node-pre-gyp ERR! command "/volume1/@appstore/homebridge/app/bin/node" "/volume1/homebridge/node_modules/@abandonware/bluetooth-hci-socket/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
npm ERR! node-pre-gyp ERR! cwd /volume1/homebridge/node_modules/@abandonware/bluetooth-hci-socket
npm ERR! node-pre-gyp ERR! node -v v16.17.1
npm ERR! node-pre-gyp ERR! node-pre-gyp -v v1.0.10
npm ERR! node-pre-gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /var/packages/homebridge/home/.npm/_logs/2022-10-17T17_53_10_779Z-debug-0.log
```

**Comment by bwp91** [comment]
what os does synology use?

**Comment by surfahboy21** [comment]
Synology uses a proprietary (I think) OS called DiskStation Manager.
