### ISSUE TITLE
No [BLE] connection method available

### ISSUE THREAD

**Issue by tfp1** [bwp91/homebridge-govee#332]
### What issue do you have? Please be as thorough and explicit as possible.
* Plugin cannot use BLE module to connect and error thrown in the logs
* I have confirmed
  * Phone _can_ connect to strip
  * Phone connection to strip is disabled when attempting to use raspberrypi BLE connection
  * `enableBT == true` in the config file
  * `noble` is installed and running
  * 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
  * HOOBS

* Which version of Homebridge/HOOBS do you have?
  *  v4.2.8

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
  * RaspberryPi
  * npm 8.19.2

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
  * v6.0.4
  * Fresh install

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
  * `H6171`

### Please paste any relevant logs below.

```
10/16/2022, 12:19:38 PM raspberryPi raspberryPi starting
10/16/2022, 12:19:41 PM raspberryPi Loaded plugin 'homebridge-govee'
10/16/2022, 12:19:41 PM raspberryPi [ DEBUG ] Registering platform 'homebridge-govee.Govee'
10/16/2022, 12:19:41 PM raspberryPi Loading 1 platforms...
10/16/2022, 12:19:41 PM raspberryPi Govee Initialising plugin v6.0.4 | System linux | Node v16.17.1 | HB v1.5.0 | HAPNodeJS v0.10.2...
10/16/2022, 12:19:41 PM raspberryPi Govee Plugin initialised. Setting up accessories....
10/16/2022, 12:19:42 PM raspberryPi Bridge is running on port 51826.
10/16/2022, 12:19:42 PM raspberryPi Govee [LAN] server started listening [0.0.0.0:4002](http://0.0.0.0:4002/)
10/16/2022, 12:19:44 PM raspberryPi Govee LAN client enabled.
10/16/2022, 12:19:44 PM raspberryPi Govee Login successful.
10/16/2022, 12:19:44 PM raspberryPi Govee HTTP/AWS clients enabled as Govee username and password provided.
10/16/2022, 12:19:44 PM raspberryPi Govee [ WARNING ] Disabling API client as API key not provided.
10/16/2022, 12:19:45 PM raspberryPi Govee BLE client enabled as packages successfully found.
10/16/2022, 12:19:45 PM raspberryPi Govee [Outdoor Strip Lights] has been added to Homebridge.
10/16/2022, 12:19:45 PM raspberryPi Govee [Outdoor Strip Lights] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"logging":"debug"}.
10/16/2022, 12:19:45 PM raspberryPi Govee [Outdoor Strip Lights] initialised with id [8E:9F:D2:37:34:32:32:42] [H6171].
10/16/2022, 12:19:45 PM raspberryPi Govee [noble] stateChange: poweredOn.
10/16/2022, 12:19:47 PM raspberryPi Govee ✓ Setup complete. Don't forget to ☆ this plugin on GitHub if you're finding it useful!
10/16/2022, 12:19:59 PM raspberryPi Govee [Outdoor Strip Lights] starting update with params [{"cmd":1,"data":1}].
10/16/2022, 12:19:59 PM raspberryPi Govee [Outdoor Strip Lights] starting timer.
10/16/2022, 12:19:59 PM raspberryPi Govee [Outdoor Strip Lights] starting scan.
10/16/2022, 12:19:59 PM raspberryPi Govee [noble] scanning started.
10/16/2022, 12:19:59 PM raspberryPi Govee [Outdoor Strip Lights] scanning started.
10/16/2022, 12:19:59 PM raspberryPi Govee [Outdoor Strip Lights] starting loop.
10/16/2022, 12:19:59 PM raspberryPi Govee [noble] found device [7c:61:49:05:02:5d] [undefined].
10/16/2022, 12:19:59 PM raspberryPi Govee [noble] found device [11:b7:37:6e:fe:50] [undefined].
10/16/2022, 12:19:59 PM raspberryPi Govee [noble] found device [70:77:b6:6e:8f:db] [undefined].
10/16/2022, 12:19:59 PM raspberryPi Govee [noble] found device [7f:2b:c8:84:50:67] [undefined].
10/16/2022, 12:19:59 PM raspberryPi Govee [noble] found device [d2:37:34:32:32:42] [Govee_H6171_3242].
10/16/2022, 12:19:59 PM raspberryPi Govee [Outdoor Strip Lights] has been reported [discoverable] via BLE.
10/16/2022, 12:19:59 PM raspberryPi Govee [Outdoor Strip Lights] attempting to connect.
10/16/2022, 12:20:00 PM raspberryPi Govee [noble] scanning stopped.
10/16/2022, 12:20:00 PM raspberryPi Govee [noble] scanning started.
10/16/2022, 12:20:00 PM raspberryPi Govee [Outdoor Strip Lights] has been reported [connected] via BLE.
10/16/2022, 12:20:00 PM raspberryPi Govee [Outdoor Strip Lights] finding device characteristics.
10/16/2022, 12:20:02 PM raspberryPi Govee [Outdoor Strip Lights] has been reported [disconnected] via BLE [undefined].
10/16/2022, 12:20:06 PM raspberryPi Govee [ WARNING ] [Outdoor Strip Lights] could not find device [d2:37:34:32:32:42].
10/16/2022, 12:20:06 PM raspberryPi Govee [ WARNING ] [Outdoor Strip Lights] reverting to API as BLE took too long.
10/16/2022, 12:20:06 PM raspberryPi Govee [ WARNING ] [Outdoor Strip Lights] could not be updated as no connection method available at file:///var/lib/hoobs/raspberrypi/node_modules/homebridge-govee/lib/platform.js:1569:13.

### 

Added [d2:37:34:32:32:42] as Custom Bluetooth Address in the configuration file

###

10/16/2022, 12:21:01 PM raspberryPi Configuration change 
10/16/2022, 12:21:01 PM raspberryPi raspberrypi stopping
10/16/2022, 12:21:05 PM raspberryPi raspberryPi starting
10/16/2022, 12:21:08 PM raspberryPi Loaded plugin 'homebridge-govee'
10/16/2022, 12:21:08 PM raspberryPi [ DEBUG ] Registering platform 'homebridge-govee.Govee'
10/16/2022, 12:21:08 PM raspberryPi Loading 1 platforms...
10/16/2022, 12:21:08 PM raspberryPi Govee Initialising plugin v6.0.4 | System linux | Node v16.17.1 | HB v1.5.0 | HAPNodeJS v0.10.2...
10/16/2022, 12:21:08 PM raspberryPi Govee Plugin initialised. Setting up accessories....
10/16/2022, 12:21:08 PM raspberryPi Bridge is running on port 51826.
10/16/2022, 12:21:08 PM raspberryPi Govee [LAN] server started listening [0.0.0.0:4002](http://0.0.0.0:4002/)
10/16/2022, 12:21:10 PM raspberryPi Govee LAN client enabled.
10/16/2022, 12:21:10 PM raspberryPi Govee Login successful.
10/16/2022, 12:21:11 PM raspberryPi Govee HTTP/AWS clients enabled as Govee username and password provided.
10/16/2022, 12:21:11 PM raspberryPi Govee [ WARNING ] Disabling API client as API key not provided.
10/16/2022, 12:21:11 PM raspberryPi Govee BLE client enabled as packages successfully found.
10/16/2022, 12:21:11 PM raspberryPi Govee [Outdoor Strip Lights] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"logging":"debug"}.
10/16/2022, 12:21:11 PM raspberryPi Govee [Outdoor Strip Lights] initialised with id [8E:9F:D2:37:34:32:32:42] [H6171].
10/16/2022, 12:21:11 PM raspberryPi Govee [noble] stateChange: poweredOn.
10/16/2022, 12:21:13 PM raspberryPi Govee ✓ Setup complete. Interested in sponsoring this plugin? https://github.com/sponsors/bwp91
10/16/2022, 12:21:20 PM raspberryPi Govee [Outdoor Strip Lights] starting update with params [{"cmd":1,"data":1}].
10/16/2022, 12:21:20 PM raspberryPi Govee [Outdoor Strip Lights] starting timer.
10/16/2022, 12:21:20 PM raspberryPi Govee [Outdoor Strip Lights] starting scan.
10/16/2022, 12:21:20 PM raspberryPi Govee [noble] scanning started.
10/16/2022, 12:21:20 PM raspberryPi Govee [Outdoor Strip Lights] scanning started.
10/16/2022, 12:21:20 PM raspberryPi Govee [Outdoor Strip Lights] starting loop.
10/16/2022, 12:21:20 PM raspberryPi Govee [noble] found device [70:77:b6:6e:8f:db] [undefined].
10/16/2022, 12:21:20 PM raspberryPi Govee [noble] found device [7f:2b:c8:84:50:67] [undefined].
10/16/2022, 12:21:20 PM raspberryPi Govee [noble] found device [84:1e:a3:73:fd:d7] [Pod BS84100EA6].
10/16/2022, 12:21:20 PM raspberryPi Govee [noble] found device [d2:37:34:32:32:42] [Govee_H6171_3242].
10/16/2022, 12:21:20 PM raspberryPi Govee [Outdoor Strip Lights] has been reported [discoverable] via BLE.
10/16/2022, 12:21:20 PM raspberryPi Govee [Outdoor Strip Lights] attempting to connect.
10/16/2022, 12:21:20 PM raspberryPi Govee [noble] scanning stopped.
10/16/2022, 12:21:20 PM raspberryPi Govee [noble] scanning started.
10/16/2022, 12:21:20 PM raspberryPi Govee [Outdoor Strip Lights] has been reported [connected] via BLE.
10/16/2022, 12:21:20 PM raspberryPi Govee [Outdoor Strip Lights] finding device characteristics.
10/16/2022, 12:21:20 PM raspberryPi Govee [Outdoor Strip Lights] has been reported [disconnected] via BLE [undefined].
10/16/2022, 12:21:27 PM raspberryPi Govee [ WARNING ] [Outdoor Strip Lights] could not find device [d2:37:34:32:32:42].
10/16/2022, 12:21:27 PM raspberryPi Govee [ WARNING ] [Outdoor Strip Lights] reverting to API as BLE took too long.
10/16/2022, 12:21:27 PM raspberryPi Govee [ WARNING ] [Outdoor Strip Lights] could not be updated as no connection method available at file:///var/lib/hoobs/raspberrypi/node_modules/homebridge-govee/lib/platform.js:1569:13.
```

**Comment by ghost** [comment]
Try v7.0.0-beta.0

**Comment by tfp1** [comment]
Updated and similar issue:

```
10/16/2022, 2:27:10 PM Hub raspberryPi starting
10/16/2022, 2:27:14 PM raspberryPi Loaded plugin 'homebridge-govee'
10/16/2022, 2:27:14 PM raspberryPi [ DEBUG ] Registering platform 'homebridge-govee.Govee'
10/16/2022, 2:27:14 PM raspberryPi Loading 1 platforms...
10/16/2022, 2:27:14 PM raspberryPi Govee Initialising plugin v7.0.0-beta.0 | System linux | Node v16.17.1 | HB v1.5.0 | HAPNodeJS v0.10.2...
10/16/2022, 2:27:14 PM raspberryPi Govee Plugin initialised. Setting up accessories....
10/16/2022, 2:27:14 PM raspberryPi Bridge is running on port 51826.
10/16/2022, 2:27:14 PM raspberryPi Govee [LAN] server started listening on 0.0.0.0:4002.
10/16/2022, 2:27:16 PM raspberryPi Govee LAN client enabled and initial scan found 0 device(s).
10/16/2022, 2:27:16 PM raspberryPi Govee Login successful.
10/16/2022, 2:27:16 PM raspberryPi Govee HTTP/AWS clients enabled and found 1 device(s)..
10/16/2022, 2:27:16 PM raspberryPi Govee [ WARNING ] Disabling API client as API key not provided.
10/16/2022, 2:27:17 PM raspberryPi Govee BLE client enabled as packages successfully found.
10/16/2022, 2:27:17 PM raspberryPi Govee [Outdoor Strip Lights] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1}.
10/16/2022, 2:27:17 PM raspberryPi Govee [Outdoor Strip Lights] initialised with id [8E:9F:D2:37:34:32:32:42] [H6171].
10/16/2022, 2:27:17 PM raspberryPi Govee [noble] stateChange: poweredOn.
10/16/2022, 2:27:19 PM raspberryPi Govee ✓ Setup complete. Want to see this plugin in your own language? Let me know!
10/16/2022, 2:28:40 PM Hub [ WARNING ] plugin site unavailable
10/16/2022, 2:29:36 PM raspberryPi Govee [Outdoor Strip Lights] starting update with params [{"cmd":1,"data":0}].
10/16/2022, 2:29:36 PM raspberryPi Govee [Outdoor Strip Lights] starting timer.
10/16/2022, 2:29:36 PM raspberryPi Govee [Outdoor Strip Lights] starting scan.
10/16/2022, 2:29:36 PM raspberryPi Govee [noble] scanning started.
10/16/2022, 2:29:36 PM raspberryPi Govee [Outdoor Strip Lights] [%s] scanning started.
10/16/2022, 2:29:36 PM raspberryPi Govee [Outdoor Strip Lights] starting loop.
10/16/2022, 2:29:37 PM raspberryPi Govee [noble] found device [d2:37:34:32:32:42] [Govee_H6171_3242].
10/16/2022, 2:29:37 PM raspberryPi Govee [Outdoor Strip Lights] has been reported [discoverable] via BLE.
10/16/2022, 2:29:37 PM raspberryPi Govee [Outdoor Strip Lights] attempting to connect.
10/16/2022, 2:29:38 PM raspberryPi Govee [noble] scanning stopped.
10/16/2022, 2:29:38 PM raspberryPi Govee [noble] scanning started.
10/16/2022, 2:29:38 PM raspberryPi Govee [Outdoor Strip Lights] has been reported [connected] via BLE.
10/16/2022, 2:29:38 PM raspberryPi Govee [Outdoor Strip Lights] finding device characteristics.
10/16/2022, 2:29:41 PM raspberryPi Govee [Outdoor Strip Lights] has been reported [disconnected] via BLE [undefined].
10/16/2022, 2:29:44 PM raspberryPi Govee [ WARNING ] [Outdoor Strip Lights] could not find device [d2:37:34:32:32:42].
10/16/2022, 2:29:44 PM raspberryPi Govee [ WARNING ] [Outdoor Strip Lights] not using BLE connection as BLE took too long.
10/16/2022, 2:29:44 PM raspberryPi Govee [ WARNING ] [Outdoor Strip Lights] could not be updated as no connection method available at file:///var/lib/hoobs/raspberrypi/node_modules/homebridge-govee/lib/platform.js:1639:13.
```

**Comment by strohganoff** [comment]
I'm getting this same issue with led strip h6102. Not sure if I'm missing a step.

**Comment by bwp91** [comment]
does anyone here also have any other plugins installed which make use of bluetooth?

**Comment by christianonpele** [comment]
same here with H6053 (no BT / no AWS). I downgrade the plugin to 5.0.1 to have ON/OFF and brightness feature working. Unfortunately the color selector feature isnt working with that version.
