### ISSUE TITLE
⚠️  Plugin v7 discussions/bugs

### ISSUE THREAD

**Issue by bwp91** [bwp91/homebridge-govee#336]
Please report any issues with v7 in this thread.

Note that v7 is not a 'perfect' release.

As always, this plugin is a work in progress hopefully for the better!

**Comment by tjridge** [comment]
Please post the following on GitHub:
H7132
{
  "mode": {
    "options": [
      {
        "name": "Low",
        "value": "1"
      },
      {
        "name": "Medium",
        "value": "2"
      },
      {
        "name": "High",
        "value": "3"
      },
      {
        "name": "Fan",
        "value": "4"
      },
      {
        "name": "Auto",
        "value": "5"
      }
    ]
  }
}

**Comment by bwp91** [comment]
Hi @tjridge thanks for this! this message will not show in future versions of the plugin including the beta version available now.

**Comment by ghost** [comment]
Not a bug, more of an experience of how the LAN function works... Absolutely perfect!!!

I have refrained from buying Govee devices because of cloud and bluetooth. But not anymore :)

**Comment by tjridge** [comment]
Some devices using adaptive lighting are turning themselves on at weird times. I have 2 that turn on in the middle of the night with no commands send from me.

**Comment by dmatchx** [comment]
since v7 I my H6141 LED can't change color or change brightness from home app or hombridge GUI.

**Comment by bwp91** [comment]
> Some devices using adaptive lighting are turning themselves on at weird times. I have 2 that turn on in the middle of the night with no commands send from me.

hi @tjridge it would be interesting to see logs from around the time this happens, if possible, to see why this is happening. the adaptive lighting command is sent every minute from homekit but the plugin is supposed to ignore this if the device is off.

**Comment by bwp91** [comment]
> since v7 I my H6141 LED can't change color or change brightness from home app or hombridge GUI.

hi @dmatchx can you turn on plugin debug logging and try do perform an action like turning on/off and show the logs?

**Comment by masonjmiller** [comment]
My child govee bridge on is currently stuck in a loop due to this error since updating to 7.1.0. Only downgrading to 7.0.1 does the error go away but I was having issues with LED strips not reporting states correctly in that version.

SyntaxError: Unexpected token � in JSON at position 0
    at JSON.parse (<anonymous>)
    at DeviceClient.<anonymous> (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/aws.js:51:22)
    at DeviceClient.emit (node:events:513:28)
    at MqttClient.<anonymous> (/var/lib/homebridge/node_modules/homebridge-govee/node_modules/aws-iot-device-sdk/device/index.js:826:12)
    at MqttClient.emit (node:events:513:28)
    at MqttClient._handlePublish (/var/lib/homebridge/node_modules/homebridge-govee/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/var/lib/homebridge/node_modules/homebridge-govee/node_modules/mqtt/lib/client.js:410:12)
    at work (/var/lib/homebridge/node_modules/homebridge-govee/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/var/lib/homebridge/node_modules/homebridge-govee/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/var/lib/homebridge/node_modules/homebridge-govee/node_modules/readable-stream/lib/_stream_writable.js:409:139)

**Comment by bwp91** [comment]
Hi @masonjmiller please try v7.1.1

**Comment by ryanlbates01** [comment]
> > since v7 I my H6141 LED can't change color or change brightness from home app or hombridge GUI.
> 
> hi @dmatchx can you turn on plugin debug logging and try do perform an action like turning on/off and show the logs?

I have a similar issue but with a different device (H6159), I cant select an RGB Color in the home app. I have opened a case with my logs #341

**Comment by bwp91** [comment]
@CodeTriager

Have brought your issue here

> I'm having the same issue. In the Web UI it works like a charme, but in the home app it says that the devices are not responding. Has anyone an idea what to do? I already updated to the latest beta but theres no difference.


  ```

[28/10/2022, 10:33:20] [Govee] [LAN] server started listening on 0.0.0.0:4002. [28/10/2022, 10:33:20] Homebridge v1.5.0 (HAP v0.10.2) (Homebridge 4117) is running on port 51393.
[28/10/2022, 10:33:20] [Govee] [LAN] found device [{"msg":{"cmd":"scan","data":{"ip":"192.168.0.45","device":"xxx","sku":"H6072","bleVersionHard":"3.02.00","bleVersionSoft":"2.03.03","wifiVersionHard":"1.00.10","wifiVersionSoft":"1.02.11"}}}] [{"address":"192.168.0.45","family":"IPv4","port":50295,"size":210}].
[28/10/2022, 10:33:20] [Govee] [LAN] found device [{"msg":{"cmd":"scan","data":{"ip":"192.168.0.92","device":"xxx,"sku":"H61A2","bleVersionHard":"2.01.02","bleVersionSoft":"2.06.06","wifiVersionHard":"1.02.00","wifiVersionSoft":"2.04.06"}}}] [{"address":"192.168.0.92","family":"IPv4","port":63267,"size":210}].
[28/10/2022, 10:33:22] [Govee] [LAN] client enabled and found 2 device(s).
[28/10/2022, 10:33:22] [Govee] [HTTP] could not use existing access token as Cannot read properties of undefined (reading 'split') at default.pluginSetup (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:365:40).
[28/10/2022, 10:33:23] [Govee] [HTTP] disabling client as This email hasn't been registered yet. at default.login (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:58:15).
[28/10/2022, 10:33:23] [Govee] [AWS] disabling client as requires HTTP client.
[28/10/2022, 10:33:24] [Govee] [API] client enabled and found 2 device(s).
[28/10/2022, 10:33:24] [Govee] [BLE] client enabled.
[28/10/2022, 10:33:24] [Govee] [Stehlampe] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"unsupported","brightnessStep":1,"colourSafeMode":false,"lan":"enabled"}.
[28/10/2022, 10:33:24] [Govee] [Stehlampe] initialised with id [xxx] [H6072].
[28/10/2022, 10:33:24] [Govee] [LED Bogen] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"unsupported","brightnessStep":1,"colourSafeMode":false,"lan":"enabled"}.
[28/10/2022, 10:33:24] [Govee] [LED Bogen] initialised with id [xxx] [H61A2].
[28/10/2022, 10:33:24] [Govee] [BLE] stateChange: poweredOn.
[28/10/2022, 10:33:24] [Govee] [Stehlampe] [API] receiving update {"online":true,"powerState":"off","brightness":1,"colorTemInKelvin":2000,"colorTem":2000,"source":"API"}.
[28/10/2022, 10:33:24] [Govee] [Stehlampe] has been reported [online].
[28/10/2022, 10:33:24] [Govee] [Stehlampe] current colour [2000K / 500M].
[28/10/2022, 10:33:24] [Govee] [LED Bogen] [API] receiving update {"online":true,"powerState":"off","brightness":100,"colorTemInKelvin":53255,"colorTem":53255,"source":"API"}.
[28/10/2022, 10:33:24] [Govee] [LED Bogen] has been reported [online].
[28/10/2022, 10:33:25] [homebridge-govee] This plugin generated a warning from the characteristic 'Color Temperature': characteristic was supplied illegal value: number 19 exceeded minimum of 140. See https://homebridge.io/w/JtMGR for more info.
[28/10/2022, 10:33:25] [Govee] [LED Bogen] current colour [53255K / 19M].
[28/10/2022, 10:33:26] [Govee] ✓ Setup complete. Interested in sponsoring this plugin? https://github.com/sponsors/bwp91
```

**Comment by dmatchx** [comment]
> > since v7 I my H6141 LED can't change color or change brightness from home app or hombridge GUI.
> 
> hi @dmatchx can you turn on plugin debug logging and try do perform an action like turning on/off and show the logs?


@bwp91 Sorry for late response, Here is log with debug on. not seeing any error also (TV LED is the strip in question) also have another led strip and that one doesn't have any issue.

11/1/2022, 12:47:29 PMHOOBSGovee[AWS] message event [{"proType":0,"msg":"{\"transaction\":\"v_1667321247896000\",\"sku\":\"H6110\",\"device\":\"A2:AB:A4:C1:38:D8:9E:BD\",\"cmdVersion\":0,\"type\":0,\"cmd\":\"status\",\"data\":\"{\\\"softversion\\\":\\\"1.07.02\\\",\\\"wifiSoftVersion\\\":\\\"1.03.05\\\",\\\"turn\\\":0,\\\"brightness\\\":117,\\\"modeValue\\\":[\\\"qgUC////Af+NCwAAAAAAAAAAACo=\\\"],\\\"mode\\\":2,\\\"timer\\\":{\\\"enable\\\":0,\\\"time\\\":[{\\\"openHour\\\":0,\\\"openMin\\\":0,\\\"closeHour\\\":23,\\\"closeMin\\\":59}]},\\\"color\\\":{\\\"red\\\":255,\\\"green\\\":141,\\\"blue\\\":11},\\\"colorTemInKelvin\\\":2000}\"}","state":{"onOff":0,"brightness":117,"color":{"r":255,"g":141,"b":11},"colorTemInKelvin":2000,"connected":"true","sku":"H6110","device":"A2:AB:A4:C1:38:D8:9E:BD"}}].
11/1/2022, 12:47:29 PMHOOBSGovee✓ Setup complete. Want to see this plugin in your own language? Let me know!
11/1/2022, 12:47:44 PMHOOBSGovee[TV LED] [AWS] sending update {"msg":{"cmd":"color","cmdVersion":0,"data":{"r":18,"g":255,"b":168,"red":18,"green":255,"blue":168},"transaction":"v_1667321264998000","type":1}}.
11/1/2022, 12:47:45 PMHOOBSGovee[TV LED] current colour [rgb 18 255 168].
11/1/2022, 12:47:45 PMHOOBSGovee[AWS] message event [{"proType":2,"sku":"H6141","device":"27:D0:9C:04:A0:15:B3:43","softVersion":"2.04.00","wifiSoftVersion":"1.00.11","cmd":"color","type":2,"transaction":"v_1667321264998000","pactType":2,"pactCode":1,"state":{"result":0}}].
11/1/2022, 12:47:45 PMHOOBSGovee[TV LED] [AWS] receiving update {"source":"AWS","result":0}.
11/1/2022, 12:47:50 PMHOOBSGovee[TV LED] [AWS] sending update {"msg":{"cmd":"color","cmdVersion":0,"data":{"r":140,"g":0,"b":255,"red":140,"green":0,"blue":255},"transaction":"v_1667321270840000","type":1}}.
11/1/2022, 12:47:50 PMHOOBSGovee[TV LED] current colour [rgb 140 0 255].
11/1/2022, 12:47:51 PMHOOBSGovee[AWS] message event [{"proType":2,"sku":"H6141","device":"27:D0:9C:04:A0:15:B3:43","softVersion":"2.04.00","wifiSoftVersion":"1.00.11","cmd":"color","type":2,"transaction":"v_1667321270840000","pactType":2,"pactCode":1,"state":{"result":0}}].
11/1/2022, 12:47:51 PMHOOBSGovee[TV LED] [AWS] receiving update {"source":"AWS","result":0}.
11/1/2022, 12:47:57 PMHOOBSGovee[Smart Air Purifier] [AWS] sending update {"msg":{"cmd":"status","cmdVersion":2,"transaction":"v_1667321277897000","type":0}}.
11/1/2022, 12:47:57 PMHOOBSGovee[TV LED] [AWS] sending update {"msg":{"cmd":"status","cmdVersion":2,"transaction":"v_1667321277899000","type":0}}.
11/1/2022, 12:47:57 PMHOOBSGovee[Kids LED] [AWS] sending update {"msg":{"cmd":"status","cmdVersion":2,"transaction":"v_1667321277900000","type":0}}.
11/1/2022, 12:47:58 PMHOOBSGovee[AWS] message event [{"proType":2,"sku":"H7121","device":"21:B4:9C:04:A0:A2:6A:CB","softVersion":"1.00.21","wifiSoftVersion":"1.00.21","cmd":"status","type":0,"transaction":"v_1667321277897000","pactType":1,"pactCode":1,"state":{"onOff":0,"result":1},"op":{"command":["qhIAAAAAAAAAAAAAAAAAAAAAALg=","qhEAAAAAAAAAAAAAAAAAAAAAALs=","qgUDAAAAAAAAAAAAAAAAAAAAAKw=","qhAAAAAAAAAAAAAAAAAAAAAAALo=","qhYAAAAXOwAAAAAAAAAAAAAAAJA=","qhkAAAAAAAAAAAAAAAAAAAAAALM=","qhgAVwAAAAAAAAAAAAAAAAAAAOU="]}}].
11/1/2022, 12:47:58 PMHOOBSGovee[Smart Air Purifier] [AWS] receiving update {"source":"AWS","onOff":0,"result":1,"commands":["qhIAAAAAAAAAAAAAAAAAAAAAALg=","qhEAAAAAAAAAAAAAAAAAAAAAALs=","qgUDAAAAAAAAAAAAAAAAAAAAAKw=","qhAAAAAAAAAAAAAAAAAAAAAAALo=","qhYAAAAXOwAAAAAAAAAAAAAAAJA=","qhkAAAAAAAAAAAAAAAAAAAAAALM=","qhgAVwAAAAAAAAAAAAAAAAAAAOU="]}.
11/1/2022, 12:47:58 PMHOOBSGoveeWARNING[Smart Air Purifier] new scene code: [qhIAAAAAAAAAAAAAAAAAAAAAALg=] [aa120000000000000000000000000000000000b8].
11/1/2022, 12:47:58 PMHOOBSGoveeWARNING[Smart Air Purifier] new scene code: [qhEAAAAAAAAAAAAAAAAAAAAAALs=] [aa110000000000000000000000000000000000bb].
11/1/2022, 12:47:58 PMHOOBSGoveeWARNING[Smart Air Purifier] new scene code: [qgUDAAAAAAAAAAAAAAAAAAAAAKw=] [aa050300000000000000000000000000000000ac].
11/1/2022, 12:47:58 PMHOOBSGoveeWARNING[Smart Air Purifier] new scene code: [qhAAAAAAAAAAAAAAAAAAAAAAALo=] [aa100000000000000000000000000000000000ba].
11/1/2022, 12:47:58 PMHOOBSGoveeWARNING[Smart Air Purifier] new scene code: [qhYAAAAXOwAAAAAAAAAAAAAAAJA=] [aa16000000173b00000000000000000000000090].
11/1/2022, 12:47:58 PMHOOBSGoveeWARNING[Smart Air Purifier] new scene code: [qhkAAAAAAAAAAAAAAAAAAAAAALM=] [aa190000000000000000000000000000000000b3].
11/1/2022, 12:47:58 PMHOOBSGoveeWARNING[Smart Air Purifier] new scene code: [qhgAVwAAAAAAAAAAAAAAAAAAAOU=] [aa180057000000000000000000000000000000e5].
11/1/2022, 12:47:58 PMHOOBSGovee[Kids LED] [API] receiving update {"online":true,"powerState":"off","brightness":46,"colorTemInKelvin":2000,"colorTem":2000,"source":"API"}.
11/1/2022, 12:47:58 PMHOOBSGovee[TV LED] [API] receiving update {"online":true,"powerState":"on","brightness":100,"color":{"r":139,"b":255,"g":0},"source":"API"}.
11/1/2022, 12:47:58 PMHOOBSGovee[AWS] message event [{"proType":2,"sku":"H6141","device":"27:D0:9C:04:A0:15:B3:43","softVersion":"2.04.00","wifiSoftVersion":"1.00.11","cmd":"status","type":0,"transaction":"v_1667321277899000","pactType":2,"pactCode":1,"state":{"onOff":1,"brightness":100,"color":{"r":139,"g":0,"b":255},"colorTemInKelvin":0,"mode":4,"result":1},"op":{"command":["qgUEiAAAAAAAAAAAAAAAAAAAACM=","qhEAHg8PAAAAAAAAAAAAAAAAAKU=","qhL/ZAAAgAoAAAAAAAAAAAAAAKk=","qiP/AQYeAAAAAIAAAACAAAAAgO8="]}}].
11/1/2022, 12:47:58 PMHOOBSGovee[TV LED] [AWS] receiving update {"source":"AWS","onOff":1,"brightness":100,"color":{"r":139,"g":0,"b":255},"colorTemInKelvin":0,"mode":4,"result":1,"commands":["qgUEiAAAAAAAAAAAAAAAAAAAACM=","qhEAHg8PAAAAAAAAAAAAAAAAAKU=","qhL/ZAAAgAoAAAAAAAAAAAAAAKk=","qiP/AQYeAAAAAIAAAACAAAAAgO8="]}.
11/1/2022, 12:47:58 PMHOOBSGoveeWARNING[TV LED] new scene code: [qgUEiAAAAAAAAAAAAAAAAAAAACM=] [aa05048800000000000000000000000000000023].
11/1/2022, 12:47:58 PMHOOBSGoveeWARNING[TV LED] new scene code: [qhEAHg8PAAAAAAAAAAAAAAAAAKU=] [aa11001e0f0f00000000000000000000000000a5].
11/1/2022, 12:47:58 PMHOOBSGoveeWARNING[TV LED] new scene code: [qhL/ZAAAgAoAAAAAAAAAAAAAAKk=] [aa12ff640000800a0000000000000000000000a9].
11/1/2022, 12:47:58 PMHOOBSGoveeWARNING[TV LED] new scene code: [qiP/AQYeAAAAAIAAAACAAAAAgO8=] [aa23ff01061e00000000800000008000000080ef].
11/1/2022, 12:47:59 PMHOOBSGovee[AWS] message event [{"proType":0,"msg":"{\"transaction\":\"v_1667321277900000\",\"sku\":\"H6110\",\"device\":\"A2:AB:A4:C1:38:D8:9E:BD\",\"cmdVersion\":0,\"type\":0,\"cmd\":\"status\",\"data\":\"{\\\"softversion\\\":\\\"1.07.02\\\",\\\"wifiSoftVersion\\\":\\\"1.03.05\\\",\\\"turn\\\":0,\\\"brightness\\\":117,\\\"modeValue\\\":[\\\"qgUC////Af+NCwAAAAAAAAAAACo=\\\"],\\\"mode\\\":2,\\\"timer\\\":{\\\"enable\\\":0,\\\"time\\\":[{\\\"openHour\\\":0,\\\"openMin\\\":0,\\\"closeHour\\\":23,\\\"closeMin\\\":59}]},\\\"color\\\":{\\\"red\\\":255,\\\"green\\\":141,\\\"blue\\\":11},\\\"colorTemInKelvin\\\":2000}\"}","state":{"onOff":0,"brightness":117,"color":{"r":255,"g":141,"b":11},"colorTemInKelvin":2000,"connected":"true","sku":"H6110","device":"A2:AB:A4:C1:38:D8:9E:BD"}}].
11/1/2022, 12:48:04 PMHOOBSGovee[TV LED] [AWS] sending update {"msg":{"cmd":"color","cmdVersion":0,"data":{"r":60,"g":0,"b":255,"red":60,"green":0,"blue":255},"transaction":"v_1667321284270000","type":1}}.
11/1/2022, 12:48:04 PMHOOBSGovee[TV LED] current colour [rgb 60 0 255].
11/1/2022, 12:48:04 PMHOOBSGovee[AWS] message event [{"proType":2,"sku":"H6141","device":"27:D0:9C:04:A0:15:B3:43","softVersion":"2.04.00","wifiSoftVersion":"1.00.11","cmd":"color","type":2,"transaction":"v_1667321284270000","pactType":2,"pactCode":1,"state":{"result":0}}].
11/1/2022, 12:48:04 PMHOOBSGovee[TV LED] [AWS] receiving update {"source":"AWS","result":0}.
11/1/2022, 12:48:06 PMHOOBSGovee[TV LED] [AWS] sending update {"msg":{"cmd":"color","cmdVersion":0,"data":{"r":255,"g":82,"b":104,"red":255,"green":82,"blue":104},"transaction":"v_1667321286497000","type":1}}.
11/1/2022, 12:48:06 PMHOOBSGovee[TV LED] current colour [rgb 255 82 104].
11/1/2022, 12:48:06 PMHOOBSGovee[AWS] message event [{"proType":2,"sku":"H6141","device":"27:D0:9C:04:A0:15:B3:43","softVersion":"2.04.00","wifiSoftVersion":"1.00.11","cmd":"color","type":2,"transaction":"v_1667321286497000","pactType":2,"pactCode":1,"state":{"result":0}}].
11/1/2022, 12:48:06 PMHOOBSGovee[TV LED] [AWS] receiving update {"source":"AWS","result":0}.

**Comment by bwp91** [comment]
@dmatchx 
just realised i hebe got back to you here. 
i assume you are still having trouble with the H6141?
