### ISSUE TITLE
Plugin errors out after upgrade to Node.js version 18.12.0

### ISSUE THREAD

**Issue by SemoTech** [bwp91/homebridge-govee#344]
### What issue do you have? Please be as thorough and explicit as possible.
Plugin errors out after upgrade to Node.js version 18.12.0

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?
Homebridge v1.5.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

MacMini running Ubuntu and Docker.
Node.js version 18.12.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v7.1.1

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
n/a this is a plugin startup issue.

### Please paste any relevant logs below.

```
[10/29/2022, 12:14:52 PM] ====================
[10/29/2022, 12:14:52 PM] ERROR LOADING PLUGIN homebridge-plugin-govee:
[10/29/2022, 12:14:52 PM] Error: The module '/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/index.js:8:20)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
[10/29/2022, 12:14:52 PM] ====================
```

**Comment by bwp91** [comment]
Please uninstall and reinstall the plugin, this will trigger a rebuild of what is needed.
There will be no loss of homekit data (ie accessories, scenes, automation) so long as you uninstall and reinstall plugin without restarting homebridge between.

**Comment by SemoTech** [comment]
Thanks for the prompt reply @bwp91 Ben.
I followed your instructions and uninstalled then re-installed, without restarting homebridge, and updated the plugin from vv7.1.1  to v7.1.2 yet the issue persists.  Do note that I had to re-enter the config settings, as they were lost them the plugin was uninstalled. 

Here is the log from final homebridge restart:

`[11/1/2022, 8:23:56 AM] ====================
[11/1/2022, 8:23:56 AM] ERROR LOADING PLUGIN homebridge-plugin-govee:
[11/1/2022, 8:23:56 AM] Error: The module '/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/index.js:8:20)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
[11/1/2022, 8:23:56 AM] ====================`

**Comment by SemoTech** [comment]
Thanks for the prompt reply @bwp91 Ben.
I updated the plugin from vv7.1.1  to vv7.1.2 yet the issue persists:

`[11/1/2022, 8:23:56 AM] ====================
[11/1/2022, 8:23:56 AM] ERROR LOADING PLUGIN homebridge-plugin-govee:
[11/1/2022, 8:23:56 AM] Error: The module '/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/index.js:8:20)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
[11/1/2022, 8:23:56 AM] ====================`

**Comment by SemoTech** [comment]
Happy Thanksgiving! 

Any chance @bwp91 Ben for an update, so the plugin is compatible with Node.JS 18.12.x ?

Thanks.

**Comment by bwp91** [comment]
You too! We don't celebrate this in the UK but I know it's a big day for the US!

The plugin has been compatible with node 18 for quite some time. I have been running successfully on my pi and mac for a number of weeks.

Are you on a raspberry pi for homebridge?

**Comment by SemoTech** [comment]
Hey @bwp91 Ben, gotcha, yeah TG is a big thing in the US. You guys across the pond should celebrate it too :-)  More days off :-)

I am using A Mac Mini with Ubuntu 22.04.1 LTS and latest Docker w/ Homebridge v1.6.0

So strange that it still errors out for me, even after a full remove and re-install.  Here is the latest from the logs:

```
[11/27/2022, 10:05:27 AM] ====================
[11/27/2022, 10:05:27 AM] ERROR LOADING PLUGIN homebridge-plugin-govee:
[11/27/2022, 10:05:27 AM] Error: The module '/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 108. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1243:18)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1061:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/homebridge/node_modules/homebridge-plugin-govee/node_modules/@abandonware/bluetooth-hci-socket/index.js:8:20)
    at Module._compile (node:internal/modules/cjs/loader:1159:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1213:10)
    at Module.load (node:internal/modules/cjs/loader:1037:32)
[11/27/2022, 10:05:27 AM] ====================
 

```

**Comment by bwp91** [comment]
I'm not so familiar with Docker, but are you able to access via a terminal and run some commands?

**Comment by SemoTech** [comment]
Well @bwp91 Ben, I may have found the issue, seems this is not your plugin!  Darn names are too simmilar...

I just saw the issue was already reported for it [HERE ](https://github.com/asednev/homebridge-plugin-govee/issues/78)so I added the logs in the hope they can fix it (re-compile it)...

My mistake and apologies to have bothered you.  Yours works just fine with Node.JS 18.12.x

```
[11/27/2022, 10:29:02 AM] [Govee] Initializing Govee platform...
[11/27/2022, 10:29:02 AM] [Govee] Initialising plugin v7.2.0 | System linux | Node v18.12.1 | HB v1.6.0 | HAPNodeJS v0.11.0...
[11/27/2022, 10:29:02 AM] [Govee] Plugin initialised. Setting up accessories....
[11/27/2022, 10:29:04 AM] [Govee] [LAN] client enabled and found 0 device(s).
[11/27/2022, 10:29:04 AM] [Govee] [HTTP] client enabled and found 4 device(s).
[11/27/2022, 10:29:04 AM] [Govee] [AWS] client enabled.
[11/27/2022, 10:29:05 AM] [Govee] [API] client enabled and found 1 device(s).
[11/27/2022, 10:29:06 AM] [Govee] [BLE] client enabled.
[11/27/2022, 10:29:08 AM] [Govee] ✓ Setup complete. Check out my other Homebridge plugins! https://github.com/bwp91
```

Thanks again for all your efforts.

**Comment by bwp91** [comment]
You shouldn't need this plugin anymore - the functionality has been integrated into my plugin 🙂

**Comment by SemoTech** [comment]
Oh, really?  I did see the line that said
`[11/27/2022, 10:29:06 AM] [Govee] [BLE] client enabled.`
but did not associate it with the other plugin's functionality. 

I was using the other plugin for [THIS](https://www.amazon.com/gp/product/B08C9VYMHY) device and [THIS](https://www.amazon.com/gp/product/B07DWMJKP5) device. 

I should be OK to remove the other plugin?

**Comment by bwp91** [comment]
Do you have your govee username and password in your config?

**Comment by SemoTech** [comment]
> Do you have your govee username and password in your config?

For the other Govee plugin the are no credentials or settings.

For your Govee plugin I have Username, Password and API key.

**Comment by bwp91** [comment]
Since you have the username and password in the config already, i’m surprised these devices haven’t appeared already, unless you have used the config to hide them? 
My plugin uses the same underlying library as the other to discovered these sensors, so for you, everything should be the same.

Before you uninstall the other plugin, just verify that these sensors appear in your homekit as accessories under my plugin too

**Comment by bwp91** [comment]
For some background context about integrating the functionality, see
https://github.com/asednev/homebridge-plugin-govee/issues/69

**Comment by SemoTech** [comment]
Strangely with the other plugin off-line I am not seeing the 2 Govee Bluetooth devices at all in HomeKit.

**Comment by bwp91** [comment]
have you in the past used the plugin config to hide them?

**Comment by SemoTech** [comment]
No, never hid them.  

I did just check and your plugin does see them (lists them under [My Devices]), with the Cloud as "offline" which makes sense.  Strange I do not see them in HomeKit tho...

**Comment by bwp91** [comment]
Ignore the bluetooth enabled: no - this is meant for light devices where it can be enabled or disabled.

Do they appear in the homebridge UI as accessories?

**Comment by SemoTech** [comment]
In the logs I see this for those 2:
```

[11/27/2022, 11:28:40 AM] [Govee] [IT Closet Temp & Hum] has been reported [offline].
[11/27/2022, 11:28:40 AM] [Govee] [IT Closet Temp & Hum] current battery [65%].
[11/27/2022, 11:28:40 AM] [Govee] [IT Closet Temp & Hum] current temperature [29.11°C].
[11/27/2022, 11:28:40 AM] [Govee] [IT Closet Temp & Hum] current humidity [15.89%].
[11/27/2022, 11:28:40 AM] [Govee] [MBA Temp & Humidity] has been reported [offline].
[11/27/2022, 11:28:40 AM] [Govee] [MBA Temp & Humidity] current temperature [26.2°C].
[11/27/2022, 11:28:40 AM] [Govee] [MBA Temp & Humidity] current humidity [39.9%].
```

**Comment by SemoTech** [comment]
> 

OK, I think we are good.  After I removed the other plugin they were placed in a generic room and I just moved them to the corresponding rooms.  They now appear in HomeKit and are showing Temp & Humidity! 

I assume the "offline" status is because they are not in my account since just Bluetooth...?

My sincere thanks!

**Comment by bwp91** [comment]
You can set the bluetooth scan frequency in the plugin settings. I would just try to confirm that the value that homekit shows is indeed the real current value (rather than a cached value from the last time the data was uploaded to the cloud).

Yes the offline status was introduced when the plugin just used the official API with a number of light models. This status does not really apply to devices that aren't supported by the official API. I could consider removing it now.
As aside from the official API, this plugin supports way more models through the AWS, HTTP and BLE connection types.

**Comment by SemoTech** [comment]
YES, I have confirmed visually that the readings match for both units. They seem to be working just fine.

You did amazing work.

The BLE Refresh interval in settings is set to 300s (5 minutes).  Setting it lower (checking more often) would drain the batteries of the units faster I assume?

**Comment by SemoTech** [comment]
And one final question @bwp91 Ben, in the logs the temperatures from both my Bluetooth units are reported in C, any way to get them to be reported in F, same as they are in HomeKit?  I saw no settings for this...

Thank you.

**Comment by bwp91** [comment]
Can you update to the beta version? and confirm whether it also logs in F now? should log both C and F now. is this okay?

**Comment by SemoTech** [comment]
Thanks @bwp91 Ben, I updated to the latest version (7.4.0) and now getting both C and F in the logs:

`[12/2/2022, 8:51:33 AM] [Govee] [MBA Temp & Humidity] current temperature [26.2°C / 79.2°F].`
