### ISSUE TITLE
⚠️ 29-Nov Govee AWS Issue

### ISSUE THREAD

**Issue by bwp91** [bwp91/homebridge-govee#367]
There seems to be an issue with regards to the AWS connection the plugin makes.

Example logs:

Generally and when restarting
```
[29/11/2022, 18:22:52] [Govee] [Device] [AWS-D] close event.
[29/11/2022, 18:22:52] [Govee] [Device] [AWS] close event.
```

When controlling a device
```
[29/11/2022, 18:22:52] [Govee] [Device] not using AWS connection as not connected to AWS
[29/11/2022, 18:22:52] [Govee] [Device]  could not be updated as no connection method available at...
```

I believe this is a Govee connection issue as this has started with no changes to the plugin. However I am also aware the Govee app is still working. So will monitor this for now.

**Comment by CadLiara** [comment]
Indeed I am seeing this same issue. As of now, my Govee tower fans have ceased to respond to commands via voice command/homekit (although showing as though they are functional and executing commands properly in homekit.) Many of the other devices are extremely slow to respond. (with logs indicating "slow to respond.")

I updated from 7.1.9 to 7.2 thinking it may be a plugin issue before seeing this thread. No change obviously.

**Comment by Tw34km3** [comment]
Can confirm, I did some testing reverting to older versions of the plugin as well and still have the same issue.

**Comment by wolf39us** [comment]
I too am seeing the same connection errors. 

I can turn the device on and off but my scenes aren’t working anymore

**Comment by CadLiara** [comment]
> I too am seeing the same connection errors.
> 
> I can turn the device on and off but my scenes aren’t working anymore

Are you also seeing a MASSIVE slowdown in the response time between command and action on devices? My scenes don't work but the slowdown is what is really making me want to flip tables. 

@bwp91 any insights on what Govee/AWS may have buggered up here?

**Comment by wolf39us** [comment]
Yes.  The response time has increased significantly.

**Comment by xcv58** [comment]
I have the same issue. I tried to use the API key and it works:
https://github.com/bwp91/homebridge-govee/wiki/Configuration#obtaining-your-api-key

**Comment by rsaucedo23** [comment]
I have the same issue. I updated API, and the lights seem to work a bit better, but still get the same error in the logs.

**Comment by CadLiara** [comment]
I tried going full LAN/API by deleting email/pw from config but the only thing different was the language of the error codes I got in the logs (back to the ol "_The write handler for the characteristic 'On' on the accessory 'Main Hallway 4' didn't respond at all!. Please check that you properly call the callback!"_"
Other than that, lights seem to be just as slow and fans/humidifier/purifier all have ceased to respond at all. I can see the power state change in the logs, but the device doesn't turn on/off at all.

**Comment by wolf39us** [comment]
Just checked logs this morning and basically this is all I get

```[30/11/2022, 12:51:30] [Govee] [AWS] close event.
[30/11/2022, 12:51:31] [Govee] [DreamView T1 Pro] [AWS-D] reconnect event.
[30/11/2022, 12:51:32] [Govee] [DreamView T1 Pro] [AWS-D] close event.
[30/11/2022, 12:51:34] [Govee] [AWS] reconnect event.
[30/11/2022, 12:51:34] [Govee] [AWS] close event.
[30/11/2022, 12:51:36] [Govee] [DreamView T1 Pro] [AWS-D] reconnect event.
[30/11/2022, 12:51:36] [Govee] [DreamView T1 Pro] [AWS-D] close event.
[30/11/2022, 12:51:42] [Govee] [AWS] reconnect event.
[30/11/2022, 12:51:43] [Govee] [AWS] close event.
[30/11/2022, 12:51:44] [Govee] [DreamView T1 Pro] [AWS-D] reconnect event.
[30/11/2022, 12:51:44] [Govee] [DreamView T1 Pro] [AWS-D] close event.```

**Comment by addisonjames** [comment]
Just opened my first Govvee product this morning, installed the plugin, and ran into same issue. (I thought it might have been related to not having a 23-digit Govee Device ID, but couldn't find that ID either way.)

Same AWS results in my logs as others posted here.

**Comment by CadLiara** [comment]
> Just opened my first Govvee product this morning, installed the plugin, and ran into same issue. (I thought it might have been related to not having a 23-digit Govee Device ID, but couldn't find that ID either way.)
> 
> Same AWS results in my logs as others posted here.

For what it is worth, if all else fails in getting device ID, I have found using the Eve app (discovered when setting up scenes/modes for this plugin) also has the individual device ID's listed when you go into the device in the app. 

And yeah, same AWS results as others. 

This may be a silly question but has anyone here contacted Govee or seen anything from them regarding this? I can imagine with all the folks using Homebridge/HOOBS to integrate Govee this must be irking quire a few folks out there.

**Comment by addisonjames** [comment]
> For what it is worth, if all else fails in getting device ID, I have found using the Eve app (discovered when setting up scenes/modes for this plugin) also has the individual device ID's listed when you go into the device in the app.

Also I just noticed the ID is in the hb plugin settings under 'My Devices'

**Comment by CadLiara** [comment]
For what it is worth, I tried calling Govee. As usual, I got the "all our customer service people are busy but please leave a voicemail" so I did. 

I also posted up on their community forums to see if others are having the same issue and perhaps get someone from Govee to respond. 

https://www.govee.com/posts/117105

**Comment by CadLiara** [comment]
> For what it is worth, I tried calling Govee. As usual, I got the "all our customer service people are busy but please leave a voicemail" so I did.
> 
> I also posted up on their community forums to see if others are having the same issue and perhaps get someone from Govee to respond.
> 
> https://www.govee.com/posts/117105

Sooooooooo in my thread on the Govee community forum Govee actually responded. 

"Hey there, I've checked with the tech team. The Govee API works properly and we do not offer any API for AWS."

@bwp91  any thoughts?

**Comment by wolf39us** [comment]
Next thing you know they’ll be telling us to clear our cookies or try another browser.

**Comment by tommyMX** [comment]
hope you can fix it :-)

**Comment by bwp91** [comment]
Can anyone try the new beta?

**Comment by bwp91** [comment]
> The Govee API works properly and we do not offer any API for AWS

Govee are correct. Their public documented connection methods are their API and LAN mode. And the API has not stopped working. This is why API supported lights are still working albeit much slower. 

Govee does not document their AWS and BLE connection methods and so they have no reason to help with situations like this ticket.

It’s logical for them, that they would want users to use their app rather than via a plugin like this.

**Comment by DarkKent00** [comment]
api limit of 1000 being reached in a matter of minutes. Then it doesn't work any more.

[12/1/2022, 8:52:55 AM] [Govee] Govee API quota limits reached, will try again in 10 minutes...
[12/1/2022, 8:52:55 AM] [Govee] Unfortunately the plugin will not work until fully initialised.

**Comment by rmaes4** [comment]
New beta version working much better for me 👍🏻

**Comment by Tw34km3** [comment]
The beta has restored AWS control!

**Comment by wolf39us** [comment]
All hail the beta!

Scenes are working :-)

**Comment by CadLiara** [comment]
updated to 7.3 and while the AWS error codes are gone, I now get this in the logs on reboot of the bridge: 
12/1/2022, 7:13:43 AMGVEEGoveeWARNING[HTTP] could not use existing access token as does not exist, this is normally not an issue.
12/1/2022, 7:13:43 AMGVEEGovee[HTTP] login successful.
12/1/2022, 7:13:44 AMGVEEGoveeWARNING[HTTP] disabling client as ENOENT: no such file or directory, open '/var/lib/hoobs/gvee/persist/govee.pfx'.
12/1/2022, 7:13:44 AMGVEEGoveeWARNING[AWS] disabling client as requires HTTP client.

Functionally, the response times remain about the same as before. Any thoughts Ben? Do I need to request a new API token?

**Comment by tommyMX** [comment]
How can I install the beta ?

Which command ?

**Comment by bwp91** [comment]
@tommyMX you can update to 7.3.0 now

@CadLiara just realised there is an issue with hoobs - looking into this now

**Comment by bwp91** [comment]
> updated to 7.3 and while the AWS error codes are gone, I now get this in the logs on reboot of the bridge: 12/1/2022, 7:13:43 AMGVEEGoveeWARNING[HTTP] could not use existing access token as does not exist, this is normally not an issue. 12/1/2022, 7:13:43 AMGVEEGovee[HTTP] login successful. 12/1/2022, 7:13:44 AMGVEEGoveeWARNING[HTTP] disabling client as ENOENT: no such file or directory, open '/var/lib/hoobs/gvee/persist/govee.pfx'. 12/1/2022, 7:13:44 AMGVEEGoveeWARNING[AWS] disabling client as requires HTTP client.
> 
> Functionally, the response times remain about the same as before. Any thoughts Ben? Do I need to request a new API token?

@CadLiara can you go into the hoobs terminal and type this command:

```
sudo mkdir /var/lib/hoobs/gvee/persist
```

and then restart?

**Comment by CadLiara** [comment]
> > updated to 7.3 and while the AWS error codes are gone, I now get this in the logs on reboot of the bridge: 12/1/2022, 7:13:43 AMGVEEGoveeWARNING[HTTP] could not use existing access token as does not exist, this is normally not an issue. 12/1/2022, 7:13:43 AMGVEEGovee[HTTP] login successful. 12/1/2022, 7:13:44 AMGVEEGoveeWARNING[HTTP] disabling client as ENOENT: no such file or directory, open '/var/lib/hoobs/gvee/persist/govee.pfx'. 12/1/2022, 7:13:44 AMGVEEGoveeWARNING[AWS] disabling client as requires HTTP client.
> > Functionally, the response times remain about the same as before. Any thoughts Ben? Do I need to request a new API token?
> 
> @CadLiara can you go into the hoobs terminal and type this command:
> 
> ```
> sudo mkdir /var/lib/hoobs/gvee/persist
> ```
> 
> and then restart?

Done. 

That fixed the responsiveness issue and the appliances are back online. 

I am getting the logs flooded with "AWS event" and a TON of "new scene code" messages for every device. (Example for one of them below)

12/1/2022, 8:04:43 AMGVEEGovee[AWS] message event [{"proType":2,"sku":"H6062","device":"F3:74:7C:81:85:A1:AA:DB","softVersion":"1.02.03","wifiSoftVersion":"1.02.09","cmd":"status","type":0,"transaction":"v_1669910682286000","pactType":1,"pactCode":2,"state":{"onOff":1,"brightness":100,"colorTemInKelvin":0,"color":{"r":255,"g":204,"b":204},"mode":21,"result":1},"op":{"command":["qgUVAQAAAAAAAAAAAAAAAAAAALs=","qqUBZP/MzGT/zMxk/8zMZP/MzA4=","qqUCZP/MzGT/zMxk/8zMZP/MzA0=","qqUDZP/MzGT/zMxk/8zMZP/MzAw=","qqUEZP/MzGT/zMxk/8zMZP/MzAs=","qqUFZP/MzGT/zMxk/8zMZP/MzAo=","qhEAHg8PAAAAAAAAAAAAAAAAAKU=","qhL/ZAAAgAoAAAAAAAAAAAAAAKk=","qiP/AAAAgAAAAIAAAACAAAAAgHY=","qkEAORMAAAAAAAAAAAAAAAAAAME="]}}].
12/1/2022, 8:04:43 AMGVEEGovee[Glide] [AWS] receiving update {"source":"AWS","onOff":1,"brightness":100,"colorTemInKelvin":0,"color":{"r":255,"g":204,"b":204},"mode":21,"result":1,"commands":["qgUVAQAAAAAAAAAAAAAAAAAAALs=","qqUBZP/MzGT/zMxk/8zMZP/MzA4=","qqUCZP/MzGT/zMxk/8zMZP/MzA0=","qqUDZP/MzGT/zMxk/8zMZP/MzAw=","qqUEZP/MzGT/zMxk/8zMZP/MzAs=","qqUFZP/MzGT/zMxk/8zMZP/MzAo=","qhEAHg8PAAAAAAAAAAAAAAAAAKU=","qhL/ZAAAgAoAAAAAAAAAAAAAAKk=","qiP/AAAAgAAAAIAAAACAAAAAgHY=","qkEAORMAAAAAAAAAAAAAAAAAAME="]}.
12/1/2022, 8:04:43 AMGVEEGoveeWARNING[Glide] new scene code: [qgUVAQAAAAAAAAAAAAAAAAAAALs=] [aa051501000000000000000000000000000000bb].
12/1/2022, 8:04:43 AMGVEEGoveeWARNING[Glide] new scene code: [qqUBZP/MzGT/zMxk/8zMZP/MzA4=] [aaa50164ffcccc64ffcccc64ffcccc64ffcccc0e].
12/1/2022, 8:04:43 AMGVEEGoveeWARNING[Glide] new scene code: [qqUCZP/MzGT/zMxk/8zMZP/MzA0=] [aaa50264ffcccc64ffcccc64ffcccc64ffcccc0d].
12/1/2022, 8:04:43 AMGVEEGoveeWARNING[Glide] new scene code: [qqUDZP/MzGT/zMxk/8zMZP/MzAw=] [aaa50364ffcccc64ffcccc64ffcccc64ffcccc0c].
12/1/2022, 8:04:43 AMGVEEGoveeWARNING[Glide] new scene code: [qqUEZP/MzGT/zMxk/8zMZP/MzAs=] [aaa50464ffcccc64ffcccc64ffcccc64ffcccc0b].
12/1/2022, 8:04:43 AMGVEEGoveeWARNING[Glide] new scene code: [qqUFZP/MzGT/zMxk/8zMZP/MzAo=] [aaa50564ffcccc64ffcccc64ffcccc64ffcccc0a].
12/1/2022, 8:04:43 AMGVEEGoveeWARNING[Glide] new scene code: [qhEAHg8PAAAAAAAAAAAAAAAAAKU=] [aa11001e0f0f00000000000000000000000000a5].
12/1/2022, 8:04:43 AMGVEEGoveeWARNING[Glide] new scene code: [qhL/ZAAAgAoAAAAAAAAAAAAAAKk=] [aa12ff640000800a0000000000000000000000a9].
12/1/2022, 8:04:43 AMGVEEGoveeWARNING[Glide] new scene code: [qiP/AAAAgAAAAIAAAACAAAAAgHY=] [aa23ff0000008000000080000000800000008076].
12/1/2022, 8:04:43 AMGVEEGoveeWARNING[Glide] new scene code: [qkEAORMAAAAAAAAAAAAAAAAAAME=] [aa410039130000000000000000000000000000c1].

And the video/game mode AWS based scene codes I set up through Eve don't work.

But yeah, pretty huge improvement overall. Thank you Ben :)

**Comment by bwp91** [comment]
This extra logging can be hidden by turning debug mode off.

**Comment by CadLiara** [comment]
> This extra logging can be hidden by turning debug mode off.

Ah yes indeed. lol. 
So nothing to be concerned about?

**Comment by bwp91** [comment]
No, this is normal. These codes help me with implementing new devices and features.

Can you post one of the video mode or game mode codes that you have configured?

**Comment by CadLiara** [comment]
Sure thing.

Video mode codes for:

G1 Pro H604A 
MwUAAEcDAC4AAAAAAAAAAAAAAFw=||ptReal||

Dreamview T1 H6199 
MwUAAAAyADIAAAAAAAAAAAAAADY=,qgUBAAAAAAAAAAAAAAAAAAAAAK4=||ptReal||

Happy to assemble other codes for other modes/devices for you if that helps

**Comment by lakeshow20** [comment]
I am getting this error for my 5083 on the new 7.3.0 update: 

[12/1/2022, 8:06:20 AM] [Govee] [ Lights Mantle] not using AWS connection as this.awsClient.updateDevice is not a function at default.sendDeviceUpdate (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1785:30).
[12/1/2022, 8:06:20 AM] [Govee] [Lights Mantle] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1829:13.

**Comment by bwp91** [comment]
@lakeshow20  can you show logs that appear when restarting the plugin?

**Comment by DebasishBahinipati** [comment]
Same Issue for me as well. I am using homebridge-govee v7.3.0. Below are the logs after the plugin restart.

[12/1/2022, 9:36:24 AM] [Govee] [AWS] client enabled.
[12/1/2022, 9:36:24 AM] [Govee] [HTTP] disabling client as Command failed: openssl pkcs12 -in "/var/lib/homebridge/persist/govee.pfx" -nodes -passin pass:a4121899
Error outputting keys and certificates
4057ADDC537F0000:error:0308010C:digital envelope routines:inner_evp_generic_fetch:unsupported:../crypto/evp/evp_fetch.c:349:Global default library context, Algorithm (RC2-40-CBC : 0), Properties ()
Error outputting keys and certificates.
[12/1/2022, 9:36:24 AM] [Govee] [AWS] disabling client as requires HTTP client.





[12/1/2022, 9:36:26 AM] [Govee] [HTTP] sync failed as this.httpClient.getDevices is not a function at default.goveeHTTPSync (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1201:45).
[12/1/2022, 9:36:26 AM] [Govee] ***** Disabling plugin. *****
[12/1/2022, 9:36:26 AM] [Govee] ***** this.awsClient.connect is not a function at default.pluginSetup (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:712:30). *****






Log While trying to turn on/off the device:
[12/1/2022, 9:31:16 AM] [Govee] [Smart Space Heater 3] current state [on].
[12/1/2022, 9:31:19 AM] [Govee] [Smart Space Heater 3] not using AWS connection as this.awsClient.updateDevice is not a function at default.sendDeviceUpdate (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1785:30).
[12/1/2022, 9:31:21 AM] [Govee] [Smart Space Heater 3] current state [off].
[12/1/2022, 9:31:28 AM] [Govee] [Smart Space Heater 3] not using AWS connection as this.awsClient.updateDevice is not a function at default.sendDeviceUpdate (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1785:30).
[12/1/2022, 9:31:28 AM] [Govee] [Smart Space Heater 3] current light [on].
[12/1/2022, 9:31:29 AM] [Govee] [Smart Space Heater 3] not using AWS connection as this.awsClient.updateDevice is not a function at default.sendDeviceUpdate (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1785:30).



[12/1/2022, 9:42:14 AM] [Govee] [Smart Space Heater 3] not using AWS connection as this.awsClient.updateDevice is not a function at default.sendDeviceUpdate (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1785:30).
[12/1/2022, 9:42:14 AM] [Govee] [Smart Space Heater 3] not using AWS connection as this.awsClient.updateDevice is not a function at default.sendDeviceUpdate (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1785:30).
[12/1/2022, 9:42:14 AM] [Govee] [Smart Space Heater 3] current state [on].
[12/1/2022, 9:42:26 AM] [Govee] [Smart Space Heater 3] not using AWS connection as this.awsClient.updateDevice is not a function at default.sendDeviceUpdate (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1785:30).
[12/1/2022, 9:42:26 AM] [Govee] [Smart Space Heater 3] current state [off].

**Comment by bwp91** [comment]
@lakeshow20 or @DebasishBahinipati 
it would be helpful for me to login to one of your accounts from my homebridge to see what is going on.
if you'd be happy for me to do this, we can message on discord

https://discord.gg/cMGhNtZ3tW

**Comment by DebasishBahinipati** [comment]
> @lakeshow20 or @DebasishBahinipati it would be helpful for me to login to one of your accounts from my homebridge to see what is going on. if you'd be happy for me to do this, we can message on discord
> 
> https://discord.gg/cMGhNtZ3tW

I have provided the details in discord.

**Comment by bwp91** [comment]
@lakeshow20 which platform are you running homebridge on?

**Comment by lakeshow20** [comment]
Sorry for the delay in a response. I can provide access to my homebridge when I am back on my network. I have home bridge on an Unbuntu Linux machine.

**Comment by cherk947** [comment]
Beta seems to be working for me

**Comment by tommyMX** [comment]
I am using 7.3.2.

But get some other errors. I am using Homebridge in a Synology docker.

[12/1/2022, 9:50:19 PM] [Govee] [HTTP] could not use existing access token as does not exist, this is normally not an issue.

[12/1/2022, 9:50:21 PM] [Govee] [HTTP] disabling client as OpenSSL issue - follow instructions at https://devdojo.com/howtoubuntu/how-to-install-openssl-on-ubuntu.

[12/1/2022, 9:50:21 PM] [Govee] [AWS] disabling client as requires HTTP client.

[12/1/2022, 9:50:22 PM] [Govee] [BLE] disabling client as EAFNOSUPPORT, Address family not supported by protocol at default.pluginSetup (file:///homebridge/node_modules/homebridge-govee/lib/platform.js:498:26).

Thank you

**Comment by tommyMX** [comment]
[12/1/2022, 9:57:15 PM] [Govee] ***** Disabling plugin. *****
[12/1/2022, 9:57:15 PM] [Govee] ***** this.awsClient.connect is not a function at default.pluginSetup (file:///homebridge/node_modules/homebridge-govee/lib/platform.js:711:30). *****

**Comment by cherk947** [comment]
7.3.2 no issues.  Trying 7.3.3.

**Comment by bwp91** [comment]
@tommyMX 

can u update to the beta version? 7.3.3-beta.0

https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

**Comment by tommyMX** [comment]
Looks good what I can see in the log:

12/1/2022, 10:16:52 PM] [Govee] [Wand 2] [API] receiving update {"online":true,"powerState":"on","brightness":1,"color":{"r":255,"b":37,"g":206},"source":"API"}.
[12/1/2022, 10:16:53 PM] [Govee] [AWS] message event [{"proType":2,"sku":"H6061","device":"F3:DF:C9:39:32:33:30:31","softVersion":"1.03.03","wifiSoftVersion":"1.02.11","wifiHardVersion":"1.00.10","cmd":"status","type":0,"transaction":"v_1669929412011000","pactType":1,"pactCode":3,"state":{"onOff":0,"brightness":1,"colorTemInKelvin":0,"color":{"r":255,"g":206,"b":37},"mode":21,"result":1},"op":{"command":["qgUVAAAAAAAAAAAAAAAAAAAAALo=","qqUBZP/OJQH/wzFk/7g9Af+tSXY=","qqUCZP+iVQH/lmEB/4ttZP+AeRI=","qqUDAf91hWT/aZIAAAAAAAAAAGI=","qhEAHg8PAAAAAAAAAAAAAAAAAKU=","qhL/ZAAAgAoAAAAAAAAAAAAAAKk=","qiP/AAAAgAAAAIAAAACAAAAAgHY="]}}].
[12/1/2022, 10:16:53 PM] [Govee] [Wand 1] [AWS] receiving update {"source":"AWS","onOff":0,"brightness":1,"colorTemInKelvin":0,"color":{"r":255,"g":206,"b":37},"mode":21,"result":1,"commands":["qgUVAAAAAAAAAAAAAAAAAAAAALo=","qqUBZP/OJQH/wzFk/7g9Af+tSXY=","qqUCZP+iVQH/lmEB/4ttZP+AeRI=","qqUDAf91hWT/aZIAAAAAAAAAAGI=","qhEAHg8PAAAAAAAAAAAAAAAAAKU=","qhL/ZAAAgAoAAAAAAAAAAAAAAKk=","qiP/AAAAgAAAAIAAAACAAAAAgHY="]}.
[12/1/2022, 10:16:53 PM] [Govee] [Wand 1] current brightness [0%].
[12/1/2022, 10:16:53 PM] [Govee] [Wand 1] new scene code: [qgUVAAAAAAAAAAAAAAAAAAAAALo=] [aa051500000000000000000000000000000000ba].
[12/1/2022, 10:16:53 PM] [Govee] [Wand 1] new scene code: [qqUBZP/OJQH/wzFk/7g9Af+tSXY=] [aaa50164ffce2501ffc33164ffb83d01ffad4976].
[12/1/2022, 10:16:53 PM] [Govee] [Wand 1] new scene code: [qqUCZP+iVQH/lmEB/4ttZP+AeRI=] [aaa50264ffa25501ff966101ff8b6d64ff807912].
[12/1/2022, 10:16:53 PM] [Govee] [Wand 1] new scene code: [qqUDAf91hWT/aZIAAAAAAAAAAGI=] [aaa50301ff758564ff6992000000000000000062].
[12/1/2022, 10:16:53 PM] [Govee] [Wand 1] new scene code: [qhEAHg8PAAAAAAAAAAAAAAAAAKU=] [aa11001e0f0f00000000000000000000000000a5].
[12/1/2022, 10:16:53 PM] [Govee] [Wand 1] new scene code: [qhL/ZAAAgAoAAAAAAAAAAAAAAKk=] [aa12ff640000800a0000000000000000000000a9].
[12/1/2022, 10:16:53 PM] [Govee] [Wand 1] new scene code: [qiP/AAAAgAAAAIAAAACAAAAAgHY=] [aa23ff0000008000000080000000800000008076].

Where can I disable the BLE thing? because I have no BT :-)

**Comment by tommyMX** [comment]
> @tommyMX
> 
> can u update to the beta version? 7.3.3-beta.0
> 
> https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

So where can I see the scenes in HB?

**Comment by tommyMX** [comment]
I can't see them :-(
 Will I need BT? I haven't on my Synology .

<img width="915" alt="Bildschirm­foto 2022-12-01 um 22 23 23" src="https://user-images.githubusercontent.com/36209886/205162025-490d47a8-adfd-45b6-b928-746adac62543.png">

**Comment by bwp91** [comment]
@tommyMX 
happy to message on discord, 
https://discord.gg/cMGhNtZ3tW

**Comment by bwp91** [comment]
Sorry guys have had to change how scene codes work in the config! 

Happy to help convert any old scene codes to new ones if needed 👍🏻

**Comment by WBWBW** [comment]
> Sorry guys have had to change how scene codes work in the config!
> 
> Happy to help convert any old scene codes to new ones if needed 👍🏻

Is there an easy way to convert existing codes?

**Comment by bwp91** [comment]
For existing AWS codes, they are base64 strings that need to be converted to hex. You can use a site like this to convert:
https://cryptii.com/pipes/base64-to-hex

For existing BLE codes, there isn't an easy available way, I can provide a new version of these if you have any.

**Comment by WBWBW** [comment]
Thank you! And thanks for fixing it so quickly.

**Comment by CadLiara** [comment]
My hat off to you again Ben. Kudos on seeing this unfold and being on it from the jump. Also being so on top of responses and cranking out updates to solve the issues as they pop up. 
Just updated my scenes and they all work like a charm again. 

Btw, what was the underlying issue that created this entire AWS debacle?

**Comment by bwp91** [comment]
Best get in contact with govee support for an official answer 😆

They seemed to close a method of subscribing to devices via AWS, maybe it was an old method of authentication.

Being careful what I say. But the new method the plugin uses seems to work well and get things back to _almost_ how they were before.

What a week! 😅

**Comment by CadLiara** [comment]
> Best get in contact with govee support for an official answer 😆
> 
> They seemed to close a method of subscribing to devices via AWS, maybe it was an old method of authentication.
> 
> Being careful what I say. But the new method the plugin uses seems to work well and get things back to _almost_ how they were before.
> 
> What a week! 😅

Gotcha. No worries. I don't need to necessarily know "how the sausage is made." Lol. 

As for asking Govee.... yeah, you saw me trying. To date still zip in terms of calling me back and the thread I posted got tier one salesperson boilerplate blow off language. 

Again, thank you for all you do. 

(And to all those reading this, ya  know Ben has a paypal and a patreon. *wink* *wink*) ;)
