### ISSUE TITLE
AWS Connection Error

### ISSUE THREAD

**Issue by Tw34km3** [bwp91/homebridge-govee#368]
### What issue do you have? Please be as thorough and explicit as possible.
Getting a not connected to AWS Error while using the credential auth method. I went to bed with the plugin working fine, and this morning I noticed no lights were working

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X on a raspberry pi. All packages are updated as well as node.js

* Which version of Homebridge/HOOBS do you have?

V1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Raspberry Pi

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

npm 9.1.2

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

All devices, I have a set of twinkly brand christmas lights that are working fine on my homebridge setup. 

### Please paste any relevant logs below.

```

```

**Comment by Tw34km3** [comment]
Log Errors ( They arent showing in the above post )

[29/11/2022, 14:44:34] [Govee] [Living Room Couch] not using AWS connection as not connected to AWS.
[29/11/2022, 14:44:34] [Govee] [Living Room Couch] could not be updated as no connection method available at file:///usr/local/lib/node_modules/homebridge-govee/lib/platform.js:1803:13.
[29/11/2022, 14:44:34] [Govee] [Living Room Couch] not using AWS connection as not connected to AWS.
[29/11/2022, 14:44:39] [Govee] [Living Room Couch] could not be updated as no connection method available at file:///usr/local/lib/node_modules/homebridge-govee/lib/platform.js:1803:13.

**Comment by Tw34km3** [comment]
disregard, I see an issue opened already regarding this. Will monitor that ticket.

**Comment by bwp91** [comment]
Closing, please see https://github.com/bwp91/homebridge-govee/issues/367
