### ISSUE TITLE
Error: This is not private key

### ISSUE THREAD

**Issue by irinacarlier** [bwp91/homebridge-govee#381]
### What issue do you have? Please be as thorough and explicit as possible.
I can not launch the plugin. It seems like there's an encryption problem.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X.

* Which version of Homebridge/HOOBS do you have?
Latest version of both softwares.

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Windows 11 and Node.js v16.16.0.

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v7.4.2. No.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
H6125.

### Please paste any relevant logs below.

```
[05/12/2022, 20:19:17] [Govee] [HTTP] client enabled and found 1 device(s).
[05/12/2022, 20:19:17] [Govee] [AWS] client enabled.
[05/12/2022, 20:19:18] Error: This is not private key
    at Object.detectAndExport (C:\Users\irina\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\node-rsa\src\formats\formats.js:83:31)
    at NodeRSA.module.exports.NodeRSA.exportKey (C:\Users\irina\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\node-rsa\src\NodeRSA.js:201:43)
    at callback (file:///C:/Users/irina/AppData/Roaming/npm/node_modules/homebridge-govee/lib/utils/functions.js:70:28)
    at done (C:\Users\irina\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\@bwp91\pem\webpack:\pem\lib\pem.js:937:1)
    at finalCallback (C:\Users\irina\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\@bwp91\pem\webpack:\pem\lib\pem.js:941:1)
    at deleteSeries (C:\Users\irina\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\@bwp91\pem\webpack:\pem\lib\helper.js:130:1)
    at myCallback (C:\Users\irina\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\@bwp91\pem\webpack:\pem\lib\helper.js:121:1)
    at FSReqCallback.oncomplete (node:fs:188:23)
[05/12/2022, 20:19:18] [HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[05/12/2022, 20:19:23] [HB Supervisor] Restarting Homebridge...
```

**Comment by rcoombz** [comment]
Afternoon - I have the identical error [Icarlier] posted above... 
Running Homebridge 1.6.0 on Windows 11. Node JS 16.16 (64bit)
Plugin: homebridge-govee v7.4.2 (2022-12-04)
Error: This is not private key
[HB Supervisor] Homebridge Process Ended. Code: 1, Signal: null
[HB Supervisor] Restarting Homebridge...

**Comment by bwp91** [comment]
Hmm maybe it’s a windows 11 problem.
If you install the beta version of the plugin does homebridge still continually crash?

**Comment by rcoombz** [comment]
Funny enough, I was trying the beta as I saw your message!  Unfortunately running the beta produces the same error.
It located the devices, then seems to spit up with the "This is not a private key error".  It will then cause Homebridge to crash and loop itself back to the same error.  I'll roll back a few versions but If you need anymore testing please let me know and I'll be happy to provide logs, results, etc...

[12/5/2022, 4:02:24 PM] [Govee] [HTTP] client enabled and found 3 device(s).
[12/5/2022, 4:02:24 PM] [Govee] [AWS] client enabled.
**[12/5/2022, 4:02:24 PM] Error: This is not private key**
    at Object.detectAndExport (C:\Users\Ryan\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\node-rsa\src\formats\formats.js:83:31)
    at NodeRSA.module.exports.NodeRSA.exportKey (C:\Users\Ryan\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\node-rsa\src\NodeRSA.js:201:43)
    at callback (file:///C:/Users/Ryan/AppData/Roaming/npm/node_modules/homebridge-govee/lib/utils/functions.js:70:28)
    at done (C:\Users\Ryan\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\@bwp91\pem\webpack:\pem\lib\pem.js:937:1)
    at finalCallback (C:\Users\Ryan\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\@bwp91\pem\webpack:\pem\lib\pem.js:941:1)
    at deleteSeries (C:\Users\Ryan\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\@bwp91\pem\webpack:\pem\lib\helper.js:130:1)
    at myCallback (C:\Users\Ryan\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\@bwp91\pem\webpack:\pem\lib\helper.js:121:1)
    at FSReqCallback.oncomplete (node:fs:188:23) 
Error: read ECONNRESET
    at TCP.onStreamRead (node:internal/stream_base_commons:217:20)

**Comment by bwp91** [comment]
which beta did you try?

**Comment by rcoombz** [comment]
v2.0.0-beta.0

**Comment by bwp91** [comment]
Ah I mean the beta version of the plugin, not homebridge

**Comment by rcoombz** [comment]
Whoops, that's my fault. (Homebridge-govee v7.4.3-beta.4 ) - Oddly enough, no crash and everything in Homebridge appears to be working.  However my outlets aren't responding to the on/off commands from the Home app but my daughters LED light strip has no issues. : -)

The plugs are Govee Dual Smart Plug, 15A WiFi Bluetooth outlet.  They still work with my Google Home just not with Homebridge using the home app.  Logs from Homebridge even look solid.  I can try to delete them and add them back as your end appears to check out.

12/5/2022, 4:52:43 PM] [Govee] [Ava’s lightstrip] skipping adaptive lighting update as device is off or kelvin is same as before [2900K /349M].
[12/5/2022, 4:52:49 PM] [Govee] [Ava’s lightstrip] [API] receiving update {"online":true,"powerState":"on","brightness":1,"colorTemInKelvin":2900,"colorTem":2900,"source":"API"}.
[12/5/2022, 4:53:19 PM] [Govee] [Ava’s lightstrip] [API] receiving update {"online":true,"powerState":"on","brightness":1,"colorTemInKelvin":2900,"colorTem":2900,"source":"API"}.
[12/5/2022, 4:53:42 PM] [Govee] [Ava’s lightstrip] [API] sending update {"name":"brightness","value":44}.
[12/5/2022, 4:53:42 PM] [Govee] [Ava’s lightstrip] current brightness [44%].
[12/5/2022, 4:53:47 PM] [Govee] [Ava’s lightstrip] [API] sending update {"name":"colorTem","value":3300}.
[12/5/2022, 4:53:47 PM] [Govee] [Ava’s lightstrip] current colour [3300K / 302M] via adaptive lighting.
[12/5/2022, 4:53:49 PM] [Govee] Skipping sync as client is busy sending updates.
[12/5/2022, 4:53:52 PM] [Govee] [Ava’s lightstrip] [API] sending update {"name":"brightness","value":57}.
[12/5/2022, 4:53:52 PM] [Govee] [Ava’s lightstrip] current brightness [57%].
[12/5/2022, 4:53:57 PM] [Govee] [Ava’s lightstrip] [API] sending update {"name":"colorTem","value":3300}.
[12/5/2022, 4:53:59 PM] [Govee] [Dual Smart Plug Spare] [Outlet 1] current state [off].
[12/5/2022, 4:54:02 PM] [Govee] [Ava’s lightstrip] [API] sending update {"name":"brightness","value":57}.
[12/5/2022, 4:54:04 PM] [Govee] [Dual Smart Plug Spare] [Outlet 2] current state [off].
[12/5/2022, 4:54:07 PM] [Govee] [Ava’s lightstrip] [API] sending update {"name":"colorTem","value":4500}.
[12/5/2022, 4:54:07 PM] [Govee] [Ava’s lightstrip] current colour [4500K / 224M] via adaptive lighting.
[12/5/2022, 4:54:12 PM] [Govee] [Ava’s lightstrip] [API] sending update {"name":"colorTem","value":3500}.
[12/5/2022, 4:54:12 PM] [Govee] [Ava’s lightstrip] current colour [3500K / 284M] via adaptive lighting.
[12/5/2022, 4:54:16 PM] [Govee] [Dual Smart Plug Xmas] [Outlet 1] current state [on].
[12/5/2022, 4:54:17 PM] [Govee] [Ava’s lightstrip] [API] sending update {"name":"colorTem","value":3500}.
[12/5/2022, 4:54:19 PM] [Govee] [Ava’s lightstrip] [API] receiving update {"online":true,"powerState":"on","brightness":57,"colorTemInKelvin":3500,"colorTem":3500,"source":"API"}.
[12/5/2022, 4:54:20 PM] [Govee] [Dual Smart Plug Xmas] [Outlet 2] current state [on].
[12/5/2022, 4:54:43 PM] [Govee] [Ava’s lightstrip] skipping adaptive lighting update as device is off or kelvin is same as before [3500K /284M].
[12/5/2022, 4:54:49 PM] [Govee] [Ava’s lightstrip] [API] receiving update {"online":true,"powerState":"on","brightness":57,"colorTemInKelvin":3500,"colorTem":3500,"source":"API"}.
[12/5/2022, 4:54:49 PM] [Govee] [Dual Smart Plug Xmas] [Outlet 1] current state [off].
[12/5/2022, 4:54:52 PM] [Govee] [Dual Smart Plug Xmas] [Outlet 2] current state [off].

**Comment by rcoombz** [comment]
I'm heading out for a B-day party but thanks for reaching out and I can provide any additional info later tonight.  This quick response and help will defn get a donation.  Appreciate it very much!

**Comment by bwp91** [comment]
this should be fixed in latest version :)
