### ISSUE TITLE
openssl error for lan devices

### ISSUE THREAD

**Issue by tdporter** [bwp91/homebridge-govee#386]
### What issue do you have? Please be as thorough and explicit as possible.
plugin is failing to load, error:
[12/12/2022, 9:53:30 AM] [Govee] [HTTP] disabling client as Could not find openssl on your system on this path: openssl at /homebridge/node_modules/homebridge-govee/node_modules/@bwp91/pem/webpack:/pem/lib/openssl.js:257:1.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

Homebridge UI-X

* Which version of Homebridge/HOOBS do you have?

Homebridge v1.6.0

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Docker

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
7.5.1 - It was working, but not sure of the previous version when it was.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Govee WiFi Thermometer Hygrometer H5179 - 3 of them

### Please paste any relevant logs below.

```[12/12/2022, 10:10:16 AM] [Govee] [HTTP] disabling client as Could not find openssl on your system on this path: openssl at /homebridge/node_modules/homebridge-govee/node_modules/@bwp91/pem/webpack:/pem/lib/openssl.js:257:1.


```

**Comment by tdporter** [comment]
Nevermind, simple fix.   Installed openssl via apk add openssl.  Working again.
