### ISSUE TITLE
Cannot change modes on H7122/H7160 (air purifier/humidifier)

### ISSUE THREAD

**Issue by jmateocodes** [bwp91/homebridge-govee#397]
### What issue do you have? Please be as thorough and explicit as possible.
`Devices only turn on and off. Upgraded to beta v7.6.1, issues remain the same.`
`Air Purifier H7122 - Cannot change modes or speed.`
`Humidifier H7160 - Can only toggle custom mode. Cannot change to other modes or speeds.`

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
`Homebridge UI-X`
`Homebridge CLI`

* Which version of Homebridge/HOOBS do you have?
`Homebridge v1.6.0`

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
`Raspberry Pi Zero W`
`Node v18.12.1`
`NPM v8.19.2`

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
`homebridge-govee v7.6.1-beta.1` `(bug is present on the stable version)`

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
`H7122 - Humidifier`
`H7160 - Air Purifier`

### Please paste any relevant logs below.

**Humidifier H7160**
```
[21/12/2022, 10:27:33] [Govee] [AWS] message event [{"proType":2,"sku":"H7160","device":"15:D1:D4:AD:FC:5C:45:0C","softVersion":"1.00.13","wifiSoftVersion":"1.00.13","cmd":"status","type":0,"transaction":"v_1671636453140000","pactType":1,"pactCode":1,"state":{"onOff":0,"result":1},"op":{"command":["qhICAAAAAAAAAAAAAAAAAAAAALo=","qhMAAQAAgAMAAAAAAAAAAAAAADs=","qhMBAAoegAAAAAAAAAAAAAAAACw=","qhEAAAAAAAAAAAAAAAAAAAAAALs=","qgUDvAAAAAAAAAAAAAAAAAAAABA=","qgUCEQEAPAA8AQA8ADwB/////70=","qgUBBQAAAAAAAAAAAAAAAAAAAKs=","qgUAA7wAAAAAAAAAAAAAAAAAABA=","qhYA/////wAAAAAAAAAAAAAAALw=","qhsAZOjo/wAAAAAAAAAAAAAAACo=","qghXTDMyOc8AAAAAAAAAAAAAAE4=","qhABAvNuAAAAAAAAAAAAAAAAACQ=","qhcAAAAAAAAAAAAAAAAAAAAAAL0="]}}].
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] [AWS] receiving update {"source":"AWS","onOff":0,"result":1,"op":{"command":["qhICAAAAAAAAAAAAAAAAAAAAALo=","qhMAAQAAgAMAAAAAAAAAAAAAADs=","qhMBAAoegAAAAAAAAAAAAAAAACw=","qhEAAAAAAAAAAAAAAAAAAAAAALs=","qgUDvAAAAAAAAAAAAAAAAAAAABA=","qgUCEQEAPAA8AQA8ADwB/////70=","qgUBBQAAAAAAAAAAAAAAAAAAAKs=","qgUAA7wAAAAAAAAAAAAAAAAAABA=","qhYA/////wAAAAAAAAAAAAAAALw=","qhsAZOjo/wAAAAAAAAAAAAAAACo=","qghXTDMyOc8AAAAAAAAAAAAAAE4=","qhABAvNuAAAAAAAAAAAAAAAAACQ=","qhcAAAAAAAAAAAAAAAAAAAAAAL0="]}}.
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] new scene code: [qhICAAAAAAAAAAAAAAAAAAAAALo=] [aa120200000000000000000000000000000000ba].
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] new scene code: [qhMAAQAAgAMAAAAAAAAAAAAAADs=] [aa1300010000800300000000000000000000003b].
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] new scene code: [qhMBAAoegAAAAAAAAAAAAAAAACw=] [aa1301000a1e800000000000000000000000002c].
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] new scene code: [qhEAAAAAAAAAAAAAAAAAAAAAALs=] [aa110000000000000000000000000000000000bb].
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] new scene code: [qgUDvAAAAAAAAAAAAAAAAAAAABA=] [aa0503bc00000000000000000000000000000010].
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] new scene code: [qgUCEQEAPAA8AQA8ADwB/////70=] [aa05021101003c003c01003c003c01ffffffffbd].
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] new scene code: [qgUBBQAAAAAAAAAAAAAAAAAAAKs=] [aa050105000000000000000000000000000000ab].
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] new scene code: [qgUAA7wAAAAAAAAAAAAAAAAAABA=] [aa050003bc000000000000000000000000000010].
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] new scene code: [qhYA/////wAAAAAAAAAAAAAAALw=] [aa1600ffffffff000000000000000000000000bc].
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] new scene code: [qhsAZOjo/wAAAAAAAAAAAAAAACo=] [aa1b0064e8e8ff0000000000000000000000002a].
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] new scene code: [qghXTDMyOc8AAAAAAAAAAAAAAE4=] [aa08574c333239cf00000000000000000000004e].
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] new scene code: [qhABAvNuAAAAAAAAAAAAAAAAACQ=] [aa100102f36e0000000000000000000000000024].
[21/12/2022, 10:27:33] [Govee] [Jo’s Humidifier] new scene code: [qhcAAAAAAAAAAAAAAAAAAAAAAL0=] [aa170000000000000000000000000000000000bd].

```

**Air Purifier H7122**
```
[21/12/2022, 10:28:33] [Govee] [AWS] message event [{"proType":2,"sku":"H7122","device":"46:84:D4:AD:FC:04:61:A4","softVersion":"1.00.19","wifiSoftVersion":"1.00.19","cmd":"status","type":0,"transaction":"v_1671636513145000","pactType":1,"pactCode":1,"state":{"onOff":0,"result":1},"op":{"command":["qhIBAAAAAAAAAAAAAAAAAAAAALk=","qhMAgRUAAAAAAAAAAAAAAAAAAC0=","qhEAAAAAAAAAAAAAAAAAAAAAALs=","qgUDAAAAAAAAAAAAAAAAAAAAAKw=","qhAAAAAAAAAAAAAAAAAAAAAAALo=","qhwBAAIAAAAAAAAAAAAAAAAAALU=","qhYA/////wAAAAAAAAAAAAAAALw=","qhkAAAAAAAAAAAAAAAAAAAAAALM="]}}].
[21/12/2022, 10:28:33] [Govee] [Jo’s Air Purifier] [AWS] receiving update {"source":"AWS","onOff":0,"result":1,"op":{"command":["qhIBAAAAAAAAAAAAAAAAAAAAALk=","qhMAgRUAAAAAAAAAAAAAAAAAAC0=","qhEAAAAAAAAAAAAAAAAAAAAAALs=","qgUDAAAAAAAAAAAAAAAAAAAAAKw=","qhAAAAAAAAAAAAAAAAAAAAAAALo=","qhwBAAIAAAAAAAAAAAAAAAAAALU=","qhYA/////wAAAAAAAAAAAAAAALw=","qhkAAAAAAAAAAAAAAAAAAAAAALM="]}}.
[21/12/2022, 10:28:33] [Govee] [Jo’s Air Purifier] new scene code: [qhIBAAAAAAAAAAAAAAAAAAAAALk=] [aa120100000000000000000000000000000000b9].
[21/12/2022, 10:28:33] [Govee] [Jo’s Air Purifier] new scene code: [qhMAgRUAAAAAAAAAAAAAAAAAAC0=] [aa1300811500000000000000000000000000002d].
[21/12/2022, 10:28:33] [Govee] [Jo’s Air Purifier] new scene code: [qhEAAAAAAAAAAAAAAAAAAAAAALs=] [aa110000000000000000000000000000000000bb].
[21/12/2022, 10:28:33] [Govee] [Jo’s Air Purifier] new scene code: [qgUDAAAAAAAAAAAAAAAAAAAAAKw=] [aa050300000000000000000000000000000000ac].
[21/12/2022, 10:28:33] [Govee] [Jo’s Air Purifier] new scene code: [qhAAAAAAAAAAAAAAAAAAAAAAALo=] [aa100000000000000000000000000000000000ba].
[21/12/2022, 10:28:33] [Govee] [Jo’s Air Purifier] new scene code: [qhwBAAIAAAAAAAAAAAAAAAAAALU=] [aa1c0100020000000000000000000000000000b5].
[21/12/2022, 10:28:33] [Govee] [Jo’s Air Purifier] new scene code: [qhYA/////wAAAAAAAAAAAAAAALw=] [aa1600ffffffff000000000000000000000000bc].
[21/12/2022, 10:28:33] [Govee] [Jo’s Air Purifier] new scene code: [qhkAAAAAAAAAAAAAAAAAAAAAALM=] [aa190000000000000000000000000000000000b3].
```

**Comment by bwp91** [comment]
Hi @jmateocodes 

Humidifier and air purifier devices are still a bit of a work in progress, I am planning to get round to them at some point!

**Comment by bwp91** [comment]
Hi @jmateocodes 

these devices should be more functional in the latest version of the plugin

**Comment by TheAlphaLaw** [comment]
@bwp91 

I have no control over this same device. It shows up in devices but then shows unknown status or an incorrect status. It shows that "AWS" is supported by disabled.

I see errors such as (when attempting to control unit): 

`[4/28/2023, 2:14:23 PM] [Govee] [Living Room Purifier] could not be updated as no connection method available at file:///C:/Users/...../AppData/Roaming/npm/node_modules/homebridge-govee/lib/platform.js:1721:13.`

**Comment by bwp91** [comment]
@TheAlphaLaw 
if aws is supported but disabled, please restart the plugin and check the startup logs. there will be an explanation why aws is being disabled

**Comment by TheAlphaLaw** [comment]
> @TheAlphaLaw if aws is supported but disabled, please restart the plugin and check the startup logs. there will be an explanation why aws is being disabled

Here is the relevant error displayed:

```
[4/30/2023, 5:45:38 PM] [Govee] [HTTP] disabling client as Could not find openssl on your system on this path: openssl at C:\Users\SERVER\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\pem\webpack:\pem\lib\openssl.js:258:1.
[4/30/2023, 5:45:38 PM] [Govee] See https://github.com/bwp91/homebridge-govee/wiki/OpenSSL for more info about installing OpenSSL
```

There Git page provided above is empty, but is OpenSSL required?

**Comment by bwp91** [comment]
@TheAlphaLaw yes it is absolutely required, unfortunately for windows i think the steps are a little more involved, but a helpful post from another user is here:

https://github.com/bwp91/homebridge-govee/issues/405#issuecomment-1513506027

The wiki page i need to sort out 😅

**Comment by TheAlphaLaw** [comment]
> @TheAlphaLaw yes it is absolutely required, unfortunately for windows i think the steps are a little more involved, but a helpful post from another user is here:
> 
> [#405 (comment)](https://github.com/bwp91/homebridge-govee/issues/405#issuecomment-1513506027)
> 
> The wiki page i need to sort out 😅

Bummer, on the bright side I was able to connect these directly to Home Assistant via ESP32. Much better solution than AWS I think, since it remains local over BT. Th

**Comment by TheAlphaLaw** [comment]
@bwp91 

Working great on Homebridge, unfortunately when pulled into Home Assistant it has no entity to use. I wonder if there is a way to force HA to read it as a fan, which would work great. I open a ticket an issue on their end.
