### ISSUE TITLE
Lastest update breaks H5179 Thermostat (v7.2.0 last working version)

### ISSUE THREAD

**Issue by tanjello** [bwp91/homebridge-govee#424]
Hello, 

7.2.0 works very well with the thermostat but the latest one seems to break it. 

Version: 7.8.0(Broken)

[1/17/2023, 12:59:42 PM] [Govee] [LAN] client enabled and found 0 device(s).
[1/17/2023, 12:59:42 PM] [Govee] [HTTP] client enabled and found 1 device(s).
[1/17/2023, 12:59:42 PM] [Govee] [HTTP] disabling client as Could not find openssl on your system on this path: openssl at C:\Users\...\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\@bwp91\pem\webpack:\pem\lib\openssl.js:257:1.
[1/17/2023, 12:59:42 PM] [Govee] [AWS] disabling client as requires HTTP client.
[1/17/2023, 12:59:42 PM] [Govee] [API] disabling client as API key not provided.
[1/17/2023, 12:59:43 PM] [Govee] [BLE] disabling client as LIBUSB_ERROR_NOT_SUPPORTED at Device.usb.Device.open (C:\Users\...\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\usb\usb.js:40:7).
[1/17/2023, 12:59:43 PM] [Govee] [Room] initialising with options {"lowBattThreshold":20}.
[1/17/2023, 12:59:43 PM] [Govee] [Room] initialised with id [14:90:1B:7D:D8:D3:A4:DC] [H5179].
[1/17/2023, 12:59:43 PM] [Govee] [BLE] sync for thermo-hygrometer sensors disabled as required hardware/packages not available.

Version 7.2.0 (Works)

[1/17/2023, 1:04:43 PM] [Govee] [LAN] client enabled and found 0 device(s).
[1/17/2023, 1:04:43 PM] [Govee] [HTTP] could not use existing access token as does not exist, this is normally not an issue.
[1/17/2023, 1:04:44 PM] [Govee] [HTTP] client enabled and found 1 device(s).
[1/17/2023, 1:04:44 PM] [Govee] [AWS] client enabled.
[1/17/2023, 1:04:44 PM] [Govee] [API] disabling client as API key not provided.
[1/17/2023, 1:04:44 PM] [Govee] [BLE] disabling client as LIBUSB_ERROR_NOT_SUPPORTED at Device.usb.Device.open (C:\Users\...\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\usb\usb.js:40:7).
[1/17/2023, 1:04:44 PM] [Govee] [Room] initialising with options {"lowBattThreshold":20}.
[1/17/2023, 1:04:44 PM] [Govee] [Room] initialised with id [14:90:1B:7D:D8:D3:A4:DC] [H5179].
[1/17/2023, 1:04:44 PM] [Govee] [BLE] sync for thermo-hygrometer sensors disabled as required hardware/packages not available.
[1/17/2023, 1:04:44 PM] [Govee] [ Room] has been reported [online].
[1/17/2023, 1:04:44 PM] [Govee] [Room] current battery [71%].
[1/17/2023, 1:04:44 PM] [Govee] [Room] current temperature [20°C].
[1/17/2023, 1:04:44 PM] [Govee] [Room] current humidity [51.6%].

Any thoughts? I have tried adding the API key, updating, delete and re-adding with no luck.

**Comment by tannis00** [comment]
I'm having the same issue. This is the only Govee device I have, and it isn't supported by any plugin I've tried. At least this one recognizes the device. 

I've tried multiple versions, but unfortunately version 7.2.0 doesn't show up in the version list.

I did try installing OpenSSL, and the error message changed, but it still doesn't work:

[4/17/2023, 10:46:37 a.m.] [Govee] [LAN] client enabled and found 0 device(s).
[4/17/2023, 10:46:37 a.m.] [Govee] [HTTP] client enabled and found 2 device(s).
[4/17/2023, 10:46:37 a.m.] [Govee] [HTTP] disabling client as Invalid openssl exit code: 1
% openssl pkcs12 -in C:\WINDOWS\TEMP\8aa788734563d5762d0ef6eb04a172a48954ed55 -passin file:C:\WINDOWS\TEMP\ef9c0fdb017d2d39d184b9a8e27f3326bc0b3b63 -legacy -traditional -nodes
pkcs12: unable to load provider legacy
Hint: use -provider-path option or OPENSSL_MODULES environment variable.
343B0000:error:12800067:DSO support routines:win32_load:could not load the shared library:crypto\dso\dso_win32.c:108:filename(C:\Program Files\OpenSSL\lib\ossl-modules\legacy.dll)
343B0000:error:12800067:DSO support routines:DSO_load:could not load the shared library:crypto\dso\dso_lib.c:152:
343B0000:error:07880025:common libcrypto routines:provider_init:reason(524325):crypto\provider_core.c:904:name=legacy
% openssl pkcs12 -in C:\WINDOWS\TEMP\8aa788734563d5762d0ef6eb04a172a48954ed55 -passin file:C:\WINDOWS\TEMP\ef9c0fdb017d2d39d184b9a8e27f3326bc0b3b63 -legacy -traditional -nodes.
[4/17/2023, 10:46:37 a.m.] [Govee] [AWS] disabling client as requires HTTP client.

**Comment by bwp91** [comment]
@tannis00 
can you try uninstalling any openssl version you have, then install openssl v1.1 rather than v3
and also refer to this comment 
https://github.com/bwp91/homebridge-govee/issues/405#issuecomment-1368269873
to see if you have any success?

**Comment by tanjello** [comment]
Since everyone just says installing OpenSSL worked for me but doesn't actually tell you how to do it, here you go.

https://public.cloud.myinfo.gov.sg/docs/OpenSSL_installation_guide.pdf

Once you're done I don't care what the directions say REBOOT YO MACHINE!

After 2 months I finally got it working.

Cliff notes:

Once the installation completed:

Set Environment Variables:
a. Open System Properties > Advanced > Environment Variables
b. Under System variables, click New then input the following as shown in the
screenshot
Variable name: OPENSSL_CONF
Variable value: Destination location/folder (from #Step2) + \bin\openssl.cfg
(e.g. C:\Program Files\OpenSSL-Win64\bin\openssl.cfg)
P/s: The variable value is the Path to the OpenSSL program stored on your local computer.
It may differ from the screenshot above.
Set Path Variable:
a. Open System Properties > Advanced > Environment Variables
b. Under System variables, select Path from the list then click Edit. (You should come
to a pop-up window with a list of directory paths)
c. Click New and input the directory path to the OpenSSL bin folder. An example is
shown in the screenshot below.
P/s: Your Path may differ from the screenshot above

**Comment by tanjello** [comment]
@tannis00, see my comment below #405

**Comment by tannis00** [comment]
I actually managed to install version 7.2.0, and it's working perfectly now. Is there a compelling reason to upgrade to a newer version?

**Comment by tanjello** [comment]
@tannis00, Personally I decided to get it working since I am sure at some point it will be unusable and deprecated. It was actually super easy once I spent the time to get it installed and configured. Only needed 3 steps. Might try and give it a twirl to see if you can get it working. Takes about 5mins.
