### ISSUE TITLE
H6171 outdoor light strip not responding in Homekit. I'm using v7.9.0 on homebridge-config-ui-x v4.50.2

### ISSUE THREAD

**Issue by mlbarber1645** [bwp91/homebridge-govee#428]
### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

* Which version of Homebridge/HOOBS do you have?

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

### Please paste any relevant logs below.

```

```

**Comment by mlbarber1645** [comment]
System info
<html>
<body>


Timezone | GMT-0600
-- | --
Raspbian GNU/Linux Bullseye (11)
homebridge
192.168.1.40
fd34:a608:de57:42cd:22b6:d77e:8322:2a80
v18.12.1
pi
/var/lib/homebridge
/var/lib/homebridge/config.json
/var/lib/homebridge/node_modules
Yes


</body>
</html>Timezone	GMT-0600
OS	Raspbian GNU/Linux Bullseye (11)
Hostname	homebridge
IPv4 (eth0)	192.168.1.40
IPv6 (eth0)	fd34:a608:de57:42cd:22b6:d77e:8322:2a80
Node.js Version	[v18.12.1](https://homebridge.io/w/JTKEF)
User	pi
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
Plugin Path	/var/lib/homebridge/node_modules
Service Mode	Yes

**Comment by bwp91** [comment]
Hi @mlbarber1645 

could do with knowing a bit more about what’s happening right now, as “not responding” could be due to so many different things.

Can you post logs from the plugin starting?

Do the accessories appear in the homebridge ui? and can you control from there?

Do the accessories appear in the home app? if you try to control from there, does anything appear in the homebridge log?

thanks!

**Comment by mlbarber1645** [comment]
Logs as follows:
[22/01/2023, 09:17:05] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge BD8A) is running on port 51824.
[22/01/2023, 09:17:07] [Govee] [LAN] client enabled and found 0 device(s).
[22/01/2023, 09:17:12] [Govee] [HTTP] client enabled and found 1 device(s).
[22/01/2023, 09:17:16] [Govee] [AWS] client enabled.
[22/01/2023, 09:17:17] [Govee] [API] client enabled and found 0 device(s).
[22/01/2023, 09:17:18] [Govee] [BLE] client enabled.
[22/01/2023, 09:17:18] [Govee] [Outdoor Strip Lights] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[22/01/2023, 09:17:18] [Govee] [Outdoor Strip Lights] initialised with id [89:CE:32:37:35:39:22:FF] [H6171].
[22/01/2023, 09:17:20] [Govee] ✓ Setup complete. Check out my other Homebridge plugins! https://github.com/bwp91
[22/01/2023, 09:20:03] [Govee] [Outdoor Strip Lights] could not find device [32:37:35:39:22:ff].
[22/01/2023, 09:20:03] [Govee] [Outdoor Strip Lights] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1869:13.
[22/01/2023, 09:20:10] [Govee] [Outdoor Strip Lights] could not find device [32:37:35:39:22:ff].
[22/01/2023, 09:20:10] [Govee] [Outdoor Strip Lights] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1869:13.
[22/01/2023, 09:20:17] [Govee] [Outdoor Strip Lights] could not find device [32:37:35:39:22:ff].
[22/01/2023, 09:20:17] [Govee] [Outdoor Strip Lights] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1869:13.
[22/01/2023, 09:20:24] [Govee] [Outdoor Strip Lights] could not find device [32:37:35:39:22:ff].
[22/01/2023, 09:20:24] [Govee] [Outdoor Strip Lights] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1869:13.

Accessory appears in Homebridge IU, but can't be controlled
Accessory appears in Home as off. Trying to control changes it to no reponse.
