### ISSUE TITLE
H6147 Appears in Homebridge but Doesn't Actually Work

### ISSUE THREAD

**Issue by daviddigregorio** [bwp91/homebridge-govee#433]
I have  a couple Govee products that work fine with the plugin (v 7.9.0), but just added a H6147 lightstrip that is having an issue. The light strip shows up in Homekit no problem, and says it's off. But when I try to turn on, it spins for awhile and then says "No Response". Eventually the no-response state reverts back to just being Off. But it never can turn on (or off if I turn it on manually). Running Homebridge (v 1.6.0) on a dedicated Pi with no other issues and over 100 devices. 

[1/23/2023, 1:29:16 PM] [Govee] [Game Room] could not connect as Error: Peripheral already connected.
[1/23/2023, 1:29:23 PM] [Govee] [Game Room] could not find device [d4:ad:fc:bf:16:80].
[1/23/2023, 1:29:23 PM] [Govee] [Game Room] could not be updated as no connection method available at file:///usr/lib/node_modules/homebridge-govee/lib/platform.js:1872:13.
[1/23/2023, 1:29:23 PM] [Govee] [Game Room] could not connect as Error: Peripheral already connected.
[1/23/2023, 1:29:30 PM] [Govee] [Game Room] could not find device [d4:ad:fc:bf:16:80].
[1/23/2023, 1:29:30 PM] [Govee] [Game Room] could not be updated as no connection method available at file:///usr/lib/node_modules/homebridge-govee/lib/platform.js:1872:13.
[1/23/2023, 1:29:30 PM] [Govee] [Game Room] could not connect as Error: Peripheral already connected.
[1/23/2023, 1:29:37 PM] [Govee] [Game Room] could not find device [d4:ad:fc:bf:16:80].
[1/23/2023, 1:29:37 PM] [Govee] [Game Room] could not be updated as no connection method available at file:///usr/lib/node_modules/homebridge-govee/lib/platform.js:1872:13.

**Comment by farhandsome** [comment]
Was there a resolution for this? I'm seeing the same thing.

**Comment by bwp91** [comment]
Is the H6147 bluetooth only?

**Comment by farhandsome** [comment]
> Is the H6147 bluetooth only?

Not sure about the H6147 but I’m getting this error on the H6053 which is BLE only.

**Comment by bwp91** [comment]
@farhandsome can you update to the beta version of the plugin? `10.15.1-beta.0`

In fact just yesterday I was changing some code to try and make the Bluetooth a bit more stable.

Can you see if this makes a difference at all?

**Comment by farhandsome** [comment]
@bwp91 

![image](https://github.com/user-attachments/assets/72c31863-8e29-4e69-82ba-a207091e3c56)

Hmm, I'm not seeing that version in the plugin window. Am I needing to update?

**Comment by bwp91** [comment]
Sorry - you should see `10.15.1-beta.1` soon

**Comment by farhandsome** [comment]
@bwp91 

`[12/12/2024, 19:48:28] [Govee] [RGBHanMonitor] could not be updated as Promise timed out after 10000 milliseconds at file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:76:24.
[12/12/2024, 19:48:38] [Govee] [RGBHanMonitor] could not be updated as Promise timed out after 10000 milliseconds at file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:76:24.
[12/12/2024, 19:48:39] [Govee] [RGBHanMonitor] starting BLE update with params [{"cmd":1,"data":0}].
[12/12/2024, 19:48:39] [Govee] [RGBHanMonitor] attempting connection with device.
[12/12/2024, 19:48:49] [Govee] [RGBHanMonitor] could not be updated as Promise timed out after 10000 milliseconds at file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:76:24.`

Hey so I just did install the beta and now this is the error I get.
