### ISSUE TITLE
Old sensor names showing up in plugin config and logs

### ISSUE THREAD

**Issue by joshjohanning** [bwp91/homebridge-govee#456]
### What issue do you have? Please be as thorough and explicit as possible.

I have some Govee water sensors (H5054) and the originally had the name of `Humidifier left` / `humidifier right`.  At some point I renamed them to `Humidifier` and `Kitchen Sink`.  It doesn't seem like this plugin picks up their new name.  

I've updated the display name in HomeBridge and in HomeKit so from a UX perspective it's correct, but I was doing some debugging in the logs the other day and the fact that it's referring to its old names was confusing.  

The old names show up in the plugin config under Devices, too.

Is it possible to resolve this to get it to grab the updated names? If I deleted the govee HomeBridge plugin and reconfigured, would it then pick up the new names from fresh, or is it a Govee server/API issue?

The particular note in the logs that caught my eye to this is that it still calls it `Humidifier left` and `Humidifier right`, but in the logs, I sometimes see this - which is weird because according to the plugin's logs, I don't have a device named `Humidifier` or `Kitchen Sink` (because it hasn't captured the new names):

```
[20/02/2023, 09:30:32] [Govee] [Humidifier] could not be refreshed as Request failed with status code 502 at settle (file:///usr/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12).
[20/02/2023, 09:35:45] [Govee] [Kitchen Sink] could not be refreshed as Request failed with status code 502 at settle (file:///usr/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12).
```

See screenshots below.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? `Homebridge`

* Which version of Homebridge/HOOBS do you have? `Homebridge 1.6.0 (latest)`

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known. `RPI 4, nodejs 16.19.1`

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version? `homebridge-govee v7.9.1`

* Which Govee devices do you have that are causing issues? Please include product models if applicable. `water sensors; H5054`

### Please paste any relevant logs below.

-------------------

### Govee names
![Screenshot 2023-02-20 at 09 41 57](https://user-images.githubusercontent.com/19912012/220150117-776595c0-d593-4ec0-b1a1-04718d9d8552.png)

### HomeBridge names

![image](https://user-images.githubusercontent.com/19912012/220150181-ba4f1554-7e31-4b2b-a6ec-dd150bcea6c8.png)

### Plugin config, under devices
![image](https://user-images.githubusercontent.com/19912012/220150466-880b4ef4-6213-4cbb-8002-2c51b8ad55f6.png)

### Relevant logs
<details>
<code>   [20/02/2023, 09:35:14] [Govee] [Humidifier Left] initialising with options {}.</br>
    [20/02/2023, 09:35:14] [Govee] [Humidifier Left] initialised with id [DAF15B092CAxxxxxx] [H5054].</br>
    [20/02/2023, 09:35:14] [Govee] [Humidifier Right] initialising with options {}.</br>
    [20/02/2023, 09:35:14] [Govee] [Humidifier Right] initialised with id [DAF15B092CAxxxxxx] [H5054].</br>
    [20/02/2023, 09:35:15] [Govee] [Humidifier Left] has been reported [online].</br>
    [20/02/2023, 09:35:16] [Govee] [Humidifier Right] has been reported [online].</br>
    </br>...</br>
    [20/02/2023, 09:30:32] [Govee] [Humidifier] could not be refreshed as Request failed with status code 502 at settle </br>
      (file:///usr/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12).</br>
    [20/02/2023, 09:35:45] [Govee] [Kitchen Sink] could not be refreshed as Request failed with status code 502 at settle </br>
      (file:///usr/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12).</br>
</code>
</details>

**Comment by joshjohanning** [comment]
Ohhhh is this from the HomeBridge device cache?
