### ISSUE TITLE
disabling client as Could not find openssl on your system

### ISSUE THREAD

**Issue by tikkanenfelix** [bwp91/homebridge-govee#472]
### What issue do you have? Please be as thorough and explicit as possible.
Can't add govee devices to homebridge. It gives me an error ` [Govee] [HTTP] disabling client as Could not find openssl on your system on this path: openssl ......`

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
UI-UX 

* Which version of Homebridge/HOOBS do you have?
[v1.6.0]

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
windows 10 nodejs [v18.14.2]

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

v7.9.3

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6159
H6127

### Please paste any relevant logs below.

```
[15/3/2023 20:58:27] [Homebridge UI] Homebridge Config UI X v4.50.2 is listening on :: port 8581
[15/3/2023 20:58:27] [HB Supervisor] Starting Homebridge with extra flags: -I
[15/3/2023 20:58:27] [HB Supervisor] Started Homebridge v1.6.0 with PID: 12404
[15/3/2023 20:58:28] Loaded config.json with 0 accessories and 2 platforms.
[15/3/2023 20:58:28] ---
[15/3/2023 20:58:28] Loaded plugin: homebridge-config-ui-x@4.50.2
[15/3/2023 20:58:28] Registering platform 'homebridge-config-ui-x.config'
[15/3/2023 20:58:28] ---
[15/3/2023 20:58:28] Loaded plugin: homebridge-dummy@0.9.0
[15/3/2023 20:58:28] Registering accessory 'homebridge-dummy.DummySwitch'
[15/3/2023 20:58:28] ---
[15/3/2023 20:58:28] Loaded plugin: homebridge-govee@7.9.3
[15/3/2023 20:58:28] Registering platform 'homebridge-govee.Govee'
[15/3/2023 20:58:28] ---
[15/3/2023 20:58:28] Loading 2 platforms...
[15/3/2023 20:58:28] [Govee] Initializing Govee platform...
[15/3/2023 20:58:28] [Govee] Initializing child bridge 0E:8D:95:7E:FE:8D
Setup Payload:
X-HM://00250SG2DY0FG
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ xxx-xx-xxx              │     
    └────────────┘     
                       
[15/3/2023 20:58:28] Homebridge v1.6.0 (HAP v0.11.0) (Homebridge 1D55) is running on port 51006.
[15/3/2023 20:58:28] [Govee] Launched child bridge with PID 14260
[15/3/2023 20:58:29] Registering platform 'homebridge-govee.Govee'
[15/3/2023 20:58:29] [Govee] Loaded homebridge-govee v7.9.3 child bridge successfully
[15/3/2023 20:58:29] Loaded 3 cached accessories from cachedAccessories.0E8D957EFE8D.
[15/3/2023 20:58:29] [Govee] Initialising plugin v7.9.3 | System win32 | Node v18.14.2 | HB v1.6.0 | HAPNodeJS v0.11.0...
[15/3/2023 20:58:29] [Govee] Plugin initialised. Setting up accessories....
[15/3/2023 20:58:29] Homebridge v1.6.0 (HAP v0.11.0) (Govee) is running on port 45928.
[15/3/2023 20:58:31] [Govee] [LAN] client enabled and found 0 device(s).
[15/3/2023 20:58:31] [Govee] [HTTP] client enabled and found 3 device(s).
[15/3/2023 20:58:31] [Govee] [HTTP] disabling client as Could not find openssl on your system on this path: openssl at C:\Users\felix.tikkanen\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\@bwp91\pem\webpack:\pem\lib\openssl.js:257:1.
[15/3/2023 20:58:31] [Govee] [AWS] disabling client as requires HTTP client.
[15/3/2023 20:58:32] [Govee] [API] client enabled and found 1 device(s).
[15/3/2023 20:58:32] [Govee] [BLE] disabling client as Cannot find package '@abandonware/bluetooth-hci-socket' imported from C:\Users\felix.tikkanen\AppData\Roaming\npm\node_modules\homebridge-govee\lib\platform.js at new NodeError (node:internal/errors:399:5).
[15/3/2023 20:58:32] [Govee] [Roof] initialising with options {"adaptiveLightingShift":0,"aws":"disabled","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[15/3/2023 20:58:32] [Govee] [Roof] initialised with id [56:67:A4:C1:38:50:10:2E] [H6159].
[15/3/2023 20:58:32] [Govee] [bed] will be visible but uncontrollable as BLE not available.
[15/3/2023 20:58:32] [Govee] [bed] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[15/3/2023 20:58:32] [Govee] [bed] initialised with id [AC:C3:A5:50:E8:3B:AD:BF] [H6127].
[15/3/2023 20:58:32] [Govee] [desk] will be visible but uncontrollable as BLE not available.
[15/3/2023 20:58:32] [Govee] [desk] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[15/3/2023 20:58:32] [Govee] [desk] initialised with id [4A:A7:14:5D:5C:06:8D:1F] [H6127].
[15/3/2023 20:58:34] [Govee] ✓ Setup complete. This plugin currently has a 4.5☆ rating on HOOBS! https://bit.ly/hb-govee-review
```

**Comment by 0nitsoga** [comment]
I am having the same issue:

- **Homebridge UI-X**: v1.6.0
- **Inside a docker in Home Assistant OS on Intel hardware**
- **Plugin Version**: v8.1.0

 ```
 [4/5/2023, 3:01:01 PM] [Govee] [HTTP] disabling client as Could not find openssl on your system on this path: openssl at /homebridge/node_modules/homebridge-govee/node_modules/@bwp91/pem/webpack:/pem/lib/openssl.js:257:1.
```

**Comment by jasontracen** [comment]
I am having the same issue

[4/16/2023, 4:25:10 AM] [Govee] [LAN] client enabled and found 1 device(s).
[4/16/2023, 4:25:10 AM] [Govee] [HTTP] client enabled and found 8 device(s).
[4/16/2023, 4:25:10 AM] [Govee] [HTTP] disabling client as Could not find openssl on your system on this path: openssl at C:\Users\\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\pem\webpack:\pem\lib\openssl.js:258:1.
[4/16/2023, 4:25:10 AM] [Govee] See https://github.com/bwp91/homebridge-govee/wiki/OpenSSL for more info about installing OpenSSL
[4/16/2023, 4:25:10 AM] [Govee] [AWS] disabling client as requires HTTP client.
[4/16/2023, 4:25:11 AM] [Govee] [BLE] disabling client as No compatible USB Bluetooth 4.0 device found! at BluetoothHciSocket.bindUser (C:\...\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\@abandonware\bluetooth-hci-socket\lib\usb.js:78:11).


Homebridge UI-X: v1.6.0
Homebridge running on Windows 10
Plugin Version 8.1.2

**Comment by bwp91** [comment]
For users on windows please try this:

—-

can you try uninstalling any openssl version you have, then install openssl v1.1 rather than v3
and also refer to this comment 
https://github.com/bwp91/homebridge-govee/issues/405#issuecomment-1368269873
to see if you have any success?

**Comment by tanjello** [comment]
See my comment below 405 for how to fix this on windows.
