### ISSUE TITLE
H6003 Color Change Failing

### ISSUE THREAD

**Issue by joshsb9662** [bwp91/homebridge-govee#484]
### What issue do you have? Please be as thorough and explicit as possible.

Govee H6003 is able to be turned on/off and dimmed but does not respond TK color change command view HomeKit/home bridge

### Details of your setup.
* Do you use Homebridge (with config-ui?) or HOOBS? 

Homebridge

* Which version of Homebridge/HOOBS do you have?

v1.6.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

v8.1.1 but have downgraded all the way back to v7.9.3. Started recently, but doesn’t appear to be tied to a version. Unsure if there is a downstream issue or change that broke this. 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

H6003

### Please paste any relevant logs below.

```
3/04/2023, 21:49:31] [Govee] [Ethan’s Lamp] current colour [rgb 0 255 0].
[03/04/2023, 21:49:32] [Govee] [AWS] message event [{"proType":2,"sku":"H6003","device":"4e:ee:d4:ad:fc:08:32:26","transaction":"v_1680572971542000","softVersion":"1.00.15","type":0,"pactType":1,"pactCode":1,"cmd":"colorwc"}].
[03/04/2023, 21:49:32] [Govee] [Ethan’s Lamp] [AWS] receiving update {"source":"AWS","proType":2,"sku":"H6003","device":"4e:ee:d4:ad:fc:08:32:26","transaction":"v_1680572971542000","softVersion":"1.00.15","type":0,"pactType":1,"pactCode":1,"cmd":"colorwc"}.
[03/04/2023, 21:49:35] [Govee] [Ethan’s Lamp] [AWS] sending update {"msg":{"cmd":"colorwc","cmdVersion":0,"data":{"color":{"r":0,"g":8,"b":255,"red":0,"green":8,"blue":255},"colorTemInKelvin":0},"transaction":"v_1680572975989000","type":1}}.
[03/04/2023, 21:49:35] [Govee] [Ethan’s Lamp] current colour [rgb 0 8 255].
[03/04/2023, 21:49:36] [Govee] [AWS] message event [{"proType":2,"sku":"H6003","device":"4e:ee:d4:ad:fc:08:32:26","transaction":"v_1680572975989000","softVersion":"1.00.15","type":0,"pactType":1,"pactCode":1,"cmd":"colorwc"}].
[03/04/2023, 21:49:36] [Govee] [Ethan’s Lamp] [AWS] receiving update {"source":"AWS","proType":2,"sku":"H6003","device":"4e:ee:d4:ad:fc:08:32:26","transaction":"v_1680572975989000","softVersion":"1.00.15","type":0,"pactType":1,"pactCode":1,"cmd":"colorwc"}.
```

**Comment by bor9455** [comment]
Having the same issue.  I am able to get the lights to come on or turn off, but they cannot change colors from HomeKit.  I made the mistake of using Alexa tonight to change the color on a light and the green hue that Amazon uses is different from the HomeKit one and it's ugly as hell.  HomeKit does a better job!  This isn't working and I'm about to just dump the Govee lights for another product.

**Comment by bwp91** [comment]
Please see the wiki page here - I have updated with some info about colour control

https://github.com/bwp91/homebridge-govee/wiki/Common-Errors

**Comment by joshsb9662** [comment]
Thanks for sending this @bwp91. 

I ran through the wiki and set the device ID/Mac Address to every color mode and restarted. I however still never got the light color to update via HomeKit, it does work still using the Govee Native app. 

This used to work very recently with default settings, my suspicion is Govee made a change to there api breaking this functionality.

**Comment by mK737** [comment]
> Please see the wiki page here - I have updated with some info about colour control
> 
> https://github.com/bwp91/homebridge-govee/wiki/Common-Errors

Hi bwp91,

I have the exact same problems like the thread opener with my H6003 lamps.

I've tried all your suggestions regarding brightness & color..nothing works.

Since for the moment brightness is the most important to me I went down all the way back to version 7.9.2 where at least brightness control works.


System setup when trying the error fix:

Homebridge v1.6.0
Node.js v18.15.0
Homebridge-govee v8.1.2

Best regards

**Comment by bwp91** [comment]
@joshsb9662 @mK737 

please restart the plugin and post the setup logs that appear in the homebridge log. maybe there is something here that is not working.

**Comment by mK737** [comment]
I just deleted the plugin and made a fresh installation and restart. Currently without extra device ID entered but I can post that as well if you wish. Thanks for your help!


> [11/04/2023, 07:25:35] [Govee] Initializing Govee platform...
[11/04/2023, 07:25:35] [Govee] Initialising plugin v8.1.2 | System linux | Node v18.15.0 | HB v1.6.0 | HAPNodeJS v0.11.0...
[11/04/2023, 07:25:35] Loading 1 accessories...
[11/04/2023, 07:25:35] [Govee] Plugin initialised. Setting up accessories....
[11/04/2023, 07:25:38] [Govee] [HTTP] client enabled and found 4 device(s).
[11/04/2023, 07:25:38] [Govee] [AWS] client enabled.
[11/04/2023, 07:25:38] [Govee] [BLE] client enabled.
[11/04/2023, 07:25:39] [Govee] [Schlafzimmer] has been added to Homebridge.
[11/04/2023, 07:25:39] [Govee] [Schlafzimmer] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"unsupported","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[11/04/2023, 07:25:39] [Govee] [Schlafzimmer] initialised with id [8b:76:7c:a6:b0:17:82:9b] [H6003].
[11/04/2023, 07:25:39] [Govee] [Kugel] has been added to Homebridge.
[11/04/2023, 07:25:39] [Govee] [Kugel] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"unsupported","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[11/04/2023, 07:25:39] [Govee] [Kugel] initialised with id [98:2f:7c:a6:b0:14:3f:58] [H6003].
[11/04/2023, 07:25:39] [Govee] [Scheinwerfer] has been added to Homebridge.
[11/04/2023, 07:25:39] [Govee] [Scheinwerfer] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"unsupported","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[11/04/2023, 07:25:39] [Govee] [Scheinwerfer] initialised with id [a5:22:7c:a6:b0:11:48:cf] [H6003].
[11/04/2023, 07:25:39] [Govee] [LED] has been added to Homebridge.
[11/04/2023, 07:25:39] [Govee] [LED] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[11/04/2023, 07:25:39] [Govee] [LED] initialised with id [BF:80:A4:C1:38:AA:56:D6] [H6181].
[11/04/2023, 07:25:40] [Govee] ✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!
[11/04/2023, 07:25:41] [Govee] [Kugel] current state [on].
[11/04/2023, 07:25:41] [Govee] [Kugel] current brightness [11%].
[11/04/2023, 07:25:41] [Govee] [Kugel] current colour [2000K / 500M].
[11/04/2023, 07:25:41] [Govee] [Schlafzimmer] current brightness [7%].
[11/04/2023, 07:25:41] [Govee] [Schlafzimmer] current colour [2000K / 500M].
[11/04/2023, 07:25:42] [Govee] [Scheinwerfer] current state [on].
[11/04/2023, 07:25:42] [Govee] [Scheinwerfer] current brightness [24%].
[11/04/2023, 07:25:42] [Govee] [Scheinwerfer] current colour [2000K / 500M].

**Comment by bwp91** [comment]
Please post more logs between what you have posted already and up until “plugin setup complete” line

**Comment by mK737** [comment]
Furthermore I'm now having problems with the BLE LED which was recognised but now is doing trouble.

I'm sorry for all that questions and trouble but I am completely new to Raspberry and Homebridge.



> [11/04/2023, 07:33:47] [Govee] [LED] could not find device [a4:c1:38:aa:56:d6].
[11/04/2023, 07:33:47] [Govee] [LED] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1721:13.
[11/04/2023, 07:33:54] [Govee] [LED] could not find device [a4:c1:38:aa:56:d6].
[11/04/2023, 07:33:54] [Govee] [LED] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1721:13.

**Comment by bwp91** [comment]
is there anyone that would be happy to give me a govee username and password for an account with a H6003 in it? whether it's a new account, or temporarily change the password for your existing account.

this is really the only way I can see what the issue is - and whether it is using different command types to what the plugin is trying to send.

happy to dm on the homebridge discord server https://discord.gg/bHjKNkN
