### ISSUE TITLE
govee light is unreachable in homekit after 9.0.2 update

### ISSUE THREAD

**Issue by arolnick1** [bwp91/homebridge-govee#512]
[DreamView T1 Pro] could not be updated as no connection method available at file:///C:/Users/Admin/AppData/Roaming/npm/node_modules/homebridge-govee/lib/platform.js:1748:13.

homebridge 1.6.1
node js 18.16.0

**Comment by arolnick1** [comment]
[HTTP] disabling client as Could not find openssl on your system on this path: openssl at C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-govee\node_modules\pem\webpack:\pem\lib\openssl.js:258:1.
[5/20/2023, 6:43:38 PM] [Govee] See https://github.com/bwp91/homebridge-govee/wiki/OpenSSL for more info about installing OpenSSL
[5/20/2023, 6:43:38 PM] [Govee] [AWS] disabling client as requires HTTP client.
[5/20/2023, 6:43:38 PM] [Govee] [BLE] disabling client as Cannot find package '@abandonware/bluetooth-hci-socket' imported from C:\Users\Admin\AppData\Roaming\npm\node_modules\homebridge-govee\lib\platform.js at new NodeError (node:internal/errors:399:5).
