### ISSUE TITLE
Two led strips not responding

### ISSUE THREAD

**Issue by petitclercj** [bwp91/homebridge-govee#526]
Hi, I just set up my Homebridge setup on a raspberry pi 4B with the Govee plugin. Homebridge is updated to the latest version.

I have one outlet device that is working perfectly, for the two other leds, I installed the bluetooth plugin through the homebridge terminal without problem. The second sudo line didn't work, tried installing it through ssh and I'm still getting an error.

My two led devices that are causing problem are :
H6196
H613A

Here is the log I always get with any of those LEDs
```
[17/06/2023, 20:55:34] [Govee] [LivingRoom] could not find device [a4:c1:38:fa:9f:41].
[17/06/2023, 20:55:34] [Govee] [LivingRoom] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1721:13.
```
I turned on debug mode where, according to online article would be able to see the Node bluetooth plugin give me the bluetooth address to be added to the configuration, but it doesn't show up

I'm new to homebride, thank you for your help in advance.
Thanks

Edit 
I tried downgrading the plugin to an older version without success, it always gives out the same error. When updating the plugin back to the latest version I noticed the following error code 
```
node-pre-gyp ERR! install response status 404 Not Found on https://github.com/abandonware/node-bluetooth-hci-socket/releases/download/0.5.3-10/bluetooth_hci_socket-0.5.3-10-node-v108-linux-arm.tar.gz 
```

**Comment by bwp91** [comment]
Hi, i need to update the wiki docs about the debug option. debug logs only appear now when a beta version of the plugin is installed.

Please install the beta version:
https://github.com/bwp91/homebridge-govee/wiki/Beta-Version

this should give you the logging.

**Comment by petitclercj** [comment]
Hi @bwp91, thank you  for your answer.
I reverted back to the beta version, which indeed gives me more infos in the logs. It seems to detect the lights (here is the test with the H613A)
```
[23/06/2023, 08:11:20] [Govee] [Kitchen Kallax] starting update with params [{"cmd":4,"data":255}].
[23/06/2023, 08:11:20] [Govee] [Kitchen Kallax] starting timer.
[23/06/2023, 08:11:20] [Govee] [Kitchen Kallax] starting scan.
[23/06/2023, 08:11:20] [Govee] [BLE] scanning started.
[23/06/2023, 08:11:20] [Govee] [Kitchen Kallax] scanning started.
[23/06/2023, 08:11:20] [Govee] [Kitchen Kallax] starting loop.
[23/06/2023, 08:11:20] [Govee] [BLE] found device [08:4e:a6:c4:6e:d8] [undefined].
[23/06/2023, 08:11:20] [Govee] [BLE] found device [28:3d:50:c8:36:77] [undefined].
[23/06/2023, 08:11:20] [Govee] [BLE] found device [29:d3:af:b3:28:9a] [undefined].
[23/06/2023, 08:11:20] [Govee] [BLE] found device [09:2e:ff:80:a0:fe] [undefined].
[23/06/2023, 08:11:20] [Govee] [BLE] found device [31:d3:aa:8a:51:6b] [undefined].
[23/06/2023, 08:11:20] [Govee] [BLE] found device [25:07:66:42:67:a6] [undefined].
[23/06/2023, 08:11:20] [Govee] [BLE] found device [74:c3:ef:1d:ea:3d] [undefined].
[23/06/2023, 08:11:20] [Govee] [BLE] found device [07:a0:b7:9e:4e:a8] [undefined].
[23/06/2023, 08:11:20] [Govee] [BLE] found device [ff:64:fa:2e:4c:7a] [undefined].
[23/06/2023, 08:11:21] [Govee] [BLE] found device [e7:cf:b5:fb:8c:71] [undefined].
[23/06/2023, 08:11:21] [Govee] [BLE] found device [ff:05:4d:a7:f0:6e] [undefined].
[23/06/2023, 08:11:22] [Govee] [BLE] found device [e5:12:1f:b6:02:59] [undefined].
[23/06/2023, 08:11:27] [Govee] [Kitchen Kallax] could not find device [d4:ad:fc:0a:84:ef].
[23/06/2023, 08:11:27] [Govee] [Kitchen Kallax] not using BLE connection as BLE took too long.
[23/06/2023, 08:11:27] [Govee] [Kitchen Kallax] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1748:13.
[23/06/2023, 08:11:34] [Govee] [Kitchen Kallax] starting update with params [{"cmd":1,"data":1}].
[23/06/2023, 08:11:34] [Govee] [Kitchen Kallax] starting timer.
[23/06/2023, 08:11:34] [Govee] [Kitchen Kallax] starting scan.
[23/06/2023, 08:11:34] [Govee] [BLE] scanning started.
[23/06/2023, 08:11:34] [Govee] [Kitchen Kallax] scanning started.
[23/06/2023, 08:11:34] [Govee] [Kitchen Kallax] starting loop.
[23/06/2023, 08:11:34] [Govee] [BLE] found device [d4:ad:fc:e5:f0:1d] [ihoment_H5083_F01D].
[23/06/2023, 08:11:34] [Govee] [BLE] found device [25:07:66:42:67:a6] [undefined].
[23/06/2023, 08:11:34] [Govee] [BLE] found device [a4:c1:38:fa:9f:41] [ihoment_H6196_9F41].
[23/06/2023, 08:11:34] [Govee] [BLE] found device [d4:ad:fc:0a:84:ef] [GBK_H613A_84EF].
[23/06/2023, 08:11:34] [Govee] [Kitchen Kallax] has been reported [discoverable] via BLE.
[23/06/2023, 08:11:34] [Govee] [Kitchen Kallax] attempting to connect.
[23/06/2023, 08:11:35] [Govee] [BLE] scanning stopped.
[23/06/2023, 08:11:35] [Govee] [BLE] scanning started.
[23/06/2023, 08:11:35] [Govee] [Kitchen Kallax] has been reported [connected] via BLE.
[23/06/2023, 08:11:35] [Govee] [Kitchen Kallax] finding device characteristics.
[23/06/2023, 08:11:35] [Govee] [Kitchen Kallax] has been reported [disconnected] via BLE [62].
[23/06/2023, 08:11:35] [Govee] [BLE] [unknown] has been reported [disconnected] via BLE [62].
[23/06/2023, 08:11:41] [Govee] [Kitchen Kallax] could not find device [d4:ad:fc:0a:84:ef].
[23/06/2023, 08:11:41] [Govee] [Kitchen Kallax] not using BLE connection as BLE took too long.
[23/06/2023, 08:11:41] [Govee] [Kitchen Kallax] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1748:13.
[23/06/2023, 08:11:48] [Govee] [Kitchen Kallax] starting update with params [{"cmd":1,"data":1}].
[23/06/2023, 08:11:48] [Govee] [Kitchen Kallax] starting timer.
[23/06/2023, 08:11:48] [Govee] [Kitchen Kallax] starting scan.
[23/06/2023, 08:11:48] [Govee] [BLE] scanning started.
[23/06/2023, 08:11:48] [Govee] [Kitchen Kallax] scanning started.
[23/06/2023, 08:11:48] [Govee] [Kitchen Kallax] starting loop.
[23/06/2023, 08:11:48] [Govee] [BLE] found device [d4:ad:fc:e3:ec:a1] [ihoment_H5083_ECA1].
[23/06/2023, 08:11:48] [Govee] [BLE] found device [a4:c1:38:fa:9f:41] [ihoment_H6196_9F41].
[23/06/2023, 08:11:48] [Govee] [BLE] found device [d4:ad:fc:ef:bb:26] [ihoment_H5083_BB26].
[23/06/2023, 08:11:48] [Govee] [BLE] found device [25:07:66:42:67:a6] [undefined].
[23/06/2023, 08:11:48] [Govee] [BLE] found device [d4:ad:fc:0a:84:ef] [GBK_H613A_84EF].
[23/06/2023, 08:11:48] [Govee] [Kitchen Kallax] has been reported [discoverable] via BLE.
[23/06/2023, 08:11:48] [Govee] [Kitchen Kallax] attempting to connect.
[23/06/2023, 08:11:48] [Govee] [BLE] scanning stopped.
[23/06/2023, 08:11:48] [Govee] [BLE] scanning started.
[23/06/2023, 08:11:48] [Govee] [Kitchen Kallax] has been reported [connected] via BLE.
[23/06/2023, 08:11:48] [Govee] [Kitchen Kallax] finding device characteristics.
[23/06/2023, 08:11:48] [Govee] [Kitchen Kallax] has been reported [disconnected] via BLE [62].
[23/06/2023, 08:11:48] [Govee] [BLE] [unknown] has been reported [disconnected] via BLE [62].
[23/06/2023, 08:11:55] [Govee] [Kitchen Kallax] could not find device [d4:ad:fc:0a:84:ef].
[23/06/2023, 08:11:55] [Govee] [Kitchen Kallax] not using BLE connection as BLE took too long.
[23/06/2023, 08:11:55] [Govee] [Kitchen Kallax] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1748:13.
```
I don't know what is the problem with their connection. The same issue and log happens with the H6196
Thank you, looking forward

**Comment by petitclercj** [comment]
@bwp91 Do you have any insight on how to make it work? Seems to be in the compatible devices from your plugin but they always seem to timeout and have problem connecting through BLE. Even though I played with the interval of updates for BLE devices, the plugins doesn't wait long enough to find the devices. Sometimes after the first failure, it finds the devices but then it times out...
Thank you
