### ISSUE TITLE
Plug In has started Reporting a "not connected to AWS error"

### ISSUE THREAD

**Issue by bzieroth** [bwp91/homebridge-govee#538]
### What issue do you have? Please be as thorough and explicit as possible.

Plug In has worked fine for over a year with 5 Govee light strip devices.  No change to the devices or Homebridge configuration.  Really appreciate any guidance you can provide. 

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 

I had a HOOBS which is re-imaged to standard HomeBridge

* Which version of Homebridge/HOOBS do you have?

currently at 1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.

Node.JS is 18.68.0, on a Raspberry PI

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?

currently on 9.1, but have back ported as part as 9.0 and the problem has not resolved itself.

* Which Govee devices do you have that are causing issues? Please include product models if applicable.

5 Devices, all H6141

### Please paste any relevant logs below.

```
[05/07/2023, 19:43:25] [Govee] [Right Front] could not find device [MAC ADDRESS].
[05/07/2023, 19:43:25] [Govee] [Right Front] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1748:13.
[05/07/2023, 19:43:32] [Govee] [Right Front Wide] could not find device [MAC ADDRESS].
[05/07/2023, 19:43:32] [Govee] [Right Front Wide] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1748:13.
[05/07/2023, 19:43:39] [Govee] [Back Wall] could not find device [MAC ADDRESS].
[05/07/2023, 19:43:39] [Govee] [Back Wall] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1748:13.
[05/07/2023, 19:43:46] [Govee] [Right Rear] could not find device [MAC ADDRESS].
[05/07/2023, 19:43:46] [Govee] [Right Rear] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1748:13.
[05/07/2023, 19:43:46] [Govee] [Left Front] could not connect as Error: Peripheral already connected.
[05/07/2023, 19:43:53] [Govee] [Left Front] could not find device [MAC ADDRESS].
[05/07/2023, 19:43:53] [Govee] [Left Front] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1748:13.
[05/07/2023, 19:44:34] [Govee] [Right Front Wide] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
[05/07/2023, 19:44:34] [Govee] [Right Front Wide] could not find device [MAC ADDRESS].
```

**Comment by bwp91** [comment]
Please can you show the logs from the plugin initialising after a restart of homebridge or any plugin bridge? 
there is probably a reason why the connection is not working there

**Comment by bzieroth** [comment]
Hi, thanks for your response.  Please see below everything I get from a home bridge restart.

[16/07/2023, 16:11:14] [Govee] [LAN] client enabled and found 0 device(s).
[16/07/2023, 16:11:17] [Govee] [BLE] client enabled.
[16/07/2023, 16:11:17] [Govee] [Back Wall] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[16/07/2023, 16:11:17] [Govee] [Back Wall] initialised with id [MAC ADDRESS] [H6141].
[16/07/2023, 16:11:17] [Govee] [Right Rear] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[16/07/2023, 16:11:17] [Govee] [Right Rear] initialised with id [MAC ADDRESS] [H6141].
[16/07/2023, 16:11:17] [Govee] [Left Front] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[16/07/2023, 16:11:17] [Govee] [Left Front] initialised with id [MAC ADDRESS] [H6141].
[16/07/2023, 16:11:17] [Govee] [Right Front] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[16/07/2023, 16:11:17] [Govee] [Right Front] initialised with id [MAC ADDRESS] [H6141].
[16/07/2023, 16:11:17] [Govee] [Right Front Wide] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[16/07/2023, 16:11:17] [Govee] [Right Front Wide] initialised with id [MAC ADDRESS] [H6141].
[16/07/2023, 16:11:59] [Govee] [Right Front] not using AWS connection as not connected to AWS.
[16/07/2023, 16:12:06] [Govee] [Right Front] could not find device [MAC ADDRESS].
[16/07/2023, 16:12:06] [Govee] [Right Front] could not be updated as no connection method available at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1748:13.

**Comment by bzieroth** [comment]
latest version appears to have solved the problem, thank you!
