### ISSUE TITLE
no interaction - "could not be updated as no connection method available

### ISSUE THREAD

**Issue by drftjpn** [bwp91/homebridge-govee#547]
**Please explain your feature request in a one or two sentences.**
    no interaction with govee products and homebridge

 **Is your feature request related to a problem? Please describe.**

after trying to add my new fan's in 2 rooms, I got no interaction with my govee plugin. All devices are not responding, and in Homebridge log, I get following errors:

[7/26/2023, 12:40:32 PM] [Govee] [DreamView] could not be updated as no connection method available at file:///homebridge/node_modules/homebridge-govee/lib/platform.js:1748:13.

[7/26/2023, 12:40:37 PM] [Govee] [DreamView] could not be updated as no connection method available at file:///homebridge/node_modules/homebridge-govee/lib/platform.js:1748:13.

**Any particular Govee devices that this relates to?**
 all

**Anything else?**

**Comment by bwp91** [comment]
Please restart the plugin and show logs from the restart

**Comment by drftjpn** [comment]
[7/26/2023, 7:23:21 PM] The plugin "homebridge-govee" requires Node.js version of ^16.20.1 || ^18.17.0 || ^20.5.0 which does not satisfy the current Node.js version of v16.13.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
[7/26/2023, 7:23:21 PM] Loaded plugin: homebridge-govee@9.2.0
[7/26/2023, 7:23:21 PM] Registering platform 'homebridge-govee.Govee'
[7/26/2023, 7:23:21 PM] ---
[7/26/2023, 7:23:23 PM] [Govee] Initializing Govee platform...
[7/26/2023, 7:23:23 PM] [Govee] Initialising plugin v9.2.0 | System linux | Node v16.13.0 | HB v1.6.1 | HAPNodeJS v0.11.1...[7/26/2023, 7:23:23 PM] [Govee] Plugin initialised. Setting up accessories....
[7/26/2023, 7:23:25 PM] [Govee] [LAN] client enabled and found 0 device(s).
[7/26/2023, 7:23:26 PM] [Govee] [HTTP] client enabled and found 3 device(s).
[7/26/2023, 7:23:26 PM] [Govee] [HTTP] disabling client as Could not find openssl on your system on this path: openssl at /homebridge/node_modules/homebridge-govee/node_modules/pem/webpack:/pem/lib/openssl.js:258:1.
[7/26/2023, 7:23:26 PM] [Govee] See https://github.com/bwp91/homebridge-govee/wiki/OpenSSL for more info about installing OpenSSL
[7/26/2023, 7:23:26 PM] [Govee] [AWS] disabling client as requires HTTP client.
[7/26/2023, 7:23:26 PM] [Govee] [BLE] disabling client as ENODEV, No such device.
[7/26/2023, 7:23:26 PM] [Govee] [Ventilator Schlafzimme] initialising with options {}.
[7/26/2023, 7:23:26 PM] [Govee] [Ventilator Schlafzimme] initialised with id [0E:8F:D4:AD:FC:BB:44:BE] [H7102].
[7/26/2023, 7:23:26 PM] [Govee] [Ventilator Wohnzimmer] initialising with options {}.
[7/26/2023, 7:23:26 PM] [Govee] [Ventilator Wohnzimmer] initialised with id [16:A3:D4:AD:FC:67:53:3C] [H7102].
[7/26/2023, 7:23:26 PM] [Govee] [DreamView] initialising with options {"adaptiveLightingShift":0,"aws":"disabled","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[7/26/2023, 7:23:26 PM] [Govee] [DreamView] initialised with id [62:D0:D5:32:37:38:37:8B] [H6199].
[7/26/2023, 7:23:26 PM] [Govee] ✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!

**Comment by bwp91** [comment]
and which platform are you running homebridge on? 
(this is why there is a template in the first place for issues 😝)

**Comment by bwp91** [comment]
The issue is this:

```
[7/26/2023, 7:23:26 PM] [Govee] [HTTP] disabling client as Could not find openssl on your system on this path: openssl at /homebridge/node_modules/homebridge-govee/node_modules/pem/webpack:/pem/lib/openssl.js:258:1.
[7/26/2023, 7:23:26 PM] [Govee] See https://github.com/bwp91/homebridge-govee/wiki/OpenSSL for more info about installing OpenSSL
[7/26/2023, 7:23:26 PM] [Govee] [AWS] disabling client as requires HTTP client.
```


so you need to install openssl, and i can try to be more specific with help if i know your system with homebridge

**Comment by drftjpn** [comment]
Yes, sorry that was stupid by myself :-D

Homebridge is running since years on a QNAP NAS (Docker container, that is using Alpine Linux  (3.12.8)

**Comment by drftjpn** [comment]
I already read the linked page from logfile, but I was not successfull with installing openssl in docker. But very strange that everything was fine before, for a whole year

**Comment by bwp91** [comment]
Can you try the command listed here:
https://github.com/bwp91/homebridge-govee/issues/386#issuecomment-1346748638

within your docker container?

looks like it is `apk add openssl`

**Comment by drftjpn** [comment]
ARE YOU KIDDING?!

It works.

I won't believe that, I am investigating a whole week on that shit!

MANY MANY THANKS!

**Comment by bwp91** [comment]
great!
wiki updated too: https://github.com/bwp91/homebridge-govee/wiki/OpenSSL

thanks for confirming it works 👍🏻

**Comment by drftjpn** [comment]
you are doing a great job here!
