### ISSUE TITLE
bluetooth rgb lights not working

### ISSUE THREAD

**Issue by hotshotnyan** [bwp91/homebridge-govee#549]
### What issue do you have? Please be as thorough and explicit as possible.
i have a h6126 strip that i want to control with homekit. the devices will show up in homebridge but i cant control them. i just recently installed a m.2 wifi/bluetooth adapter in the pc.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
 i use 1

* Which version of Homebridge/HOOBS do you have?
Homebridge v1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
I run homebridge on a virtual box vm in windows

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v9.2.1-beta.4
issue started right away

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
-H6126

### Please paste any relevant logs below.

```
[7/28/2023, 11:57:00 AM] [Govee] [BLE] disabling client as EAFNOSUPPORT, Address family not supported by protocol at new BluetoothHciSocketWrapped (/homebridge/node_modules/homebridge-govee/node_modules/@abandonware/bluetooth-hci-socket/lib/native.js:9:5).
[7/28/2023, 11:57:00 AM] [Govee] [Ps5 room] will be visible but uncontrollable as BLE not available.
[7/28/2023, 11:57:00 AM] [Govee] [Ps5 room] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[7/28/2023, 11:57:00 AM] [Govee] [Ps5 room] initialised with id [62:F8:D4:AD:FC:48:81:BF] [H6126].
[7/28/2023, 11:57:00 AM] [Govee] [My bedroom] will be visible but uncontrollable as BLE not available.
[7/28/2023, 11:57:00 AM] [Govee] [My bedroom] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[7/28/2023, 11:57:00 AM] [Govee] [My bedroom] initialised with id [64:3E:A4:C1:38:7D:81:F7] [H6126].
[7/28/2023, 11:57:00 AM] [Govee] ✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!
[7/28/2023, 11:57:00 AM] [Govee] [AWS] connect event.
[7/28/2023, 11:57:01 AM] [Nest] initing thermostat "Hallway Thermostat": deviceId: 02AA01AC0715075Q structureId: 2945f192-7873-11e5-bdc5-22000ae18863
[Hallway Thermostat@@Heating Threshold Temperature] characteristic was supplied illegal value: number 0 exceeded minimum of 9
[7/28/2023, 11:57:01 AM] [Nest] initing home_away_sensor "Home Occupied - Amrik": deviceId: 2945f192-7873-11e5-bdc5-22000ae18863 structureId: 2945f192-7873-11e5-bdc5-22000ae18863
[7/28/2023, 11:57:01 AM] [Nest] initing home_away_sensor "Home Occupied - Home": deviceId: d47dc110-2cd9-11ed-9a49-0acb55c2ef71 structureId: d47dc110-2cd9-11ed-9a49-0acb55c2ef71
[7/28/2023, 11:57:11 AM] [Homebridge UI] Changes to config.json saved.
[7/28/2023, 11:57:43 AM] [Govee] [Ps5 room] could not be updated as no connection method available at file:///homebridge/node_modules/homebridge-govee/lib/platform.js:1749:13.
[7/28/2023, 11:57:48 AM] [Govee] [Ps5 room] could not be updated as no connection method available at file:///homebridge/node_modules/homebridge-govee/lib/platform.js:1749:13.
[7/28/2023, 1:24:10 PM] [Homebridge UI] [nyan] Accessory layout changes saved.
[7/29/2023, 1:10:59 AM] [Homebridge UI] Running job to cleanup config.json backup files older than 60 days...
[7/29/2023, 4:58:21 AM] [Homebridge UI] Running scheduled instance backup...
[7/29/2023, 4:58:21 AM] [Homebridge UI] Creating temporary backup archive at /tmp/homebridge-backup-txIvyW/homebridge-backup-0E9CCAE95FDC.tar.gz

```

**Comment by bwp91** [comment]
Hi @hotshotnyan 

The bluetooth error you are receiving is this `EAFNOSUPPORT` which means in simple terms that the plugin does not have access to the bluetooth.

I'm not familiar with this error code, but i'm doing a search in github repos

- https://github.com/abandonware/noble/issues?q=EAFNOSUPPORT

and found these links which may help:

- https://github.com/abandonware/noble/issues/43
- https://github.com/abandonware/noble/issues/152
- https://github.com/constructorfleet/homebridge-ultimate-govee/issues/94
- https://github.com/satrik/homebridge-bslamp2/issues/8

**Comment by hotshotnyan** [comment]
okay thank you @bwp91. just one last question, Does homebridge work with a built in bluetooth adapter?

**Comment by bwp91** [comment]
Honestly, on windows, i really have no idea as i don’t have a windows device to test on.

The plugin uses a package called noble for bluetooth connectivity, there is a section for getting it working with windows:
https://github.com/abandonware/noble#windows

I don’t know if or how this would work with an extra vm layer.

But i don’t know of any users who have gone through these steps successfully.

My honest advice would be to buy a model that has cloud connectivity (wifi) or buy a raspberry pi with inbuilt bluetooth 😅
