### ISSUE TITLE
H6125 BLE Device not Working

### ISSUE THREAD

**Issue by xXxNIKIxXx** [bwp91/homebridge-govee#551]
### What issue do you have? Please be as thorough and explicit as possible.
I am trying to connect my LED Strips to HomeKit. I set up the plugin as explained, disabled the settings i dont use. Now i have the problem, that the plugin finds my devices, but times out if i try to send commands.

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
(1) Homebridge UI-X 

* Which version of Homebridge/HOOBS do you have?
Using HB v1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi
Node.js version: v18.17.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
I am using v9.3.1-beta.2, but also tried with version v9.3.0-latest

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
i am using 2 Govee H6125 LED Strips

### Please paste any relevant logs below.

```
[01/08/2023, 20:06:13] [Govee] Initializing Govee platform...
[01/08/2023, 20:06:13] [Govee] Initialising plugin v9.3.1-beta.2 | System linux | Node v18.17.0 | HB v1.6.1 | HAPNodeJS v0.11.1...
[01/08/2023, 20:06:13] [Govee] Plugin initialised. Setting up accessories....
[01/08/2023, 20:06:13] [Govee] ******************************************************************************************
[01/08/2023, 20:06:13] [Govee] You are using a beta version of the plugin - you will experience more logging than normal.
[01/08/2023, 20:06:13] [Govee] ******************************************************************************************
[01/08/2023, 20:06:14] [Govee] [LAN] disabling client as disabled in config.
[01/08/2023, 20:06:15] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 819E) is running on port 51420.
[01/08/2023, 20:06:15] [Govee] [HTTP] retrieved access token from cache.
[01/08/2023, 20:06:22] [Govee] [HTTP] client enabled and found 2 device(s).
[01/08/2023, 20:06:24] [Govee] [AWS] disabling client as disabled in config.
[01/08/2023, 20:06:25] [Govee] [BLE] client enabled.
[01/08/2023, 20:06:25] [Govee] [H6125_3576] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[01/08/2023, 20:06:25] [Govee] [H6125_3576] initialised with id [D2:F1:D4:AD:FC:FF:35:76] [H6125].
[01/08/2023, 20:06:26] [Govee] [H6125_BAD6] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[01/08/2023, 20:06:26] [Govee] [H6125_BAD6] initialised with id [D6:38:D4:AD:FC:BB:BA:D6] [H6125].
[01/08/2023, 20:06:27] [Govee] [BLE] stateChange: poweredOn.
[01/08/2023, 20:06:27] [Govee] ✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!
[01/08/2023, 20:06:46] [Govee] [H6125_3576] starting update with params [{"cmd":4,"data":255}].
[01/08/2023, 20:06:46] [Govee] [H6125_3576] starting timer.
[01/08/2023, 20:06:46] [Govee] [H6125_3576] starting scan.
[01/08/2023, 20:06:56] [Govee] [H6125_3576] starting update with params [{"cmd":1,"data":1}].
[01/08/2023, 20:06:56] [Govee] [H6125_3576] starting timer.
[01/08/2023, 20:06:56] [Govee] [H6125_3576] starting scan.
[01/08/2023, 20:06:56] [Govee] [H6125_3576] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
[01/08/2023, 20:07:06] [Govee] [H6125_3576] starting update with params [{"cmd":1,"data":1}].
[01/08/2023, 20:07:06] [Govee] [H6125_3576] starting timer.
[01/08/2023, 20:07:06] [Govee] [H6125_3576] starting scan.
[01/08/2023, 20:07:06] [Govee] [H6125_3576] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
[01/08/2023, 20:07:16] [Govee] [H6125_3576] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
[01/08/2023, 20:08:53] [Govee] [BLE] scanning stopped.
[01/08/2023, 20:08:53] [Govee] [BLE] scanning started.
[01/08/2023, 20:08:53] [Govee] [H6125_3576] scanning started.
[01/08/2023, 20:08:53] [Govee] [H6125_3576] starting loop.
[01/08/2023, 20:08:53] [Govee] [H6125_3576] could not find device [d4:ad:fc:ff:35:76].
[01/08/2023, 20:08:53] [Govee] [H6125_3576] scanning started.
[01/08/2023, 20:08:53] [Govee] [H6125_3576] starting loop.
[01/08/2023, 20:08:53] [Govee] [H6125_3576] could not find device [d4:ad:fc:ff:35:76].
[01/08/2023, 20:08:53] [Govee] [H6125_3576] scanning started.
[01/08/2023, 20:08:53] [Govee] [H6125_3576] starting loop.
[01/08/2023, 20:08:53] [Govee] [H6125_3576] could not find device [d4:ad:fc:ff:35:76].
[01/08/2023, 20:08:53] [Govee] [H6125_3576] not using BLE connection as BLE took too long.
[01/08/2023, 20:08:53] [Govee] [H6125_3576] not using BLE connection as BLE took too long.
[01/08/2023, 20:08:53] [Govee] [H6125_3576] not using BLE connection as BLE took too long.
```

**Comment by bwp91** [comment]
Hi @xXxNIKIxXx xXx

Logs looks like maybe your device is simply too far away from your homebridge instance, and it simply can’t find the device?

Thanks 
xXx Ben xXx

**Comment by xXxNIKIxXx** [comment]
This would be weird, because my pi was like less than one meter to the Strip.

**Comment by xXxNIKIxXx** [comment]
I have installed the driver from my Bluetooth chip now the output looks like this.

´´´
[01/08/2023, 22:29:00] [Govee] [LAN] disabling client as disabled in config.
[01/08/2023, 22:29:01] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 819E) is running on port 51420.
[01/08/2023, 22:29:01] [Govee] [HTTP] retrieved access token from cache.
[01/08/2023, 22:29:12] [Govee] [HTTP] client enabled and found 2 device(s).
[01/08/2023, 22:29:14] [Govee] [AWS] disabling client as disabled in config.
[01/08/2023, 22:29:16] [Govee] [BLE] client enabled.
[01/08/2023, 22:29:16] [Govee] [H6125_3576] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[01/08/2023, 22:29:16] [Govee] [H6125_3576] initialised with id [D2:F1:D4:AD:FC:FF:35:76] [H6125].
[01/08/2023, 22:29:16] [Govee] [H6125_BAD6] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[01/08/2023, 22:29:16] [Govee] [H6125_BAD6] initialised with id [D6:38:D4:AD:FC:BB:BA:D6] [H6125].
[01/08/2023, 22:29:17] [Govee] [BLE] stateChange: poweredOn.
[01/08/2023, 22:29:17] [Govee] ✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!
[01/08/2023, 22:29:36] [Govee] [H6125_3576] starting update with params [{"cmd":1,"data":1}].
[01/08/2023, 22:29:36] [Govee] [H6125_3576] starting timer.
[01/08/2023, 22:29:36] [Govee] [H6125_3576] starting scan.
[01/08/2023, 22:29:36] [Govee] [BLE] scanning started.
[01/08/2023, 22:29:36] [Govee] [H6125_3576] scanning started.
[01/08/2023, 22:29:36] [Govee] [H6125_3576] starting loop.
[01/08/2023, 22:29:36] [Govee] [BLE] found device [35:f1:29:0e:d5:1e] [undefined].
[01/08/2023, 22:29:36] [Govee] [BLE] found device [1e:01:99:ac:41:0b] [undefined].
[01/08/2023, 22:29:36] [Govee] [BLE] found device [4b:f7:34:32:4f:d4] [undefined].
[01/08/2023, 22:29:36] [Govee] [BLE] found device [60:f4:d4:95:2e:93] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [7a:cc:8c:52:cb:37] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [86:2a:fd:76:bb:09] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [45:6c:8a:b2:18:25] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [22:92:05:27:7c:d8] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [d0:03:df:88:a0:63] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [02:27:78:52:f9:aa] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [d6:ab:5b:50:65:f7] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [d6:f1:df:54:d7:f4] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [00:7c:2d:e5:c2:fd] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [ea:30:97:88:34:66] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [18:23:07:b0:79:d1] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [f4:73:03:0f:3f:18] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [c7:30:1d:b8:83:27] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [50:de:06:78:08:95] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [48:59:14:0e:d7:6b] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [64:d2:c4:a9:81:63] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [1c:29:29:07:eb:bb] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [40:11:27:65:44:18] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [6c:a5:33:21:a6:0e] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [43:e0:17:96:db:1a] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [c7:1f:e4:09:37:17] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [44:28:18:9e:22:09] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [3a:52:a5:4b:8d:eb] [undefined].
[01/08/2023, 22:29:37] [Govee] [BLE] found device [c0:95:6d:50:b2:98] [undefined].
[01/08/2023, 22:29:38] [Govee] [BLE] found device [35:8f:5e:1f:4e:b5] [undefined].
[01/08/2023, 22:29:38] [Govee] [BLE] found device [5e:71:a7:0f:2a:fc] [undefined].
[01/08/2023, 22:29:38] [Govee] [BLE] found device [6f:2c:58:98:8d:65] [undefined].
[01/08/2023, 22:29:38] [Govee] [BLE] found device [27:c5:c7:1c:cb:d6] [undefined].
[01/08/2023, 22:29:38] [Govee] [BLE] found device [3d:8c:8d:8d:a1:76] [undefined].
[01/08/2023, 22:29:38] [Govee] [BLE] found device [05:32:1c:34:54:57] [undefined].
[01/08/2023, 22:29:38] [Govee] [BLE] found device [d4:ad:fc:ff:35:76] [GBK_H6125_3576].
[01/08/2023, 22:29:38] [Govee] [H6125_3576] has been reported [discoverable] via BLE.
[01/08/2023, 22:29:38] [Govee] [H6125_3576] attempting to connect.
[01/08/2023, 22:30:20] [Govee] [H6125_3576] starting update with params [{"cmd":4,"data":255}].
[01/08/2023, 22:30:20] [Govee] [H6125_3576] starting timer.
[01/08/2023, 22:30:20] [Govee] [H6125_3576] starting scan.
[01/08/2023, 22:30:20] [Govee] [H6125_3576] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
[01/08/2023, 22:30:21] [Govee] [BLE] scanning started.
[01/08/2023, 22:30:21] [Govee] [H6125_3576] scanning started.
[01/08/2023, 22:30:21] [Govee] [H6125_3576] starting loop.
[01/08/2023, 22:30:21] [Govee] [H6125_3576] could not find device [d4:ad:fc:ff:35:76].
[01/08/2023, 22:30:21] [Govee] [H6125_3576] not using BLE connection as BLE took too long.
[01/08/2023, 22:30:21] [Govee] [BLE] scanning stopped.
[01/08/2023, 22:30:27] [Govee] [H6125_3576] could not find device [d4:ad:fc:ff:35:76].
[01/08/2023, 22:30:27] [Govee] [H6125_3576] not using BLE connection as BLE took too long.
[01/08/2023, 22:30:28] [Govee] [H6125_3576] starting update with params [{"cmd":1,"data":1}].
[01/08/2023, 22:30:28] [Govee] [H6125_3576] starting timer.
[01/08/2023, 22:30:28] [Govee] [H6125_3576] starting scan.
[01/08/2023, 22:30:28] [Govee] [H6125_3576] could not be updated as no connection method available, see https://shorturl.at/eCN04 for more info at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1751:13.
noble warning: unknown handle 16 disconnected!
[01/08/2023, 22:30:38] [Govee] [H6125_3576] starting update with params [{"cmd":1,"data":1}].
[01/08/2023, 22:30:38] [Govee] [H6125_3576] starting timer.
[01/08/2023, 22:30:38] [Govee] [H6125_3576] starting scan.
[01/08/2023, 22:30:38] [Govee] [H6125_3576] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
[01/08/2023, 22:30:48] [Govee] [H6125_3576] starting update with params [{"cmd":4,"data":255}].
[01/08/2023, 22:30:48] [Govee] [H6125_3576] starting timer.
[01/08/2023, 22:30:48] [Govee] [H6125_3576] starting scan.
[01/08/2023, 22:30:48] [Govee] [H6125_3576] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
[01/08/2023, 22:30:58] [Govee] [H6125_3576] starting update with params [{"cmd":1,"data":1}].
[01/08/2023, 22:30:58] [Govee] [H6125_3576] starting timer.
[01/08/2023, 22:30:58] [Govee] [H6125_3576] starting scan.
[01/08/2023, 22:30:58] [Govee] [H6125_3576] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
[01/08/2023, 22:31:08] [Govee] [H6125_3576] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
´´´

**Comment by xXxNIKIxXx** [comment]
i now installed the driver for the blouthouth from another source. if i run the following on the pi i get this output.
So it looks like it can't connect to the led Strip.
```
niklas@homebridge-niklas:~ $ bluetoothctl
Agent registered
[CHG] Controller 08:BF:B8:49:C9:3E Pairable: yes
[bluetooth]# scan on
Discovery started
[CHG] Controller 08:BF:B8:49:C9:3E Discovering: yes
[NEW] Device 2C:24:0D:53:FE:E4 2C-24-0D-53-FE-E4
[NEW] Device 0D:C1:4D:A4:6F:35 0D-C1-4D-A4-6F-35
[NEW] Device 1E:01:99:AC:41:0B 1E-01-99-AC-41-0B
[NEW] Device C0:95:6D:50:B2:98 C0-95-6D-50-B2-98
[NEW] Device 86:2A:FD:76:BB:09 86-2A-FD-76-BB-09
[NEW] Device 2E:41:87:23:B6:90 2E-41-87-23-B6-90
[NEW] Device 7D:6B:6E:45:4C:BA 7D-6B-6E-45-4C-BA
[NEW] Device 5C:9E:1B:AB:4A:C3 5C-9E-1B-AB-4A-C3
[NEW] Device 45:AE:FE:A1:14:16 45-AE-FE-A1-14-16
[NEW] Device D4:AD:FC:FF:35:76 GBK_H6125_3576
[NEW] Device 64:D2:C4:A9:81:63 64-D2-C4-A9-81-63
[NEW] Device 3D:8C:8D:8D:A1:76 3D-8C-8D-8D-A1-76
[NEW] Device 50:15:EE:39:13:7A 50-15-EE-39-13-7A
[NEW] Device 50:DE:06:78:08:95 50-DE-06-78-08-95
[NEW] Device 60:B5:92:9F:78:8E 60-B5-92-9F-78-8E
[NEW] Device 1C:29:29:07:EB:BB 1C-29-29-07-EB-BB
[CHG] Controller 08:BF:B8:49:C9:3E Name: homebridge-niklas
[CHG] Controller 08:BF:B8:49:C9:3E Alias: BlueZ 5.55
[CHG] Controller 08:BF:B8:49:C9:3E Alias: homebridge-niklas
[NEW] Device 5B:BE:25:61:20:9F 5B-BE-25-61-20-9F
[NEW] Device 52:B2:88:1A:AE:D9 52-B2-88-1A-AE-D9
[NEW] Device 7C:8A:49:36:5C:88 7C-8A-49-36-5C-88
[NEW] Device 7D:52:0F:F4:96:DB 7D-52-0F-F4-96-DB
[NEW] Device 51:88:41:2B:BF:52 51-88-41-2B-BF-52
[bluetooth]# scan off
[CHG] Device 51:88:41:2B:BF:52 TxPower is nil
[CHG] Device 51:88:41:2B:BF:52 RSSI is nil
[CHG] Device 7D:52:0F:F4:96:DB TxPower is nil
[CHG] Device 7D:52:0F:F4:96:DB RSSI is nil
[CHG] Device 7C:8A:49:36:5C:88 TxPower is nil
[CHG] Device 7C:8A:49:36:5C:88 RSSI is nil
[CHG] Device 52:B2:88:1A:AE:D9 TxPower is nil
[CHG] Device 52:B2:88:1A:AE:D9 RSSI is nil
[CHG] Device 5B:BE:25:61:20:9F TxPower is nil
[CHG] Device 5B:BE:25:61:20:9F RSSI is nil
[CHG] Device 1C:29:29:07:EB:BB RSSI is nil
[CHG] Device 60:B5:92:9F:78:8E TxPower is nil
[CHG] Device 60:B5:92:9F:78:8E RSSI is nil
[CHG] Device 50:DE:06:78:08:95 TxPower is nil
[CHG] Device 50:DE:06:78:08:95 RSSI is nil
[CHG] Device 50:15:EE:39:13:7A TxPower is nil
[CHG] Device 50:15:EE:39:13:7A RSSI is nil
[CHG] Device 3D:8C:8D:8D:A1:76 RSSI is nil
[CHG] Device 64:D2:C4:A9:81:63 TxPower is nil
[CHG] Device 64:D2:C4:A9:81:63 RSSI is nil
[CHG] Device D4:AD:FC:FF:35:76 RSSI is nil
[CHG] Device 45:AE:FE:A1:14:16 TxPower is nil
[CHG] Device 45:AE:FE:A1:14:16 RSSI is nil
[CHG] Device 5C:9E:1B:AB:4A:C3 TxPower is nil
[CHG] Device 5C:9E:1B:AB:4A:C3 RSSI is nil
[CHG] Device 7D:6B:6E:45:4C:BA TxPower is nil
[CHG] Device 7D:6B:6E:45:4C:BA RSSI is nil
[CHG] Device 2E:41:87:23:B6:90 RSSI is nil
[CHG] Device 86:2A:FD:76:BB:09 RSSI is nil
[CHG] Device C0:95:6D:50:B2:98 TxPower is nil
[CHG] Device C0:95:6D:50:B2:98 RSSI is nil
[CHG] Device 1E:01:99:AC:41:0B RSSI is nil
[CHG] Device 0D:C1:4D:A4:6F:35 RSSI is nil
[CHG] Device 2C:24:0D:53:FE:E4 RSSI is nil
[CHG] Controller 08:BF:B8:49:C9:3E Discovering: no
Discovery stopped
[bluetooth]#
```

But the Homebridge output looks like this:

```
[02/08/2023, 06:09:33] [Govee] [LAN] disabling client as disabled in config.
[02/08/2023, 06:09:33] Homebridge v1.6.1 (HAP v0.11.1) (Homebridge 249B) is running on port 51797.
[02/08/2023, 06:09:34] [Govee] [HTTP] retrieved access token from cache.
[02/08/2023, 06:09:40] [Govee] [HTTP] client enabled and found 2 device(s).
[02/08/2023, 06:09:43] [Govee] [AWS] disabling client as disabled in config.
[02/08/2023, 06:09:44] [Govee] [BLE] client enabled.
[02/08/2023, 06:09:44] [Govee] [H6125_3576] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[02/08/2023, 06:09:44] [Govee] [H6125_3576] initialised with id [D2:F1:D4:AD:FC:FF:35:76] [H6125].
[02/08/2023, 06:09:44] [Govee] [H6125_BAD6] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[02/08/2023, 06:09:44] [Govee] [H6125_BAD6] initialised with id [D6:38:D4:AD:FC:BB:BA:D6] [H6125].
[02/08/2023, 06:09:45] [Govee] [BLE] stateChange: poweredOn.
[02/08/2023, 06:09:45] [Govee] ✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!
[02/08/2023, 06:10:26] [Govee] [H6125_3576] starting update with params [{"cmd":1,"data":1}].
[02/08/2023, 06:10:26] [Govee] [H6125_3576] starting timer.
[02/08/2023, 06:10:26] [Govee] [H6125_3576] starting scan.
[02/08/2023, 06:10:26] [Govee] [BLE] scanning started.
[02/08/2023, 06:10:26] [Govee] [H6125_3576] scanning started.
[02/08/2023, 06:10:26] [Govee] [H6125_3576] starting loop.
[02/08/2023, 06:10:26] [Govee] [BLE] found device [d4:ad:fc:ff:35:76] [GBK_H6125_3576].
[02/08/2023, 06:10:26] [Govee] [H6125_3576] has been reported [discoverable] via BLE.
[02/08/2023, 06:10:26] [Govee] [H6125_3576] attempting to connect.
[02/08/2023, 06:11:09] [Govee] [H6125_3576] starting update with params [{"cmd":4,"data":255}].
[02/08/2023, 06:11:09] [Govee] [H6125_3576] starting timer.
[02/08/2023, 06:11:09] [Govee] [H6125_3576] starting scan.
[02/08/2023, 06:11:09] [Govee] [H6125_3576] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
[02/08/2023, 06:11:09] [Govee] [H6125_3576] could not find device [d4:ad:fc:ff:35:76].
[02/08/2023, 06:11:09] [Govee] [H6125_3576] not using BLE connection as BLE took too long.
[02/08/2023, 06:11:09] [Govee] [BLE] scanning stopped.
[02/08/2023, 06:11:09] [Govee] [BLE] scanning started.
[02/08/2023, 06:11:09] [Govee] [H6125_3576] scanning started.
[02/08/2023, 06:11:09] [Govee] [H6125_3576] starting loop.
[02/08/2023, 06:11:09] [Govee] [BLE] scanning stopped.
[02/08/2023, 06:11:16] [Govee] [H6125_3576] could not find device [d4:ad:fc:ff:35:76].
[02/08/2023, 06:11:16] [Govee] [H6125_3576] not using BLE connection as BLE took too long.
[02/08/2023, 06:11:16] [Govee] [H6125_3576] starting update with params [{"cmd":1,"data":1}].
[02/08/2023, 06:11:16] [Govee] [H6125_3576] starting timer.
[02/08/2023, 06:11:16] [Govee] [H6125_3576] starting scan.
[02/08/2023, 06:11:16] [Govee] [H6125_3576] could not be updated as no connection method available, see https://shorturl.at/eCN04 for more info at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1751:13.
noble warning: unknown handle 16 disconnected!
[02/08/2023, 06:11:26] [Govee] [H6125_3576] starting update with params [{"cmd":1,"data":1}].
[02/08/2023, 06:11:26] [Govee] [H6125_3576] starting timer.
[02/08/2023, 06:11:26] [Govee] [H6125_3576] starting scan.
[02/08/2023, 06:11:26] [Govee] [H6125_3576] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
[02/08/2023, 06:11:35] [Govee] [BLE] scanning stopped.
[02/08/2023, 06:11:35] [Govee] [BLE] scanning started.
[02/08/2023, 06:11:35] [Govee] [H6125_3576] scanning started.
[02/08/2023, 06:11:35] [Govee] [H6125_3576] starting loop.
[02/08/2023, 06:11:35] [Govee] [H6125_3576] could not find device [d4:ad:fc:ff:35:76].
[02/08/2023, 06:11:35] [Govee] [H6125_3576] scanning started.
[02/08/2023, 06:11:35] [Govee] [H6125_3576] starting loop.
[02/08/2023, 06:11:35] [Govee] [H6125_3576] could not find device [d4:ad:fc:ff:35:76].
[02/08/2023, 06:11:35] [Govee] [H6125_3576] not using BLE connection as BLE took too long.
[02/08/2023, 06:11:35] [Govee] [H6125_3576] not using BLE connection as BLE took too long.
[02/08/2023, 06:11:35] [Govee] [H6125_3576] starting update with params [{"cmd":4,"data":255}].
[02/08/2023, 06:11:35] [Govee] [H6125_3576] starting timer.
[02/08/2023, 06:11:35] [Govee] [H6125_3576] starting scan.
[02/08/2023, 06:11:35] [Govee] [H6125_3576] could not be updated as no connection method available, see https://shorturl.at/eCN04 for more info at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1751:13.
[02/08/2023, 06:11:45] [Govee] [H6125_3576] starting update with params [{"cmd":1,"data":1}].
[02/08/2023, 06:11:45] [Govee] [H6125_3576] starting timer.
[02/08/2023, 06:11:45] [Govee] [H6125_3576] starting scan.
[02/08/2023, 06:11:45] [Govee] [H6125_3576] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
[02/08/2023, 06:11:55] [Govee] [H6125_3576] starting update with params [{"cmd":1,"data":1}].
[02/08/2023, 06:11:55] [Govee] [H6125_3576] starting timer.
[02/08/2023, 06:11:55] [Govee] [H6125_3576] starting scan.
[02/08/2023, 06:11:55] [Govee] [H6125_3576] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
```

**Comment by xXxNIKIxXx** [comment]
Seems like the problem is while trying to update. I get no error that it cant connect, but also not the feedback that it is connected.
If i use the bluetoothctl cmd line tool, and start an scan. i can connect to the device. I get the following output in homebridge
```
[02/08/2023, 07:49:26] [Govee] [BLE] unknown peripheral d4adfcff3576 connected!.
[02/08/2023, 07:49:37] [Govee] [BLE] unknown peripheral d4adfcff3576 disconnected!.
```
and after some seconds i get disconected. Is it possible that the connect is going thought, but when the command get send the connection is already closed again? 

Here is my command log on the pi
```
[bluetooth]# connect D4:AD:FC:FF:35:76
Attempting to connect to D4:AD:FC:FF:35:76
[CHG] Device D4:AD:FC:FF:35:76 Connected: yes
Connection successful
[CHG] Device D4:AD:FC:FF:35:76 ServicesResolved: yes
[CHG] Device D4:AD:FC:FF:35:76 ServicesResolved: no
[CHG] Device D4:AD:FC:FF:35:76 Connected: no
```
