### ISSUE TITLE
Space Heater 7135 shows light as well heater

### ISSUE THREAD

**Issue by RobertN82** [bwp91/homebridge-govee#662]
### What issue do you have? Please be as thorough and explicit as possible.
I have 8 Govee lights and as of today a new space heater (7315). HomeBridge finds it and adds it to Homekit as 3 devices: Heater, thermostat and a light. The home app shows me a temp control, heat/auto/off, a fan control and a light brightness slider.
The device obviously doesn't have a light, any way to remove it?

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI-X 

* Which version of Homebridge/HOOBS do you have?
HomeBridge v1.6.1

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi, Node.js Version v20.9.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
homebridge-govee v9.4.2

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
8x H601A - for some reason the log says it can't find two but they seem to work anyway?
1x H7135 - works but with a light

### Please paste any relevant logs below.

On boot
```
[01/12/2023, 15:48:41] [Govee] [LAN] client enabled and found 0 device(s).
[01/12/2023, 15:48:41] [Govee] [HTTP] client enabled and found 9 device(s).
[01/12/2023, 15:48:42] [Govee] [AWS] client enabled.
[01/12/2023, 15:48:42] [Govee] [BLE] client enabled.
[01/12/2023, 15:48:42] [Govee] [Space Heater] initialising with options {}.
[01/12/2023, 15:48:42] [Govee] [Space Heater] initialised with id [1E:A1:D4:AD:FC:85:97:84] [H7135].
[01/12/2023, 15:48:42] [Govee] [Studio Light 5] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[01/12/2023, 15:48:42] [Govee] [Studio Light 5] initialised with id [40:36:D4:AD:FC:9D:E1:A8] [H601A].
[01/12/2023, 15:48:42] [Govee] [Studio Light 4] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[01/12/2023, 15:48:42] [Govee] [Studio Light 4] initialised with id [61:17:D4:AD:FC:A6:4C:CE] [H601A].
[01/12/2023, 15:48:42] [Govee] [Studio Light 6] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[01/12/2023, 15:48:42] [Govee] [Studio Light 6] initialised with id [74:FE:D4:AD:FC:AB:91:7E] [H601A].
[01/12/2023, 15:48:42] [Govee] [Studio Light 7] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[01/12/2023, 15:48:42] [Govee] [Studio Light 7] initialised with id [49:D1:D4:AD:FC:AB:06:E8] [H601A].
[01/12/2023, 15:48:42] [Govee] [Studio Light 8] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[01/12/2023, 15:48:42] [Govee] [Studio Light 8] initialised with id [5C:26:D4:AD:FC:A6:4C:22] [H601A].
[01/12/2023, 15:48:42] [Govee] [Studio Light 2] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[01/12/2023, 15:48:42] [Govee] [Studio Light 2] initialised with id [30:42:D4:AD:FC:AB:96:CE] [H601A].
[01/12/2023, 15:48:42] [Govee] [Studio Light 1] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[01/12/2023, 15:48:42] [Govee] [Studio Light 1] initialised with id [14:FE:D4:AD:FC:9D:DE:90] [H601A].
[01/12/2023, 15:48:42] [Govee] [Studio Light 3] initialising with options {"adaptiveLightingShift":0,"aws":"enabled","ble":"enabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[01/12/2023, 15:48:42] [Govee] [Studio Light 3] initialised with id [35:1F:D4:AD:FC:AC:0D:54] [H601A].
[01/12/2023, 15:48:42] [Govee] [Studio Light 7] not using AWS connection as not connected to AWS.
[01/12/2023, 15:48:42] [Govee] [Studio Light 8] not using AWS connection as not connected to AWS.
[01/12/2023, 15:49:24] [Govee] [Studio Light 7] could not be updated as Promise timed out after 10000 milliseconds at Timeout._onTimeout (file:///usr/local/lib/node_modules/homebridge-govee/node_modules/p-timeout/index.js:79:64).
[01/12/2023, 15:49:24] [Govee] Could not retrieve TTRs as timeout of 10000ms exceeded at RedirectableRequest.handleRequestTimeout (file:///usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/adapters/http.js:643:16).
[01/12/2023, 15:49:24] [Govee] ✓ Setup complete. This plugin has been made with ♥ by bwp91, please consider a ☆ on GitHub if you are finding it useful!
[01/12/2023, 15:49:24] [Govee] [Studio Light 5] current colour [3600K / 278M].
[01/12/2023, 15:49:24] [Govee] [Studio Light 4] current colour [3600K / 278M].
[01/12/2023, 15:49:24] [Govee] [Studio Light 6] current colour [3600K / 278M].
[01/12/2023, 15:49:24] [Govee] [Space Heater] current temperature [20°C].
[01/12/2023, 15:49:24] [Govee] [Space Heater] current mode [low].
[01/12/2023, 15:49:24] [Govee] [Space Heater] current mode [auto].
[01/12/2023, 15:49:24] [Govee] [Studio Light 3] current colour [3600K / 278M].
[01/12/2023, 15:49:24] [Govee] [Studio Light 1] current colour [2700K / 370M].
[01/12/2023, 15:49:24] [Govee] [Studio Light 2] current colour [2700K / 370M].
[01/12/2023, 15:49:24] [Govee] [Studio Light 7] current colour [3600K / 278M].
[01/12/2023, 15:49:24] [Govee] [Studio Light 8] current colour [3600K / 278M].
[01/12/2023, 15:49:25] [Govee] [Studio Light 7] could not find device [d4:ad:fc:ab:06:e9].
[01/12/2023, 15:49:31] [Govee] [Studio Light 8] could not find device [d4:ad:fc:a6:4c:23].
[01/12/2023, 15:49:31] [Govee] [Studio Light 8] could not be updated as no connection method available, see https://shorturl.at/eCN04 for more info at file:///usr/local/lib/node_modules/homebridge-govee/lib/platform.js:1753:13.
```

When using the Heater
```
[01/12/2023, 15:54:44] [Govee] [Space Heater] current state [off].
[01/12/2023, 15:54:44] [Govee] [Space Heater] current mode [high].
[01/12/2023, 15:54:44] [Govee] [Space Heater] current mode [auto].
[01/12/2023, 15:55:00] [Govee] [Space Heater] current state [on].
[01/12/2023, 15:55:00] [Govee] [Space Heater] current mode [low].
```

When using the light
```
[01/12/2023, 15:55:48] [Govee] [Space Heater] current light [on].
[01/12/2023, 15:55:49] [Govee] [Space Heater] current brightness [1%].
[01/12/2023, 15:55:49] [Govee] [Space Heater] current brightness [81%].
[01/12/2023, 15:55:49] [Govee] [Space Heater] current brightness [100%].
```

**Comment by RobertN82** [comment]
Hi,

as per your post regarding batch closures, this one still seems unresolved as of v10.4.0 or v10.4.1-beta.1.

thanks!

**Comment by RobertN82** [comment]
Thanks for re-opening this. I see someone appears to have the same issue in #715.
