### ISSUE TITLE
Not receiving a list of devices 

### ISSUE THREAD

**Issue by urmilsetia** [bwp91/homebridge-govee#671]
### What issue do you have? Please be as thorough and explicit as possible.
Trying to add 4 H6008 bulbs, everything was working fine with T1 TV backlight.
Getting this error: `could not use existing access token as no data received from Govee server whilst obtaining devices at default.getDevices`

### Details of your setup.
* Do you use (1) Homebridge UI-X (2) Homebridge CLI or (3) HOOBS? 
Homebridge UI on macOS

* Which version of Homebridge/HOOBS do you have?
Homebridge v1.7.0 (HAP v0.11.1)

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
macOS 13.6.2 (22G320) with Node.js v20.10.0

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
Tried v10.2.0 and v10.1.0 

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
I have H6199, H6008

### Please paste any relevant logs below.

```
[12/13/2023, 10:36:33 AM] [Govee] [HTTP] could not use existing access token as no data received from Govee server whilst obtaining devices at default.getDevices (file:///usr/local/lib/node_modules/homebridge-govee/lib/connection/http.js:162:15).
[12/13/2023, 10:36:34 AM] [Govee] [HTTP] disabling client as The number of consecutive failed logins for this account has reached the maximum. Please try again in 5 minutes. at default.login (file:///usr/local/lib/node_modules/homebridge-govee/lib/connection/http.js:58:15).
[12/13/2023, 10:36:34 AM] [Govee] [AWS] disabling client as requires HTTP client.
[12/13/2023, 10:36:34 AM] [Govee] [BLE] disabling client as not supported on mac devices.
[12/13/2023, 10:36:34 AM] [Govee] ***** Disabling plugin [v10.1.0]. *****
[12/13/2023, 10:36:34 AM] [Govee] ***** No devices found to initialise. *****
```

**Comment by nackerr** [comment]
This is happening to me as well.

**Comment by y0m1g** [comment]
Same issue on my side as well.

**Comment by ventoryprod** [comment]
Same happened to me today

**Comment by schwaggy** [comment]
Same issue. 2 H5040 gateways and 20 H5054 sensors

[12/16/2023, 11:38:28 AM] [Govee] [HTTP] could not use existing access token as no data received from Govee server whilst obtaining devices at default.getDevices (file:///usr/local/lib/node_modules/homebridge-govee/lib/connection/http.js:162:15).
[12/16/2023, 11:38:29 AM] [Govee] [HTTP] disabling client as Request failed with status code 503 at settle (file:///usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12).
[12/16/2023, 11:38:29 AM] [Govee] [AWS] disabling client as requires HTTP client.
[12/16/2023, 11:38:29 AM] [Govee] [BLE] disabling client as disabled in config.
[12/16/2023, 11:38:29 AM] [Govee] ***** Disabling plugin [v10.2.0]. *****
[12/16/2023, 11:38:29 AM] [Govee] ***** No devices found to initialise. *****

**Comment by mikemucc** [comment]
Also seeing this issue as of today. Tried resetting password and removing special characters from the password. Also tried  forcing this client to logout through the iOS app. None of these helped.

Running in docker, `homebridge/homebridge:latest`. Did a `docker-compose pull && docker-compose up -d` as well, did not help. Upgraded node.js in the container (from 18 to 20), did not help

Relevant logs:
```
[Govee] Initialising plugin v10.2.0 | System linux | Node v20.10.0 | HB v1.7.0 | HAPNodeJS v0.11.1...
...
[12/16/2023, 3:49:10 PM] [Govee] [HTTP] could not use existing access token as no data received from Govee server whilst obtaining devices at default.getDevices (file:///homebridge/node_modules/homebridge-govee/lib/connection/http.js:162:15).
[12/16/2023, 3:49:11 PM] [Govee] [HTTP] disabling client as Request failed with status code 503 at settle (file:///homebridge/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12).
[12/16/2023, 3:49:11 PM] [Govee] [AWS] disabling client as requires HTTP client.
[12/16/2023, 3:49:11 PM] [Govee] [BLE] disabling client as ERR_DLOPEN_FAILED.
```

**Comment by sid7hartha** [comment]
Same issue for me.  Based on my data, I believe this started a couple days ago.

[12/17/2023, 4:56:22 AM] [Govee] [HTTP] could not use existing access token as no data received from Govee server whilst obtaining devices at default.getDevices (file:///var/lib/homebridge/node_modules/homebridge-govee/lib/connection/http.js:162:15).
[12/17/2023, 4:56:23 AM] [Govee] [HTTP] disabling client as Request failed with status code 503 at settle (file:///var/lib/homebridge/node_modules/homebridge-govee/node_modules/axios/lib/core/settle.js:19:12).
[12/17/2023, 4:56:23 AM] [Govee] [AWS] disabling client as requires HTTP client.
[12/17/2023, 4:56:23 AM] [Govee] [BLE] disabling client as ENODEV, No such device.
[12/17/2023, 4:56:23 AM] [Govee] ***** Disabling plugin [v10.2.0]. *****
[12/17/2023, 4:56:23 AM] [Govee] ***** No devices found to initialise. *****

**Comment by sid7hartha** [comment]
This problem just stopped for me yesterday -- I made no changes.  Does everyone else still have issues?

**Comment by schwaggy** [comment]
> This problem just stopped for me yesterday -- I made no changes. Does everyone else still have issues?

Same. Resolved on its own. I thought for sure it was an issue with the plug-in since the native app was working. Perhaps was a temporary issue with the API?

**Comment by shermanjoshua** [comment]
Adding a comment here because I searched for this exact message and found this issue. Would you prefer I open a new issue @bwp91 ?

**Comment by bwp91** [comment]
> Adding a comment here because I searched for this exact message and found this issue. Would you prefer I open a new issue @bwp91 ? 

Yes please, with homebridge logs of the plugin starting!
