### ISSUE TITLE
H6181 doesn’t work by Bluetooth

### ISSUE THREAD

**Issue by mirgopa** [bwp91/homebridge-govee#764]
Hello! I can’t connect to my H6181 LED strip by Bluetooth. The device is in HomeKit but I can’t turn on/off anyway (seems they don’t have connection).
The first problem that I had was with the abandonware Bluetooth lib, but I followed the “common error” section and installed the bluetooth-hci-socket in the plugin directory which I think solve the issue.

I have homebridge installed by apt in a orange-pi with Ubuntu Jammy (22.04.4 LTS) and I’m using homebridge-ui (v4.56.1) with all the newest versions.

- Homebridge [v1.7.0]
- Homebridge-govee [v10.5.0] (but now I’m trying with v10.4.1-beta.4 to see more details in logs)
- Homebridge Node [v20.12.1]

My system also is up to date by apt upgrade.

My last log after restart the HB was:
```
[4/8/2024, 2:08:21 AM] [Homebridge UI] Homebridge log truncated by orangepi.
[4/8/2024, 2:08:23 AM] [Homebridge UI] Homebridge restart request received
[4/8/2024, 2:08:24 AM] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[4/8/2024, 2:08:24 AM] [Homebridge UI] Sending SIGTERM to Homebridge
[4/8/2024, 2:08:24 AM] Got SIGTERM, shutting down Homebridge...
[4/8/2024, 2:08:29 AM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[4/8/2024, 2:08:34 AM] [HB Supervisor] Restarting Homebridge...
[4/8/2024, 2:08:34 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /var/lib/homebridge/node_modules --strict-plugin-resolution
[4/8/2024, 2:08:34 AM] [HB Supervisor] Started Homebridge v1.7.0 with PID: 2797
[4/8/2024, 2:08:36 AM] Loaded config.json with 0 accessories and 3 platforms.
[4/8/2024, 2:08:36 AM] Loaded 5 cached accessories from cachedAccessories.
[4/8/2024, 2:08:38 AM] ---
[4/8/2024, 2:08:39 AM] Loaded plugin: homebridge-govee@10.4.1-beta.4
[4/8/2024, 2:08:39 AM] Registering platform 'homebridge-govee.Govee'
[4/8/2024, 2:08:39 AM] ---
[4/8/2024, 2:08:39 AM] Loading 3 platforms...
[4/8/2024, 2:08:39 AM] [Govee] Initializing Govee platform...
[4/8/2024, 2:08:39 AM] [Govee] Initialising plugin v10.4.1-beta.4 | System linux | Node v20.12.1 | HB v1.7.0 | HAPNodeJS v0.11.1...
[4/8/2024, 2:08:39 AM] [Govee] Plugin initialised. Setting up accessories....
[4/8/2024, 2:08:39 AM] [Govee] ******************************************************************************************
[4/8/2024, 2:08:39 AM] [Govee] You are using a beta version of the plugin - you will experience more logging than normal.
[4/8/2024, 2:08:39 AM] [Govee] ******************************************************************************************
Setup Payload:
X-HM://
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ââââââââââââââ     
    ââââââââââââââ     
                       
[4/8/2024, 2:08:40 AM] Homebridge v1.7.0 (HAP v0.11.1) (Homebridge 344D) is running on port 51727.
[4/8/2024, 2:08:40 AM] [Govee] [LAN] disabling client as disabled in config.
[4/8/2024, 2:08:40 AM] [Govee] [HTTP] retrieved access token from cache.
[4/8/2024, 2:08:41 AM] [Govee] [HTTP] client enabled and found 1 device(s).
[4/8/2024, 2:08:41 AM] [Govee] [AWS] disabling client as disabled in config.
**[4/8/2024, 2:08:41 AM] [Govee] [BLE] disabling client as required hardware/packages not available.
[4/8/2024, 2:08:41 AM] [Govee] [Ambient light TV] will be visible but uncontrollable as BLE not available.**
[4/8/2024, 2:08:41 AM] [Govee] [Ambient light TV] initialising with options {"adaptiveLightingShift":0,"aws":"unsupported","ble":"disabled","brightnessStep":1,"colourSafeMode":false,"lan":"unsupported"}.
[4/8/2024, 2:08:41 AM] [Govee] [Ambient light TV] initialised with id [XX:XX:XX:XX:XX:XX:XX:XX] [H6181].
[4/8/2024, 2:08:45 AM] [Govee] â Setup complete. This plugin has been made with â¥ by bwp91, please consider a â on GitHub if you are finding it useful!
[4/8/2024, 2:08:45 AM] [Govee] [Ambient light TV] skipping adaptive lighting update as device is off or kelvin is same as before [2000K /500M].
[4/8/2024, 2:08:45 AM] [Govee] [Ambient light TV] skipping adaptive lighting update as device is off or kelvin is same as before [2000K /500M].
[4/8/2024, 2:08:45 AM] [Govee] [Ambient light TV] skipping adaptive lighting update as device is off or kelvin is same as before [2000K /500M].
[4/8/2024, 2:08:45 AM] [Govee] [Ambient light TV] skipping adaptive lighting update as device is off or kelvin is same as before [2000K /500M].
[4/8/2024, 2:08:45 AM] [Govee] [Ambient light TV] skipping adaptive lighting update as device is off or kelvin is same as before [2000K /500M].
[4/8/2024, 2:08:45 AM] [Govee] [Ambient light TV] skipping adaptive lighting update as device is off or kelvin is same as before [2000K /500M].
```

And when I try to turn on…
```
[4/8/2024, 2:20:17 AM] [Govee] [Ambient light TV] could not be updated as no connection method available, see https://shorturl.at/eCN04 for more info at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1764:13.
[4/8/2024, 2:20:22 AM] [Govee] [Ambient light TV] could not be updated as no connection method available, see https://shorturl.at/eCN04 for more info at file:///var/lib/homebridge/node_modules/homebridge-govee/lib/platform.js:1764:13.
[4/8/2024, 2:20:41 AM] [Govee] [Ambient light TV] skipping adaptive lighting update as device is off or kelvin is same as before [2000K /500M].
```

My config file:
```
{
"name": "Govee",
"username": "xxx@yyy.com",
"password": "xxx",
"awsDisable": true,
"bleDisable": false,
"lanDisable": true,
"lightDevices": [ {
            "label": "Ambient light",            
            "deviceId": "XX:XX:XX:XX:XX:XX:XX:XX",
            "showAs": "default",
            "customAddress": "YY:YY:YY:YY:YY:YY",
            "awsColourMode": "default"
}],
"platform": "Govee"
}
```

I’m stuck with this problem… I can’t do work properly.
Thanks for your support.

**Comment by mirgopa** [comment]
Please, any idea how to solve this??
