### ISSUE TITLE
Govee Aura - 400 Error

### ISSUE THREAD

**Issue by mording** [bwp91/homebridge-govee#79]
### What issue do you have? Please be as thorough and explicit as possible.
My Govee Aura will not adjust to higher than 39% within HomeKit without causing a 400 error. This then causes the device to stop responding temporarily in HomeKit. It appears that HomeKit is seeing 39% as 99-100%. Anything above 39% on the HomeKit slider outputs a brightness value of over 100% and this creates the error. 

### Details of your setup.
* Do you use (1) Homebridge (+ config-ui), (2) Homebridge (CLI) or (3) HOOBS? 
1 - Homebridge

* Which version of Homebridge/HOOBS do you have?
1.3.4 (current)

* Which platform do you run Homebridge/HOOBS on (e.g. Raspberry Pi/Windows/HOOBS Box)? Please also mention your version of Node.js/NPM if known.
Raspberry Pi

* Which version of this plugin (homebridge-govee) do you have? Has the issue started since upgrading from a previous version?
3.2.4

* Which Govee devices do you have that are causing issues? Please include product models if applicable.
Govee Aura - H6052

### Please paste any relevant logs below.

```
[23/06/2021, 23:52:22] [Govee] [Office Aura] could not be updated as Request failed with status code 400 at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[23/06/2021, 23:52:23] [Govee] [Office Aura] sending update {"name":"brightness","value":160}.
[23/06/2021, 23:52:23] [Govee] [Office Aura] could not be updated as Request failed with status code 400 at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[23/06/2021, 23:52:24] [Govee] [Office Aura] sending update {"name":"brightness","value":170}.
[23/06/2021, 23:52:24] [Govee] [Office Aura] could not be updated as Request failed with status code 400 at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[23/06/2021, 23:52:24] [Govee] [Office Aura] sending update {"name":"brightness","value":188}.
[23/06/2021, 23:52:25] [Govee] [Office Aura] could not be updated as Request failed with status code 400 at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[23/06/2021, 23:52:25] [Govee] [Office Aura] sending update {"name":"brightness","value":203}.
[23/06/2021, 23:52:25] [Govee] [Office Aura] could not be updated as Request failed with status code 400 at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[23/06/2021, 23:52:26] [Govee] [Office Aura] sending update {"name":"brightness","value":201}.
[23/06/2021, 23:52:26] [Govee] [Office Aura] could not be updated as Request failed with status code 400 at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[23/06/2021, 23:52:26] [Govee] [Office Aura] sending update {"name":"brightness","value":188}.
[23/06/2021, 23:52:27] [Govee] [Office Aura] could not be updated as Request failed with status code 400 at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[23/06/2021, 23:52:27] [Govee] [Office Aura] sending update {"name":"brightness","value":180}.
[23/06/2021, 23:52:28] [Govee] [Office Aura] could not be updated as Request failed with status code 400 at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[23/06/2021, 23:52:28] [Govee] [Office Aura] sending update {"name":"brightness","value":165}.
[23/06/2021, 23:52:28] [Govee] [Office Aura] could not be updated as Request failed with status code 400 at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[23/06/2021, 23:52:29] [Govee] [Office Aura] sending update {"name":"brightness","value":132}.
[23/06/2021, 23:52:29] [Govee] [Office Aura] could not be updated as Request failed with status code 400 at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.j
[23/06/2021, 23:53:07] [Govee] [Office Aura] sending update {"name":"brightness","value":79}.
[23/06/2021, 23:53:08] [Govee] [Office Aura] current brightness [31%].
[23/06/2021, 23:53:08] [Govee] [Office Aura] sending update {"name":"brightness","value":81}.
[23/06/2021, 23:53:09] [Govee] [Office Aura] current brightness [32%].
[23/06/2021, 23:53:09] [Govee] [Office Aura] sending update {"name":"brightness","value":84}.
[23/06/2021, 23:53:09] [Govee] [Office Aura] current brightness [33%].
[23/06/2021, 23:53:10] [Govee] [Office Aura] sending update {"name":"brightness","value":89}.
[23/06/2021, 23:53:10] [Govee] [Office Aura] current brightness [35%].
[23/06/2021, 23:53:10] [Govee] [Office Aura] sending update {"name":"brightness","value":91}.
[23/06/2021, 23:53:11] [Govee] [Office Aura] current brightness [36%].
[23/06/2021, 23:53:11] [Govee] [Office Aura] sending update {"name":"brightness","value":94}.
[23/06/2021, 23:53:12] [Govee] [Office Aura] current brightness [37%].
[23/06/2021, 23:53:12] [Govee] [Office Aura] sending update {"name":"brightness","value":97}.
[23/06/2021, 23:53:12] [Govee] [Office Aura] current brightness [38%].
[23/06/2021, 23:53:14] [Govee] [Office Aura] sending update {"name":"brightness","value":99}.
[23/06/2021, 23:53:14] [Govee] [Office Aura] current brightness [39%].
```

**Comment by bwp91** [comment]
Hi @mording 

Could you update to the beta version of the plugin, at least v3.2.5-beta.4, and confirm this is fixed?

Thanks for this

**Comment by mording** [comment]
Morning

That did the trick! I'll let you know if I come across any issues with the beta build.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by bwp91** [comment]
Great, thank you!
