### ISSUE TITLE
Disabling plugin error  govee v3.5.1 HB v1.3.4

### ISSUE THREAD

**Issue by skir0cket** [bwp91/homebridge-govee#87]
recently updated the plugin and now seem to be getting this error, also its deleted my device.

[15/07/2021, 19:10:23] [Govee] Disabling API client as timeout of 10000ms exceeded at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[15/07/2021, 19:10:23] [Govee] Disabling BLE client as no enabled devices configured at GoveePlatform.pluginSetup (/usr/local/lib/node_modules/homebridge-govee/lib/index.js:310:17).
[15/07/2021, 19:10:23] [Govee] ***** Disabling plugin. *****
[15/07/2021, 19:10:23] [Govee] ***** No devices found to initialise at GoveePlatform.pluginSetup (/usr/local/lib/node_modules/homebridge-govee/lib/index.js:390:15). *****

EDIT -  I've reverted back to v3.5.0 for now as it seems to work fine on this version.

**Comment by bwp91** [comment]
Hi @skir0cket,

Could you update to v3.5.2-beta.5 via the homebridge-ui to see if this works?

The issue you had looks like it was an internet problem or govee server problem, that coincidentally happened when you updated. The URL that the plugin uses to get a device list had not changed between v3.5.0 and v3.5.1.

On this 3.5.2-beta.5 version, the plugin will no longer remove the homebridge accessories if an error like this happens.

Currently, if there is a connection problem and the plugin can't retrieve a device list when the plugin initialises, it disables itself. I will improve this in a future version of the plugin with a retry after e.g. 30 seconds.

**Comment by skir0cket** [comment]
hi I've updated to the beta but have the same issue with the plugin disabling.

**Comment by bwp91** [comment]
can you get logs from both
* the plugin initialising on v3.5.0, and
* the plugin initialising on the beta.

Everything from

```
[Govee] Plugin initialised. Setting up accessories....
```

to 

```
[Govee] ✓ Setup complete ||| OR ||| Disabling plugin...
```

**Comment by skir0cket** [comment]
govee v3.5.1

[16/07/2021, 06:30:19] [Govee] Plugin initialised. Setting up accessories....
[16/07/2021, 06:30:41] [Govee] Disabling HTTP client as timeout of 5000ms exceeded at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[16/07/2021, 06:30:56] [Govee] Disabling API client as timeout of 10000ms exceeded at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[16/07/2021, 06:30:56] [Govee] Disabling BLE client as no enabled devices configured at GoveePlatform.pluginSetup (/usr/local/lib/node_modules/homebridge-govee/lib/index.js:310:17).
[16/07/2021, 06:30:56] [Govee] ***** Disabling plugin. *****
[16/07/2021, 06:30:56] [Govee] ***** No devices found to initialise at GoveePlatform.pluginSetup (/usr/local/lib/node_modules/homebridge-govee/lib/index.js:390:15). *****c
[16/07/2021, 06:30:56] [Govee] ***** No devices found to initialise at GoveePlatform.pluginSetup (/usr/local/lib/node_modules/homebridge-govee/lib/index.js:390:15). *****

I saw that beta 6 was available so updated to that version which now seems to be working for me.

**Comment by bwp91** [comment]
Please double check the logs when the plugin starts, the beta version you are on will keep retrying the connection to govee until it is successful. 

So long as you can (eventually) see the 

```
[Govee] ✓ Setup complete
```

entry, then the plugin has loaded okay.

**Comment by bwp91** [comment]
Hopefully the plugin has been working recently and v3.6.0 works too.

**Comment by skir0cket** [comment]
> Hopefully the plugin has been working recently and v3.6.0 works too.

thanks its been working fine so far if I get anymore issues I will let you know.

**Comment by skir0cket** [comment]
hi it seems to have stopped working again, it shows that its switching on and off on homebridge but is not actually switching the light on or off.

[24/07/2021, 07:10:40] [Govee] Plugin initialised. Setting up accessories....
[24/07/2021, 07:11:02] [Govee] Unable to reach Govee, retrying in 30 seconds [HTTP - getDevices() - ECONNABORTED].
24/07/2021, 07:11:50] [Govee] Unable to reach Govee, retrying in 30 seconds [HTTP - getDevices() - ECONNABORTED].
[24/07/2021, 07:12:23] [Govee] Disabling BLE client as no enabled devices configured.
[24/07/2021, 07:12:23] [Govee] [Tv lights] initialising with options {"adaptiveLightingShift":0,"brightnessStep":1,"enableAWS":"disabled","enableBT":"disabled","logging":"standard"}.
[24/07/2021, 07:12:23] [Govee] [Tv lights] initialised with id [64:10:A4:C1:38:B2:43:5B].
[24/07/2021, 07:12:23] [Govee] ✓ Setup complete. This plugin has been made with ♥ by bwp91 from the UK!

[24/07/2021, 07:12:48] [Govee] [Tv lights] current state [off].
[24/07/2021, 07:12:51] [Govee] [Tv lights] current state [on].
[24/07/2021, 07:13:49] [Govee] [Tv lights] current state [off].
[24/07/2021, 07:13:53] [Govee] [Tv lights] current state [on].

**Comment by bwp91** [comment]
Are you still having issues with this?

**Comment by skir0cket** [comment]
Yeah I can’t get the lights to connect at all it says setup is complete but they don’t function through homebridge.

**Comment by bwp91** [comment]
Can you try changing your govee password in the govee app then updating the plugin config?

I’m stuck with this because I don’t know how the process for logging in works for everyone else but in you case isn’t working :/

**Comment by skir0cket** [comment]
Ok I’ll give this a try later tonight after work and let you know how it goes.

**Comment by skir0cket** [comment]
reset password and reconnected to wifi in the govee app, seems to be working fine now.

**Comment by jp-lno** [comment]
Hello @bwp91 ,

Kind of same issue for me. And updating password solved it. I think you can add this part in your common Error wiki page.

**Comment by bwp91** [comment]
What is the error that is shown?

**Comment by jp-lno** [comment]
I only have this in log (debug:true)

29/11/2021, 12:17:54] [Govee] Disabling HTTP client as timeout of 10000ms exceeded at createError (/usr/local/lib/node_modules/homebridge-govee/node_modules/axios/lib/core/createError.js:16:15).
[29/11/2021, 12:18:01] [Govee] Disabling BLE client as no enabled devices configured.
[29/11/2021, 12:18:01] [Govee] ***** Disabling plugin. *****
[29/11/2021, 12:18:01] [Govee] ***** No devices found to initialise. *****

Issue appear after updating to 4.18.0. Rollback did not change anything.
